################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/common_test_1.c \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/common_test_1_v1.c \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/common_test_1_v2.c \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/common_test_2.c \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/common_test_3.c \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/defsym_test.c \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/discard_locals_relocatable_test.c \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/discard_locals_test.c \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/dyn_weak_ref_1.c \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/dyn_weak_ref_2.c \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/exclude_libs_test.c \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/exclude_libs_test_1.c \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/exclude_libs_test_2.c \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/exclude_libs_test_3.c \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/gc_dynamic_list_test.c \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/gdb_index_test_3.c \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/hidden_test_1.c \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/hidden_test_main.c \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/ifuncdep2.c \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/ifuncmain1.c \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/ifuncmain1vis.c \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/ifuncmain2.c \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/ifuncmain3.c \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/ifuncmain4.c \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/ifuncmain5.c \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/ifuncmain6pie.c \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/ifuncmain7.c \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/ifuncmod1.c \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/ifuncmod3.c \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/ifuncmod5.c \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/ifuncmod6.c \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/ifuncvar1.c \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/ifuncvar2.c \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/ifuncvar3.c \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/incremental_test_1.c \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/incremental_test_2.c \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/initpri1.c \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/initpri2.c \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/initpri3.c \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/justsyms_exec.c \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/justsyms_lib.c \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/large.c \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/no_version_test.c \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/plugin_common_test_1.c \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/plugin_common_test_2.c \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/plugin_section_order.c \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/plugin_test.c \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/plugin_test_7_1.c \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/plugin_test_7_2.c \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/pr14265.c \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/script_test_11.c \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/start_lib_test_1.c \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/start_lib_test_2.c \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/start_lib_test_3.c \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/start_lib_test_main.c \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/strong_ref_weak_def_1.c \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/strong_ref_weak_def_2.c \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/tls_test_c.c \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/ver_test_6.c 

CC_SRCS += \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/basic_test.cc \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/binary_test.cc \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/binary_unittest.cc \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/constructor_test.cc \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/copy_test.cc \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/copy_test_1.cc \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/copy_test_2.cc \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/copy_test_v1.cc \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/debug_msg.cc \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/dwp_test_1.cc \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/dwp_test_1b.cc \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/dwp_test_2.cc \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/dwp_test_main.cc \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/dynamic_list_2.cc \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/dynamic_list_lib1.cc \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/dynamic_list_lib2.cc \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/ehdr_start_def.cc \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/ehdr_start_test.cc \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/exception_test_1.cc \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/exception_test_2.cc \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/exception_test_main.cc \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/final_layout.cc \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/gc_comdat_test_1.cc \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/gc_comdat_test_2.cc \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/gc_orphan_section_test.cc \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/gc_tls_test.cc \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/gdb_index_test.cc \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/icf_keep_unique_test.cc \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/icf_preemptible_functions_test.cc \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/icf_safe_so_test.cc \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/icf_safe_test.cc \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/icf_sht_rel_addend_test_1.cc \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/icf_sht_rel_addend_test_2.cc \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/icf_string_merge_test.cc \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/icf_test.cc \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/icf_virtual_function_folding_test.cc \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/incr_comdat_test_1.cc \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/incr_comdat_test_2_v1.cc \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/incr_comdat_test_2_v2.cc \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/incr_comdat_test_2_v3.cc \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/justsyms_1.cc \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/justsyms_2.cc \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/large_symbol_alignment.cc \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/leb128_unittest.cc \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/many_sections_test.cc \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/merge_string_literals_1.cc \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/merge_string_literals_2.cc \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/missing_key_func.cc \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/object_unittest.cc \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/odr_violation1.cc \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/odr_violation2.cc \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/pie_copyrelocs_shared_test.cc \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/pie_copyrelocs_test.cc \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/plugin_final_layout.cc \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/protected_1.cc \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/protected_2.cc \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/protected_3.cc \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/protected_4.cc \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/protected_main_1.cc \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/protected_main_2.cc \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/protected_main_3.cc \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/relro_test.cc \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/relro_test_main.cc \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/script_test_1.cc \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/script_test_2.cc \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/script_test_2a.cc \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/script_test_2b.cc \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/script_test_5.cc \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/script_test_9.cc \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/searched_file_test.cc \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/searched_file_test_lib.cc \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/section_sorting_name.cc \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/test.cc \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/testfile.cc \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/testmain.cc \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/text_section_grouping.cc \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/thin_archive_main.cc \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/thin_archive_test_1.cc \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/thin_archive_test_2.cc \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/thin_archive_test_3.cc \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/thin_archive_test_4.cc \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/tls_test.cc \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/tls_test_file2.cc \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/tls_test_main.cc \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/two_file_test_1.cc \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/two_file_test_1_v1.cc \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/two_file_test_1b.cc \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/two_file_test_1b_v1.cc \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/two_file_test_2.cc \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/two_file_test_2_tls.cc \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/two_file_test_2_v1.cc \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/two_file_test_main.cc \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/two_file_test_tls.cc \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/undef_symbol.cc \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/undef_symbol_main.cc \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/ver_matching_def.cc \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/ver_test_1.cc \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/ver_test_2.cc \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/ver_test_3.cc \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/ver_test_4.cc \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/ver_test_5.cc \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/ver_test_7.cc \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/ver_test_9.cc \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/ver_test_main.cc \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/ver_test_main_2.cc \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/weak_alias_test_1.cc \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/weak_alias_test_2.cc \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/weak_alias_test_3.cc \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/weak_alias_test_4.cc \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/weak_alias_test_5.cc \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/weak_alias_test_main.cc \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/weak_plt_main.cc \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/weak_plt_shared.cc \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/weak_test.cc \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/weak_undef_file1.cc \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/weak_undef_file2.cc \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/weak_undef_file3.cc \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/weak_undef_file4.cc \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/weak_undef_test.cc \
../nachos_initialCode/tools/binutils-2.25/gold/testsuite/weak_undef_test_2.cc 

OBJS += \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/basic_test.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/binary_test.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/binary_unittest.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/common_test_1.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/common_test_1_v1.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/common_test_1_v2.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/common_test_2.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/common_test_3.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/constructor_test.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/copy_test.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/copy_test_1.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/copy_test_2.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/copy_test_v1.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/debug_msg.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/defsym_test.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/discard_locals_relocatable_test.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/discard_locals_test.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/dwp_test_1.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/dwp_test_1b.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/dwp_test_2.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/dwp_test_main.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/dyn_weak_ref_1.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/dyn_weak_ref_2.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/dynamic_list_2.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/dynamic_list_lib1.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/dynamic_list_lib2.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/ehdr_start_def.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/ehdr_start_test.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/exception_test_1.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/exception_test_2.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/exception_test_main.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/exclude_libs_test.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/exclude_libs_test_1.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/exclude_libs_test_2.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/exclude_libs_test_3.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/final_layout.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/gc_comdat_test_1.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/gc_comdat_test_2.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/gc_dynamic_list_test.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/gc_orphan_section_test.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/gc_tls_test.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/gdb_index_test.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/gdb_index_test_3.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/hidden_test_1.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/hidden_test_main.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/icf_keep_unique_test.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/icf_preemptible_functions_test.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/icf_safe_so_test.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/icf_safe_test.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/icf_sht_rel_addend_test_1.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/icf_sht_rel_addend_test_2.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/icf_string_merge_test.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/icf_test.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/icf_virtual_function_folding_test.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/ifuncdep2.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/ifuncmain1.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/ifuncmain1vis.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/ifuncmain2.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/ifuncmain3.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/ifuncmain4.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/ifuncmain5.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/ifuncmain6pie.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/ifuncmain7.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/ifuncmod1.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/ifuncmod3.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/ifuncmod5.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/ifuncmod6.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/ifuncvar1.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/ifuncvar2.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/ifuncvar3.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/incr_comdat_test_1.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/incr_comdat_test_2_v1.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/incr_comdat_test_2_v2.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/incr_comdat_test_2_v3.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/incremental_test_1.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/incremental_test_2.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/initpri1.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/initpri2.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/initpri3.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/justsyms_1.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/justsyms_2.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/justsyms_exec.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/justsyms_lib.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/large.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/large_symbol_alignment.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/leb128_unittest.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/many_sections_test.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/merge_string_literals_1.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/merge_string_literals_2.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/missing_key_func.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/no_version_test.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/object_unittest.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/odr_violation1.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/odr_violation2.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/pie_copyrelocs_shared_test.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/pie_copyrelocs_test.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/plugin_common_test_1.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/plugin_common_test_2.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/plugin_final_layout.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/plugin_section_order.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/plugin_test.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/plugin_test_7_1.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/plugin_test_7_2.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/pr14265.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/protected_1.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/protected_2.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/protected_3.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/protected_4.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/protected_main_1.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/protected_main_2.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/protected_main_3.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/relro_test.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/relro_test_main.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/script_test_1.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/script_test_11.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/script_test_2.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/script_test_2a.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/script_test_2b.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/script_test_5.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/script_test_9.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/searched_file_test.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/searched_file_test_lib.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/section_sorting_name.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/start_lib_test_1.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/start_lib_test_2.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/start_lib_test_3.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/start_lib_test_main.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/strong_ref_weak_def_1.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/strong_ref_weak_def_2.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/test.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/testfile.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/testmain.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/text_section_grouping.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/thin_archive_main.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/thin_archive_test_1.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/thin_archive_test_2.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/thin_archive_test_3.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/thin_archive_test_4.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/tls_test.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/tls_test_c.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/tls_test_file2.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/tls_test_main.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/two_file_test_1.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/two_file_test_1_v1.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/two_file_test_1b.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/two_file_test_1b_v1.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/two_file_test_2.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/two_file_test_2_tls.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/two_file_test_2_v1.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/two_file_test_main.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/two_file_test_tls.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/undef_symbol.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/undef_symbol_main.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/ver_matching_def.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/ver_test_1.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/ver_test_2.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/ver_test_3.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/ver_test_4.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/ver_test_5.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/ver_test_6.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/ver_test_7.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/ver_test_9.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/ver_test_main.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/ver_test_main_2.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/weak_alias_test_1.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/weak_alias_test_2.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/weak_alias_test_3.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/weak_alias_test_4.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/weak_alias_test_5.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/weak_alias_test_main.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/weak_plt_main.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/weak_plt_shared.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/weak_test.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/weak_undef_file1.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/weak_undef_file2.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/weak_undef_file3.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/weak_undef_file4.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/weak_undef_test.o \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/weak_undef_test_2.o 

C_DEPS += \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/common_test_1.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/common_test_1_v1.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/common_test_1_v2.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/common_test_2.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/common_test_3.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/defsym_test.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/discard_locals_relocatable_test.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/discard_locals_test.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/dyn_weak_ref_1.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/dyn_weak_ref_2.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/exclude_libs_test.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/exclude_libs_test_1.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/exclude_libs_test_2.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/exclude_libs_test_3.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/gc_dynamic_list_test.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/gdb_index_test_3.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/hidden_test_1.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/hidden_test_main.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/ifuncdep2.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/ifuncmain1.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/ifuncmain1vis.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/ifuncmain2.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/ifuncmain3.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/ifuncmain4.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/ifuncmain5.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/ifuncmain6pie.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/ifuncmain7.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/ifuncmod1.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/ifuncmod3.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/ifuncmod5.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/ifuncmod6.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/ifuncvar1.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/ifuncvar2.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/ifuncvar3.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/incremental_test_1.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/incremental_test_2.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/initpri1.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/initpri2.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/initpri3.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/justsyms_exec.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/justsyms_lib.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/large.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/no_version_test.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/plugin_common_test_1.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/plugin_common_test_2.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/plugin_section_order.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/plugin_test.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/plugin_test_7_1.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/plugin_test_7_2.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/pr14265.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/script_test_11.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/start_lib_test_1.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/start_lib_test_2.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/start_lib_test_3.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/start_lib_test_main.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/strong_ref_weak_def_1.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/strong_ref_weak_def_2.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/tls_test_c.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/ver_test_6.d 

CC_DEPS += \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/basic_test.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/binary_test.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/binary_unittest.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/constructor_test.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/copy_test.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/copy_test_1.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/copy_test_2.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/copy_test_v1.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/debug_msg.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/dwp_test_1.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/dwp_test_1b.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/dwp_test_2.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/dwp_test_main.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/dynamic_list_2.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/dynamic_list_lib1.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/dynamic_list_lib2.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/ehdr_start_def.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/ehdr_start_test.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/exception_test_1.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/exception_test_2.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/exception_test_main.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/final_layout.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/gc_comdat_test_1.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/gc_comdat_test_2.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/gc_orphan_section_test.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/gc_tls_test.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/gdb_index_test.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/icf_keep_unique_test.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/icf_preemptible_functions_test.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/icf_safe_so_test.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/icf_safe_test.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/icf_sht_rel_addend_test_1.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/icf_sht_rel_addend_test_2.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/icf_string_merge_test.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/icf_test.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/icf_virtual_function_folding_test.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/incr_comdat_test_1.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/incr_comdat_test_2_v1.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/incr_comdat_test_2_v2.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/incr_comdat_test_2_v3.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/justsyms_1.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/justsyms_2.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/large_symbol_alignment.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/leb128_unittest.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/many_sections_test.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/merge_string_literals_1.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/merge_string_literals_2.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/missing_key_func.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/object_unittest.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/odr_violation1.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/odr_violation2.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/pie_copyrelocs_shared_test.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/pie_copyrelocs_test.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/plugin_final_layout.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/protected_1.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/protected_2.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/protected_3.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/protected_4.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/protected_main_1.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/protected_main_2.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/protected_main_3.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/relro_test.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/relro_test_main.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/script_test_1.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/script_test_2.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/script_test_2a.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/script_test_2b.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/script_test_5.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/script_test_9.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/searched_file_test.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/searched_file_test_lib.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/section_sorting_name.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/test.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/testfile.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/testmain.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/text_section_grouping.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/thin_archive_main.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/thin_archive_test_1.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/thin_archive_test_2.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/thin_archive_test_3.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/thin_archive_test_4.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/tls_test.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/tls_test_file2.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/tls_test_main.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/two_file_test_1.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/two_file_test_1_v1.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/two_file_test_1b.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/two_file_test_1b_v1.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/two_file_test_2.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/two_file_test_2_tls.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/two_file_test_2_v1.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/two_file_test_main.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/two_file_test_tls.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/undef_symbol.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/undef_symbol_main.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/ver_matching_def.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/ver_test_1.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/ver_test_2.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/ver_test_3.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/ver_test_4.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/ver_test_5.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/ver_test_7.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/ver_test_9.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/ver_test_main.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/ver_test_main_2.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/weak_alias_test_1.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/weak_alias_test_2.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/weak_alias_test_3.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/weak_alias_test_4.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/weak_alias_test_5.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/weak_alias_test_main.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/weak_plt_main.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/weak_plt_shared.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/weak_test.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/weak_undef_file1.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/weak_undef_file2.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/weak_undef_file3.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/weak_undef_file4.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/weak_undef_test.d \
./nachos_initialCode/tools/binutils-2.25/gold/testsuite/weak_undef_test_2.d 


# Each subdirectory must supply rules for building sources it contributes
nachos_initialCode/tools/binutils-2.25/gold/testsuite/%.o: ../nachos_initialCode/tools/binutils-2.25/gold/testsuite/%.cc
	@echo 'Building file: $<'
	@echo 'Invoking: Cross G++ Compiler'
	g++ -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

nachos_initialCode/tools/binutils-2.25/gold/testsuite/%.o: ../nachos_initialCode/tools/binutils-2.25/gold/testsuite/%.c
	@echo 'Building file: $<'
	@echo 'Invoking: Cross GCC Compiler'
	gcc -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


