################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/chan.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/cpuprof.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/env_posix.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/getncpu-bsd.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/getncpu-irix.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/getncpu-linux.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/getncpu-none.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/getncpu-solaris.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-append.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-assert-interface.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-assert.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-breakpoint.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-byte-array-to-string.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-caller.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-callers.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-can-convert-interface.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-cdiv.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-cgo.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-check-interface.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-construct-map.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-convert-interface.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-copy.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-defer.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-deferred-recover.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-eface-compare.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-eface-val-compare.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-fieldtrack.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-getgoroot.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-int-array-to-string.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-int-to-string.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-interface-compare.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-interface-eface-compare.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-interface-val-compare.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-main.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-make-slice.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-map-delete.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-map-index.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-map-len.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-map-range.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-matherr.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-memcmp.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-nanotime.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-new-map.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-new.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-nosys.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-now.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-panic.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-print.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-recover.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-reflect-call.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-reflect-map.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-rune.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-runtime-error.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-setenv.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-signal.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-strcmp.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-string-to-byte-array.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-string-to-int-array.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-strplus.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-strslice.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-traceback.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-trampoline.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-type-complex.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-type-eface.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-type-error.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-type-float.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-type-identity.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-type-interface.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-type-string.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-typedesc-equal.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-typestring.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-unsafe-new.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-unsafe-newarray.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-unsafe-pointer.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-unwind.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-varargs.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/goc2c.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/lfstack.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/lock_futex.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/lock_sema.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/mcache.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/mcentral.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/mem.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/mem_posix_memalign.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/mfinal.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/mfixalloc.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/mgc0.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/mheap.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/msize.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/netpoll_epoll.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/netpoll_kqueue.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/netpoll_select.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/netpoll_stub.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/panic.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/parfor.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/print.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/proc.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/rtems-task-variable-add.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/runtime.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/signal_unix.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/thread-linux.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/thread-sema.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/thread.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/yield.c 

OBJS += \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/chan.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/cpuprof.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/env_posix.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/getncpu-bsd.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/getncpu-irix.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/getncpu-linux.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/getncpu-none.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/getncpu-solaris.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-append.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-assert-interface.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-assert.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-breakpoint.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-byte-array-to-string.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-caller.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-callers.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-can-convert-interface.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-cdiv.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-cgo.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-check-interface.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-construct-map.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-convert-interface.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-copy.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-defer.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-deferred-recover.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-eface-compare.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-eface-val-compare.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-fieldtrack.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-getgoroot.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-int-array-to-string.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-int-to-string.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-interface-compare.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-interface-eface-compare.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-interface-val-compare.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-main.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-make-slice.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-map-delete.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-map-index.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-map-len.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-map-range.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-matherr.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-memcmp.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-nanotime.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-new-map.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-new.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-nosys.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-now.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-panic.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-print.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-recover.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-reflect-call.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-reflect-map.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-rune.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-runtime-error.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-setenv.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-signal.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-strcmp.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-string-to-byte-array.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-string-to-int-array.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-strplus.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-strslice.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-traceback.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-trampoline.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-type-complex.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-type-eface.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-type-error.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-type-float.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-type-identity.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-type-interface.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-type-string.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-typedesc-equal.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-typestring.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-unsafe-new.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-unsafe-newarray.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-unsafe-pointer.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-unwind.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-varargs.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/goc2c.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/lfstack.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/lock_futex.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/lock_sema.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/mcache.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/mcentral.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/mem.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/mem_posix_memalign.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/mfinal.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/mfixalloc.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/mgc0.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/mheap.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/msize.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/netpoll_epoll.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/netpoll_kqueue.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/netpoll_select.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/netpoll_stub.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/panic.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/parfor.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/print.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/proc.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/rtems-task-variable-add.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/runtime.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/signal_unix.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/thread-linux.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/thread-sema.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/thread.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/yield.o 

C_DEPS += \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/chan.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/cpuprof.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/env_posix.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/getncpu-bsd.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/getncpu-irix.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/getncpu-linux.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/getncpu-none.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/getncpu-solaris.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-append.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-assert-interface.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-assert.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-breakpoint.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-byte-array-to-string.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-caller.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-callers.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-can-convert-interface.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-cdiv.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-cgo.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-check-interface.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-construct-map.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-convert-interface.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-copy.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-defer.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-deferred-recover.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-eface-compare.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-eface-val-compare.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-fieldtrack.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-getgoroot.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-int-array-to-string.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-int-to-string.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-interface-compare.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-interface-eface-compare.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-interface-val-compare.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-main.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-make-slice.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-map-delete.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-map-index.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-map-len.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-map-range.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-matherr.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-memcmp.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-nanotime.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-new-map.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-new.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-nosys.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-now.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-panic.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-print.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-recover.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-reflect-call.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-reflect-map.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-rune.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-runtime-error.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-setenv.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-signal.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-strcmp.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-string-to-byte-array.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-string-to-int-array.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-strplus.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-strslice.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-traceback.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-trampoline.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-type-complex.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-type-eface.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-type-error.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-type-float.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-type-identity.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-type-interface.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-type-string.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-typedesc-equal.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-typestring.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-unsafe-new.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-unsafe-newarray.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-unsafe-pointer.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-unwind.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/go-varargs.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/goc2c.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/lfstack.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/lock_futex.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/lock_sema.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/mcache.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/mcentral.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/mem.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/mem_posix_memalign.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/mfinal.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/mfixalloc.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/mgc0.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/mheap.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/msize.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/netpoll_epoll.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/netpoll_kqueue.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/netpoll_select.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/netpoll_stub.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/panic.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/parfor.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/print.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/proc.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/rtems-task-variable-add.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/runtime.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/signal_unix.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/thread-linux.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/thread-sema.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/thread.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/yield.d 


# Each subdirectory must supply rules for building sources it contributes
nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/%.o: ../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgo/runtime/%.c
	@echo 'Building file: $<'
	@echo 'Invoking: Cross GCC Compiler'
	gcc -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


