################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../nachos_initialCode/tools/binutils-2.25/gas/config/atof-ieee.c \
../nachos_initialCode/tools/binutils-2.25/gas/config/atof-vax.c \
../nachos_initialCode/tools/binutils-2.25/gas/config/bfin-lex-wrapper.c \
../nachos_initialCode/tools/binutils-2.25/gas/config/e-crisaout.c \
../nachos_initialCode/tools/binutils-2.25/gas/config/e-criself.c \
../nachos_initialCode/tools/binutils-2.25/gas/config/e-i386aout.c \
../nachos_initialCode/tools/binutils-2.25/gas/config/e-i386coff.c \
../nachos_initialCode/tools/binutils-2.25/gas/config/e-i386elf.c \
../nachos_initialCode/tools/binutils-2.25/gas/config/e-mipself.c \
../nachos_initialCode/tools/binutils-2.25/gas/config/obj-aout.c \
../nachos_initialCode/tools/binutils-2.25/gas/config/obj-coff-seh.c \
../nachos_initialCode/tools/binutils-2.25/gas/config/obj-coff.c \
../nachos_initialCode/tools/binutils-2.25/gas/config/obj-ecoff.c \
../nachos_initialCode/tools/binutils-2.25/gas/config/obj-elf.c \
../nachos_initialCode/tools/binutils-2.25/gas/config/obj-evax.c \
../nachos_initialCode/tools/binutils-2.25/gas/config/obj-fdpicelf.c \
../nachos_initialCode/tools/binutils-2.25/gas/config/obj-macho.c \
../nachos_initialCode/tools/binutils-2.25/gas/config/obj-multi.c \
../nachos_initialCode/tools/binutils-2.25/gas/config/obj-som.c \
../nachos_initialCode/tools/binutils-2.25/gas/config/tc-aarch64.c \
../nachos_initialCode/tools/binutils-2.25/gas/config/tc-alpha.c \
../nachos_initialCode/tools/binutils-2.25/gas/config/tc-arc.c \
../nachos_initialCode/tools/binutils-2.25/gas/config/tc-arm.c \
../nachos_initialCode/tools/binutils-2.25/gas/config/tc-avr.c \
../nachos_initialCode/tools/binutils-2.25/gas/config/tc-bfin.c \
../nachos_initialCode/tools/binutils-2.25/gas/config/tc-cr16.c \
../nachos_initialCode/tools/binutils-2.25/gas/config/tc-cris.c \
../nachos_initialCode/tools/binutils-2.25/gas/config/tc-crx.c \
../nachos_initialCode/tools/binutils-2.25/gas/config/tc-d10v.c \
../nachos_initialCode/tools/binutils-2.25/gas/config/tc-d30v.c \
../nachos_initialCode/tools/binutils-2.25/gas/config/tc-dlx.c \
../nachos_initialCode/tools/binutils-2.25/gas/config/tc-epiphany.c \
../nachos_initialCode/tools/binutils-2.25/gas/config/tc-fr30.c \
../nachos_initialCode/tools/binutils-2.25/gas/config/tc-frv.c \
../nachos_initialCode/tools/binutils-2.25/gas/config/tc-generic.c \
../nachos_initialCode/tools/binutils-2.25/gas/config/tc-h8300.c \
../nachos_initialCode/tools/binutils-2.25/gas/config/tc-hppa.c \
../nachos_initialCode/tools/binutils-2.25/gas/config/tc-i370.c \
../nachos_initialCode/tools/binutils-2.25/gas/config/tc-i386-intel.c \
../nachos_initialCode/tools/binutils-2.25/gas/config/tc-i386.c \
../nachos_initialCode/tools/binutils-2.25/gas/config/tc-i860.c \
../nachos_initialCode/tools/binutils-2.25/gas/config/tc-i960.c \
../nachos_initialCode/tools/binutils-2.25/gas/config/tc-ia64.c \
../nachos_initialCode/tools/binutils-2.25/gas/config/tc-ip2k.c \
../nachos_initialCode/tools/binutils-2.25/gas/config/tc-iq2000.c \
../nachos_initialCode/tools/binutils-2.25/gas/config/tc-lm32.c \
../nachos_initialCode/tools/binutils-2.25/gas/config/tc-m32c.c \
../nachos_initialCode/tools/binutils-2.25/gas/config/tc-m32r.c \
../nachos_initialCode/tools/binutils-2.25/gas/config/tc-m68hc11.c \
../nachos_initialCode/tools/binutils-2.25/gas/config/tc-m68k.c \
../nachos_initialCode/tools/binutils-2.25/gas/config/tc-mcore.c \
../nachos_initialCode/tools/binutils-2.25/gas/config/tc-mep.c \
../nachos_initialCode/tools/binutils-2.25/gas/config/tc-metag.c \
../nachos_initialCode/tools/binutils-2.25/gas/config/tc-microblaze.c \
../nachos_initialCode/tools/binutils-2.25/gas/config/tc-mips.c \
../nachos_initialCode/tools/binutils-2.25/gas/config/tc-mmix.c \
../nachos_initialCode/tools/binutils-2.25/gas/config/tc-mn10200.c \
../nachos_initialCode/tools/binutils-2.25/gas/config/tc-mn10300.c \
../nachos_initialCode/tools/binutils-2.25/gas/config/tc-moxie.c \
../nachos_initialCode/tools/binutils-2.25/gas/config/tc-msp430.c \
../nachos_initialCode/tools/binutils-2.25/gas/config/tc-mt.c \
../nachos_initialCode/tools/binutils-2.25/gas/config/tc-nds32.c \
../nachos_initialCode/tools/binutils-2.25/gas/config/tc-nios2.c \
../nachos_initialCode/tools/binutils-2.25/gas/config/tc-ns32k.c \
../nachos_initialCode/tools/binutils-2.25/gas/config/tc-or1k.c \
../nachos_initialCode/tools/binutils-2.25/gas/config/tc-pdp11.c \
../nachos_initialCode/tools/binutils-2.25/gas/config/tc-pj.c \
../nachos_initialCode/tools/binutils-2.25/gas/config/tc-ppc.c \
../nachos_initialCode/tools/binutils-2.25/gas/config/tc-rl78.c \
../nachos_initialCode/tools/binutils-2.25/gas/config/tc-rx.c \
../nachos_initialCode/tools/binutils-2.25/gas/config/tc-s390.c \
../nachos_initialCode/tools/binutils-2.25/gas/config/tc-score.c \
../nachos_initialCode/tools/binutils-2.25/gas/config/tc-score7.c \
../nachos_initialCode/tools/binutils-2.25/gas/config/tc-sh.c \
../nachos_initialCode/tools/binutils-2.25/gas/config/tc-sh64.c \
../nachos_initialCode/tools/binutils-2.25/gas/config/tc-sparc.c \
../nachos_initialCode/tools/binutils-2.25/gas/config/tc-spu.c \
../nachos_initialCode/tools/binutils-2.25/gas/config/tc-tic30.c \
../nachos_initialCode/tools/binutils-2.25/gas/config/tc-tic4x.c \
../nachos_initialCode/tools/binutils-2.25/gas/config/tc-tic54x.c \
../nachos_initialCode/tools/binutils-2.25/gas/config/tc-tic6x.c \
../nachos_initialCode/tools/binutils-2.25/gas/config/tc-tilegx.c \
../nachos_initialCode/tools/binutils-2.25/gas/config/tc-tilepro.c \
../nachos_initialCode/tools/binutils-2.25/gas/config/tc-v850.c \
../nachos_initialCode/tools/binutils-2.25/gas/config/tc-vax.c \
../nachos_initialCode/tools/binutils-2.25/gas/config/tc-xc16x.c \
../nachos_initialCode/tools/binutils-2.25/gas/config/tc-xgate.c \
../nachos_initialCode/tools/binutils-2.25/gas/config/tc-xstormy16.c \
../nachos_initialCode/tools/binutils-2.25/gas/config/tc-xtensa.c \
../nachos_initialCode/tools/binutils-2.25/gas/config/tc-z80.c \
../nachos_initialCode/tools/binutils-2.25/gas/config/tc-z8k.c \
../nachos_initialCode/tools/binutils-2.25/gas/config/te-vms.c \
../nachos_initialCode/tools/binutils-2.25/gas/config/xtensa-relax.c 

OBJS += \
./nachos_initialCode/tools/binutils-2.25/gas/config/atof-ieee.o \
./nachos_initialCode/tools/binutils-2.25/gas/config/atof-vax.o \
./nachos_initialCode/tools/binutils-2.25/gas/config/bfin-lex-wrapper.o \
./nachos_initialCode/tools/binutils-2.25/gas/config/e-crisaout.o \
./nachos_initialCode/tools/binutils-2.25/gas/config/e-criself.o \
./nachos_initialCode/tools/binutils-2.25/gas/config/e-i386aout.o \
./nachos_initialCode/tools/binutils-2.25/gas/config/e-i386coff.o \
./nachos_initialCode/tools/binutils-2.25/gas/config/e-i386elf.o \
./nachos_initialCode/tools/binutils-2.25/gas/config/e-mipself.o \
./nachos_initialCode/tools/binutils-2.25/gas/config/obj-aout.o \
./nachos_initialCode/tools/binutils-2.25/gas/config/obj-coff-seh.o \
./nachos_initialCode/tools/binutils-2.25/gas/config/obj-coff.o \
./nachos_initialCode/tools/binutils-2.25/gas/config/obj-ecoff.o \
./nachos_initialCode/tools/binutils-2.25/gas/config/obj-elf.o \
./nachos_initialCode/tools/binutils-2.25/gas/config/obj-evax.o \
./nachos_initialCode/tools/binutils-2.25/gas/config/obj-fdpicelf.o \
./nachos_initialCode/tools/binutils-2.25/gas/config/obj-macho.o \
./nachos_initialCode/tools/binutils-2.25/gas/config/obj-multi.o \
./nachos_initialCode/tools/binutils-2.25/gas/config/obj-som.o \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-aarch64.o \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-alpha.o \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-arc.o \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-arm.o \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-avr.o \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-bfin.o \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-cr16.o \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-cris.o \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-crx.o \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-d10v.o \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-d30v.o \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-dlx.o \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-epiphany.o \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-fr30.o \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-frv.o \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-generic.o \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-h8300.o \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-hppa.o \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-i370.o \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-i386-intel.o \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-i386.o \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-i860.o \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-i960.o \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-ia64.o \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-ip2k.o \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-iq2000.o \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-lm32.o \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-m32c.o \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-m32r.o \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-m68hc11.o \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-m68k.o \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-mcore.o \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-mep.o \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-metag.o \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-microblaze.o \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-mips.o \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-mmix.o \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-mn10200.o \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-mn10300.o \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-moxie.o \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-msp430.o \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-mt.o \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-nds32.o \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-nios2.o \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-ns32k.o \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-or1k.o \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-pdp11.o \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-pj.o \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-ppc.o \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-rl78.o \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-rx.o \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-s390.o \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-score.o \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-score7.o \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-sh.o \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-sh64.o \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-sparc.o \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-spu.o \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-tic30.o \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-tic4x.o \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-tic54x.o \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-tic6x.o \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-tilegx.o \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-tilepro.o \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-v850.o \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-vax.o \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-xc16x.o \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-xgate.o \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-xstormy16.o \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-xtensa.o \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-z80.o \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-z8k.o \
./nachos_initialCode/tools/binutils-2.25/gas/config/te-vms.o \
./nachos_initialCode/tools/binutils-2.25/gas/config/xtensa-relax.o 

C_DEPS += \
./nachos_initialCode/tools/binutils-2.25/gas/config/atof-ieee.d \
./nachos_initialCode/tools/binutils-2.25/gas/config/atof-vax.d \
./nachos_initialCode/tools/binutils-2.25/gas/config/bfin-lex-wrapper.d \
./nachos_initialCode/tools/binutils-2.25/gas/config/e-crisaout.d \
./nachos_initialCode/tools/binutils-2.25/gas/config/e-criself.d \
./nachos_initialCode/tools/binutils-2.25/gas/config/e-i386aout.d \
./nachos_initialCode/tools/binutils-2.25/gas/config/e-i386coff.d \
./nachos_initialCode/tools/binutils-2.25/gas/config/e-i386elf.d \
./nachos_initialCode/tools/binutils-2.25/gas/config/e-mipself.d \
./nachos_initialCode/tools/binutils-2.25/gas/config/obj-aout.d \
./nachos_initialCode/tools/binutils-2.25/gas/config/obj-coff-seh.d \
./nachos_initialCode/tools/binutils-2.25/gas/config/obj-coff.d \
./nachos_initialCode/tools/binutils-2.25/gas/config/obj-ecoff.d \
./nachos_initialCode/tools/binutils-2.25/gas/config/obj-elf.d \
./nachos_initialCode/tools/binutils-2.25/gas/config/obj-evax.d \
./nachos_initialCode/tools/binutils-2.25/gas/config/obj-fdpicelf.d \
./nachos_initialCode/tools/binutils-2.25/gas/config/obj-macho.d \
./nachos_initialCode/tools/binutils-2.25/gas/config/obj-multi.d \
./nachos_initialCode/tools/binutils-2.25/gas/config/obj-som.d \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-aarch64.d \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-alpha.d \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-arc.d \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-arm.d \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-avr.d \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-bfin.d \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-cr16.d \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-cris.d \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-crx.d \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-d10v.d \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-d30v.d \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-dlx.d \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-epiphany.d \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-fr30.d \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-frv.d \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-generic.d \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-h8300.d \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-hppa.d \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-i370.d \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-i386-intel.d \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-i386.d \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-i860.d \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-i960.d \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-ia64.d \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-ip2k.d \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-iq2000.d \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-lm32.d \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-m32c.d \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-m32r.d \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-m68hc11.d \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-m68k.d \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-mcore.d \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-mep.d \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-metag.d \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-microblaze.d \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-mips.d \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-mmix.d \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-mn10200.d \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-mn10300.d \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-moxie.d \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-msp430.d \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-mt.d \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-nds32.d \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-nios2.d \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-ns32k.d \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-or1k.d \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-pdp11.d \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-pj.d \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-ppc.d \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-rl78.d \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-rx.d \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-s390.d \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-score.d \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-score7.d \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-sh.d \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-sh64.d \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-sparc.d \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-spu.d \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-tic30.d \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-tic4x.d \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-tic54x.d \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-tic6x.d \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-tilegx.d \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-tilepro.d \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-v850.d \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-vax.d \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-xc16x.d \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-xgate.d \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-xstormy16.d \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-xtensa.d \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-z80.d \
./nachos_initialCode/tools/binutils-2.25/gas/config/tc-z8k.d \
./nachos_initialCode/tools/binutils-2.25/gas/config/te-vms.d \
./nachos_initialCode/tools/binutils-2.25/gas/config/xtensa-relax.d 


# Each subdirectory must supply rules for building sources it contributes
nachos_initialCode/tools/binutils-2.25/gas/config/%.o: ../nachos_initialCode/tools/binutils-2.25/gas/config/%.c
	@echo 'Building file: $<'
	@echo 'Invoking: Cross GCC Compiler'
	gcc -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


