################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/acoshq.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/acosq.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/asinhq.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/asinq.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/atan2q.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/atanhq.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/atanq.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/cacoshq.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/cacosq.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/casinhq.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/casinq.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/catanhq.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/catanq.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/cbrtq.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/ccoshq.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/ceilq.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/cexpq.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/cimagq.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/clog10q.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/clogq.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/complex.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/conjq.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/copysignq.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/coshq.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/cosq.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/cosq_kernel.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/cprojq.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/crealq.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/csinhq.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/csinq.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/csqrtq.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/ctanhq.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/ctanq.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/erfq.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/expm1q.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/expq.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/fabsq.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/fdimq.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/finiteq.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/floorq.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/fmaq.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/fmaxq.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/fminq.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/fmodq.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/frexpq.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/hypotq.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/ilogbq.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/isinf_nsq.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/isinfq.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/isnanq.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/j0q.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/j1q.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/jnq.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/ldexpq.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/lgammaq.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/llrintq.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/llroundq.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/log10q.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/log1pq.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/log2q.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/logq.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/lrintq.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/lroundq.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/modfq.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/nanq.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/nearbyintq.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/nextafterq.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/powq.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/rem_pio2q.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/remainderq.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/remquoq.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/rintq.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/roundq.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/scalblnq.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/scalbnq.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/signbitq.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/sincos_table.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/sincosq.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/sincosq_kernel.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/sinhq.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/sinq.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/sinq_kernel.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/sqrtq.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/tanhq.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/tanq.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/tgammaq.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/truncq.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/x2y2m1q.c 

OBJS += \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/acoshq.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/acosq.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/asinhq.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/asinq.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/atan2q.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/atanhq.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/atanq.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/cacoshq.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/cacosq.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/casinhq.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/casinq.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/catanhq.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/catanq.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/cbrtq.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/ccoshq.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/ceilq.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/cexpq.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/cimagq.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/clog10q.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/clogq.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/complex.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/conjq.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/copysignq.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/coshq.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/cosq.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/cosq_kernel.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/cprojq.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/crealq.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/csinhq.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/csinq.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/csqrtq.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/ctanhq.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/ctanq.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/erfq.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/expm1q.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/expq.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/fabsq.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/fdimq.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/finiteq.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/floorq.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/fmaq.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/fmaxq.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/fminq.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/fmodq.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/frexpq.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/hypotq.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/ilogbq.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/isinf_nsq.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/isinfq.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/isnanq.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/j0q.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/j1q.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/jnq.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/ldexpq.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/lgammaq.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/llrintq.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/llroundq.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/log10q.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/log1pq.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/log2q.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/logq.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/lrintq.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/lroundq.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/modfq.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/nanq.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/nearbyintq.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/nextafterq.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/powq.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/rem_pio2q.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/remainderq.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/remquoq.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/rintq.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/roundq.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/scalblnq.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/scalbnq.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/signbitq.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/sincos_table.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/sincosq.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/sincosq_kernel.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/sinhq.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/sinq.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/sinq_kernel.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/sqrtq.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/tanhq.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/tanq.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/tgammaq.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/truncq.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/x2y2m1q.o 

C_DEPS += \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/acoshq.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/acosq.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/asinhq.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/asinq.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/atan2q.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/atanhq.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/atanq.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/cacoshq.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/cacosq.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/casinhq.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/casinq.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/catanhq.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/catanq.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/cbrtq.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/ccoshq.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/ceilq.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/cexpq.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/cimagq.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/clog10q.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/clogq.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/complex.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/conjq.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/copysignq.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/coshq.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/cosq.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/cosq_kernel.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/cprojq.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/crealq.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/csinhq.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/csinq.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/csqrtq.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/ctanhq.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/ctanq.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/erfq.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/expm1q.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/expq.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/fabsq.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/fdimq.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/finiteq.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/floorq.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/fmaq.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/fmaxq.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/fminq.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/fmodq.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/frexpq.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/hypotq.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/ilogbq.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/isinf_nsq.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/isinfq.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/isnanq.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/j0q.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/j1q.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/jnq.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/ldexpq.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/lgammaq.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/llrintq.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/llroundq.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/log10q.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/log1pq.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/log2q.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/logq.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/lrintq.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/lroundq.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/modfq.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/nanq.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/nearbyintq.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/nextafterq.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/powq.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/rem_pio2q.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/remainderq.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/remquoq.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/rintq.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/roundq.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/scalblnq.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/scalbnq.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/signbitq.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/sincos_table.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/sincosq.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/sincosq_kernel.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/sinhq.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/sinq.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/sinq_kernel.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/sqrtq.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/tanhq.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/tanq.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/tgammaq.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/truncq.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/x2y2m1q.d 


# Each subdirectory must supply rules for building sources it contributes
nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/%.o: ../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libquadmath/math/%.c
	@echo 'Building file: $<'
	@echo 'Invoking: Cross GCC Compiler'
	gcc -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


