################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_UPPER_SRCS += \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/affinity-1.C \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/atomic-1.C \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/atomic-10.C \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/atomic-11.C \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/atomic-12.C \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/atomic-13.C \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/atomic-14.C \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/atomic-15.C \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/atomic-2.C \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/atomic-3.C \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/atomic-4.C \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/atomic-5.C \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/atomic-6.C \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/atomic-7.C \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/atomic-8.C \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/atomic-9.C \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/cancel-for-1.C \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/cancel-for-2.C \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/cancel-parallel-1.C \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/cancel-parallel-2.C \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/cancel-parallel-3.C \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/cancel-sections-1.C \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/cancel-taskgroup-1.C \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/cancel-taskgroup-2.C \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/cancel-taskgroup-3.C \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/collapse-1.C \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/collapse-2.C \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/copyin-1.C \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/copyin-2.C \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/ctor-1.C \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/ctor-10.C \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/ctor-11.C \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/ctor-12.C \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/ctor-2.C \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/ctor-3.C \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/ctor-4.C \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/ctor-5.C \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/ctor-6.C \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/ctor-7.C \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/ctor-8.C \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/ctor-9.C \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/for-1.C \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/for-10.C \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/for-11.C \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/for-2.C \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/for-3.C \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/for-4.C \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/for-5.C \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/for-6.C \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/for-7.C \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/for-8.C \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/for-9.C \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/loop-1.C \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/loop-10.C \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/loop-11.C \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/loop-12.C \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/loop-13.C \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/loop-14.C \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/loop-15.C \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/loop-2.C \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/loop-3.C \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/loop-4.C \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/loop-5.C \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/loop-6.C \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/loop-7.C \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/loop-8.C \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/loop-9.C \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/master-1.C \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/nested-1.C \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/parallel-1.C \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/pr24455-1.C \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/pr24455.C \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/pr26691.C \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/pr26943.C \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/pr27337.C \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/pr30703.C \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/pr34513.C \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/pr35185.C \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/pr38650.C \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/pr39573.C \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/pr43893.C \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/pr48869.C \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/pr49043.C \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/pr56217.C \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/pr63248.C \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/reduction-1.C \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/reduction-2.C \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/reduction-3.C \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/reduction-4.C \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/sections-1.C \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/shared-1.C \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/shared-2.C \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/simd-1.C \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/simd-2.C \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/simd-3.C \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/simd-4.C \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/simd-5.C \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/simd-6.C \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/simd-7.C \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/simd-8.C \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/simd-9.C \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/simd10.C \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/simd11.C \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/simd12.C \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/simd13.C \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/single-1.C \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/single-2.C \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/single-3.C \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/target-1.C \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/target-2.C \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/target-3.C \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/task-1.C \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/task-2.C \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/task-3.C \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/task-4.C \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/task-5.C \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/task-6.C \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/task-7.C \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/task-8.C \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/taskgroup-1.C \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/tls-init1.C \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/udr-1.C \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/udr-11.C \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/udr-12.C \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/udr-13.C \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/udr-14.C \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/udr-15.C \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/udr-16.C \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/udr-17.C \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/udr-18.C \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/udr-19.C \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/udr-2.C \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/udr-3.C \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/udr-4.C \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/udr-5.C \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/udr-6.C \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/udr-7.C \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/udr-8.C \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/udr-9.C 

CC_SRCS += \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/target-2-aux.cc 

OBJS += \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/affinity-1.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/atomic-1.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/atomic-10.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/atomic-11.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/atomic-12.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/atomic-13.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/atomic-14.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/atomic-15.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/atomic-2.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/atomic-3.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/atomic-4.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/atomic-5.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/atomic-6.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/atomic-7.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/atomic-8.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/atomic-9.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/cancel-for-1.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/cancel-for-2.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/cancel-parallel-1.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/cancel-parallel-2.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/cancel-parallel-3.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/cancel-sections-1.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/cancel-taskgroup-1.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/cancel-taskgroup-2.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/cancel-taskgroup-3.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/collapse-1.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/collapse-2.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/copyin-1.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/copyin-2.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/ctor-1.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/ctor-10.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/ctor-11.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/ctor-12.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/ctor-2.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/ctor-3.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/ctor-4.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/ctor-5.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/ctor-6.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/ctor-7.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/ctor-8.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/ctor-9.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/for-1.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/for-10.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/for-11.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/for-2.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/for-3.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/for-4.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/for-5.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/for-6.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/for-7.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/for-8.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/for-9.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/loop-1.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/loop-10.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/loop-11.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/loop-12.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/loop-13.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/loop-14.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/loop-15.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/loop-2.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/loop-3.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/loop-4.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/loop-5.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/loop-6.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/loop-7.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/loop-8.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/loop-9.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/master-1.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/nested-1.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/parallel-1.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/pr24455-1.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/pr24455.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/pr26691.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/pr26943.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/pr27337.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/pr30703.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/pr34513.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/pr35185.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/pr38650.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/pr39573.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/pr43893.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/pr48869.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/pr49043.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/pr56217.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/pr63248.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/reduction-1.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/reduction-2.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/reduction-3.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/reduction-4.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/sections-1.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/shared-1.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/shared-2.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/simd-1.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/simd-2.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/simd-3.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/simd-4.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/simd-5.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/simd-6.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/simd-7.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/simd-8.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/simd-9.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/simd10.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/simd11.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/simd12.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/simd13.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/single-1.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/single-2.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/single-3.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/target-1.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/target-2-aux.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/target-2.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/target-3.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/task-1.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/task-2.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/task-3.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/task-4.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/task-5.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/task-6.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/task-7.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/task-8.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/taskgroup-1.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/tls-init1.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/udr-1.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/udr-11.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/udr-12.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/udr-13.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/udr-14.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/udr-15.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/udr-16.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/udr-17.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/udr-18.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/udr-19.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/udr-2.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/udr-3.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/udr-4.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/udr-5.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/udr-6.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/udr-7.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/udr-8.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/udr-9.o 

CC_DEPS += \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/target-2-aux.d 

C_UPPER_DEPS += \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/affinity-1.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/atomic-1.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/atomic-10.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/atomic-11.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/atomic-12.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/atomic-13.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/atomic-14.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/atomic-15.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/atomic-2.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/atomic-3.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/atomic-4.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/atomic-5.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/atomic-6.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/atomic-7.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/atomic-8.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/atomic-9.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/cancel-for-1.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/cancel-for-2.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/cancel-parallel-1.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/cancel-parallel-2.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/cancel-parallel-3.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/cancel-sections-1.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/cancel-taskgroup-1.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/cancel-taskgroup-2.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/cancel-taskgroup-3.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/collapse-1.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/collapse-2.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/copyin-1.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/copyin-2.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/ctor-1.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/ctor-10.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/ctor-11.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/ctor-12.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/ctor-2.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/ctor-3.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/ctor-4.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/ctor-5.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/ctor-6.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/ctor-7.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/ctor-8.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/ctor-9.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/for-1.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/for-10.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/for-11.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/for-2.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/for-3.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/for-4.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/for-5.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/for-6.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/for-7.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/for-8.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/for-9.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/loop-1.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/loop-10.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/loop-11.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/loop-12.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/loop-13.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/loop-14.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/loop-15.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/loop-2.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/loop-3.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/loop-4.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/loop-5.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/loop-6.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/loop-7.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/loop-8.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/loop-9.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/master-1.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/nested-1.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/parallel-1.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/pr24455-1.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/pr24455.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/pr26691.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/pr26943.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/pr27337.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/pr30703.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/pr34513.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/pr35185.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/pr38650.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/pr39573.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/pr43893.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/pr48869.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/pr49043.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/pr56217.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/pr63248.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/reduction-1.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/reduction-2.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/reduction-3.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/reduction-4.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/sections-1.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/shared-1.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/shared-2.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/simd-1.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/simd-2.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/simd-3.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/simd-4.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/simd-5.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/simd-6.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/simd-7.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/simd-8.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/simd-9.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/simd10.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/simd11.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/simd12.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/simd13.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/single-1.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/single-2.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/single-3.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/target-1.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/target-2.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/target-3.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/task-1.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/task-2.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/task-3.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/task-4.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/task-5.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/task-6.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/task-7.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/task-8.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/taskgroup-1.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/tls-init1.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/udr-1.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/udr-11.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/udr-12.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/udr-13.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/udr-14.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/udr-15.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/udr-16.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/udr-17.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/udr-18.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/udr-19.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/udr-2.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/udr-3.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/udr-4.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/udr-5.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/udr-6.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/udr-7.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/udr-8.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/udr-9.d 


# Each subdirectory must supply rules for building sources it contributes
nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/%.o: ../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/%.C
	@echo 'Building file: $<'
	@echo 'Invoking: Cross G++ Compiler'
	g++ -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/%.o: ../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgomp/testsuite/libgomp.c++/%.cc
	@echo 'Building file: $<'
	@echo 'Invoking: Cross G++ Compiler'
	g++ -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


