################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/call-by-value.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/cast.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/compare-eq-const.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/compare-eq-d128.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/compare-eq-d32.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/compare-eq-d64.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/compare-eq-dfp.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/compare-rel-const.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/compare-rel-d128.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/compare-rel-d32.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/compare-rel-d64.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/compare-rel-dfp.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/compare-special-d128.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/compare-special-d32.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/compare-special-d64.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/constants-zero.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/convert-bfp-10.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/convert-bfp-11.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/convert-bfp-12.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/convert-bfp-13.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/convert-bfp-14.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/convert-bfp-2.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/convert-bfp-3.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/convert-bfp-4.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/convert-bfp-5.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/convert-bfp-6.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/convert-bfp-7.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/convert-bfp-8.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/convert-bfp-9.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/convert-bfp-fold.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/convert-bfp.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/convert-dfp-fold-2.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/convert-dfp-fold.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/convert-dfp.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/convert-int-fold.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/convert-int-max-fold.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/convert-int-max.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/convert-int-saturate.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/convert-int.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/func-array.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/func-deref.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/func-mixed.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/func-pointer.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/func-scalar.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/func-struct.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/func-vararg-alternate-d128-2.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/func-vararg-alternate-d128.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/func-vararg-alternate-d32.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/func-vararg-alternate-d64.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/func-vararg-dfp.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/func-vararg-mixed-2.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/func-vararg-mixed.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/func-vararg-size0.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/inf-1.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/loop-index.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/modes.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/nan-1.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/nan-2.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/operator-arith-fold.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/operator-assignment.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/operator-comma.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/operator-cond.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/operator-logical.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/operator-unary.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/pr31385.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/pr33466.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/pr35620.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/pr36800.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/pr39034.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/pr39035.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/pr39902.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/pr39986.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/signbit-1.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/signbit-2.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/struct-layout-1.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/usual-arith-conv-const.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/usual-arith-conv.c 

OBJS += \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/call-by-value.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/cast.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/compare-eq-const.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/compare-eq-d128.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/compare-eq-d32.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/compare-eq-d64.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/compare-eq-dfp.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/compare-rel-const.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/compare-rel-d128.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/compare-rel-d32.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/compare-rel-d64.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/compare-rel-dfp.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/compare-special-d128.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/compare-special-d32.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/compare-special-d64.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/constants-zero.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/convert-bfp-10.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/convert-bfp-11.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/convert-bfp-12.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/convert-bfp-13.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/convert-bfp-14.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/convert-bfp-2.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/convert-bfp-3.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/convert-bfp-4.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/convert-bfp-5.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/convert-bfp-6.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/convert-bfp-7.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/convert-bfp-8.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/convert-bfp-9.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/convert-bfp-fold.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/convert-bfp.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/convert-dfp-fold-2.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/convert-dfp-fold.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/convert-dfp.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/convert-int-fold.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/convert-int-max-fold.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/convert-int-max.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/convert-int-saturate.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/convert-int.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/func-array.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/func-deref.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/func-mixed.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/func-pointer.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/func-scalar.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/func-struct.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/func-vararg-alternate-d128-2.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/func-vararg-alternate-d128.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/func-vararg-alternate-d32.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/func-vararg-alternate-d64.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/func-vararg-dfp.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/func-vararg-mixed-2.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/func-vararg-mixed.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/func-vararg-size0.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/inf-1.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/loop-index.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/modes.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/nan-1.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/nan-2.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/operator-arith-fold.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/operator-assignment.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/operator-comma.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/operator-cond.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/operator-logical.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/operator-unary.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/pr31385.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/pr33466.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/pr35620.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/pr36800.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/pr39034.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/pr39035.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/pr39902.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/pr39986.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/signbit-1.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/signbit-2.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/struct-layout-1.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/usual-arith-conv-const.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/usual-arith-conv.o 

C_DEPS += \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/call-by-value.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/cast.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/compare-eq-const.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/compare-eq-d128.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/compare-eq-d32.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/compare-eq-d64.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/compare-eq-dfp.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/compare-rel-const.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/compare-rel-d128.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/compare-rel-d32.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/compare-rel-d64.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/compare-rel-dfp.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/compare-special-d128.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/compare-special-d32.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/compare-special-d64.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/constants-zero.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/convert-bfp-10.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/convert-bfp-11.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/convert-bfp-12.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/convert-bfp-13.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/convert-bfp-14.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/convert-bfp-2.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/convert-bfp-3.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/convert-bfp-4.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/convert-bfp-5.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/convert-bfp-6.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/convert-bfp-7.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/convert-bfp-8.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/convert-bfp-9.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/convert-bfp-fold.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/convert-bfp.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/convert-dfp-fold-2.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/convert-dfp-fold.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/convert-dfp.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/convert-int-fold.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/convert-int-max-fold.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/convert-int-max.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/convert-int-saturate.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/convert-int.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/func-array.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/func-deref.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/func-mixed.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/func-pointer.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/func-scalar.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/func-struct.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/func-vararg-alternate-d128-2.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/func-vararg-alternate-d128.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/func-vararg-alternate-d32.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/func-vararg-alternate-d64.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/func-vararg-dfp.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/func-vararg-mixed-2.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/func-vararg-mixed.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/func-vararg-size0.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/inf-1.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/loop-index.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/modes.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/nan-1.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/nan-2.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/operator-arith-fold.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/operator-assignment.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/operator-comma.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/operator-cond.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/operator-logical.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/operator-unary.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/pr31385.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/pr33466.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/pr35620.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/pr36800.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/pr39034.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/pr39035.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/pr39902.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/pr39986.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/signbit-1.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/signbit-2.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/struct-layout-1.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/usual-arith-conv-const.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/usual-arith-conv.d 


# Each subdirectory must supply rules for building sources it contributes
nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/%.o: ../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/dfp/%.c
	@echo 'Building file: $<'
	@echo 'Invoking: Cross GCC Compiler'
	gcc -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


