################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/closure_fn0.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/closure_fn1.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/closure_fn2.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/closure_fn3.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/closure_fn4.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/closure_fn5.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/closure_fn6.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/closure_loc_fn0.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/closure_stdcall.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/closure_thiscall.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_12byte.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_16byte.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_18byte.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_19byte.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_1_1byte.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_20byte.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_20byte1.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_24byte.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_2byte.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_3_1byte.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_3byte1.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_3byte2.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_4_1byte.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_4byte.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_5_1_byte.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_5byte.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_64byte.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_6_1_byte.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_6byte.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_7_1_byte.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_7byte.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_8byte.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_9byte1.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_9byte2.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_align_double.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_align_float.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_align_longdouble.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_align_longdouble_split.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_align_longdouble_split2.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_align_pointer.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_align_sint16.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_align_sint32.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_align_sint64.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_align_uint16.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_align_uint32.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_align_uint64.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_dbls_struct.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_double.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_double_va.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_float.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_longdouble.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_longdouble_va.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_multi_schar.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_multi_sshort.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_multi_sshortchar.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_multi_uchar.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_multi_ushort.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_multi_ushortchar.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_pointer.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_pointer_stack.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_schar.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_sint.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_sshort.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_struct_va1.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_uchar.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_uchar_va.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_uint.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_uint_va.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_ulong_va.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_ulonglong.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_ushort.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_ushort_va.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/err_bad_abi.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/err_bad_typedef.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/fastthis1_win32.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/fastthis2_win32.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/fastthis3_win32.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/float.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/float1.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/float2.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/float3.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/float4.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/float_va.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/huge_struct.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/many.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/many2.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/many2_win32.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/many_win32.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/negint.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/nested_struct.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/nested_struct1.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/nested_struct10.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/nested_struct11.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/nested_struct2.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/nested_struct3.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/nested_struct4.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/nested_struct5.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/nested_struct6.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/nested_struct7.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/nested_struct8.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/nested_struct9.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/problem1.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/promotion.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/pyobjc-tc.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/return_dbl.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/return_dbl1.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/return_dbl2.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/return_fl.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/return_fl1.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/return_fl2.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/return_fl3.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/return_ldl.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/return_ll.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/return_ll1.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/return_sc.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/return_sl.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/return_uc.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/return_ul.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/stret_large.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/stret_large2.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/stret_medium.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/stret_medium2.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/strlen.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/strlen2_win32.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/strlen_win32.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/struct1.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/struct1_win32.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/struct2.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/struct2_win32.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/struct3.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/struct4.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/struct5.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/struct6.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/struct7.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/struct8.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/struct9.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/testclosure.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/uninitialized.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/va_1.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/va_struct1.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/va_struct2.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/va_struct3.c 

OBJS += \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/closure_fn0.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/closure_fn1.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/closure_fn2.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/closure_fn3.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/closure_fn4.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/closure_fn5.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/closure_fn6.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/closure_loc_fn0.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/closure_stdcall.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/closure_thiscall.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_12byte.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_16byte.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_18byte.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_19byte.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_1_1byte.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_20byte.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_20byte1.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_24byte.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_2byte.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_3_1byte.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_3byte1.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_3byte2.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_4_1byte.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_4byte.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_5_1_byte.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_5byte.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_64byte.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_6_1_byte.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_6byte.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_7_1_byte.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_7byte.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_8byte.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_9byte1.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_9byte2.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_align_double.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_align_float.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_align_longdouble.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_align_longdouble_split.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_align_longdouble_split2.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_align_pointer.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_align_sint16.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_align_sint32.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_align_sint64.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_align_uint16.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_align_uint32.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_align_uint64.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_dbls_struct.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_double.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_double_va.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_float.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_longdouble.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_longdouble_va.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_multi_schar.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_multi_sshort.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_multi_sshortchar.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_multi_uchar.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_multi_ushort.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_multi_ushortchar.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_pointer.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_pointer_stack.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_schar.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_sint.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_sshort.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_struct_va1.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_uchar.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_uchar_va.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_uint.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_uint_va.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_ulong_va.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_ulonglong.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_ushort.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_ushort_va.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/err_bad_abi.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/err_bad_typedef.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/fastthis1_win32.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/fastthis2_win32.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/fastthis3_win32.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/float.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/float1.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/float2.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/float3.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/float4.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/float_va.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/huge_struct.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/many.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/many2.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/many2_win32.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/many_win32.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/negint.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/nested_struct.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/nested_struct1.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/nested_struct10.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/nested_struct11.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/nested_struct2.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/nested_struct3.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/nested_struct4.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/nested_struct5.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/nested_struct6.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/nested_struct7.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/nested_struct8.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/nested_struct9.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/problem1.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/promotion.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/pyobjc-tc.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/return_dbl.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/return_dbl1.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/return_dbl2.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/return_fl.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/return_fl1.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/return_fl2.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/return_fl3.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/return_ldl.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/return_ll.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/return_ll1.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/return_sc.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/return_sl.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/return_uc.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/return_ul.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/stret_large.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/stret_large2.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/stret_medium.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/stret_medium2.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/strlen.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/strlen2_win32.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/strlen_win32.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/struct1.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/struct1_win32.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/struct2.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/struct2_win32.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/struct3.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/struct4.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/struct5.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/struct6.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/struct7.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/struct8.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/struct9.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/testclosure.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/uninitialized.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/va_1.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/va_struct1.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/va_struct2.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/va_struct3.o 

C_DEPS += \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/closure_fn0.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/closure_fn1.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/closure_fn2.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/closure_fn3.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/closure_fn4.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/closure_fn5.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/closure_fn6.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/closure_loc_fn0.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/closure_stdcall.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/closure_thiscall.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_12byte.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_16byte.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_18byte.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_19byte.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_1_1byte.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_20byte.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_20byte1.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_24byte.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_2byte.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_3_1byte.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_3byte1.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_3byte2.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_4_1byte.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_4byte.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_5_1_byte.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_5byte.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_64byte.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_6_1_byte.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_6byte.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_7_1_byte.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_7byte.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_8byte.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_9byte1.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_9byte2.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_align_double.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_align_float.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_align_longdouble.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_align_longdouble_split.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_align_longdouble_split2.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_align_pointer.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_align_sint16.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_align_sint32.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_align_sint64.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_align_uint16.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_align_uint32.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_align_uint64.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_dbls_struct.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_double.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_double_va.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_float.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_longdouble.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_longdouble_va.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_multi_schar.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_multi_sshort.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_multi_sshortchar.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_multi_uchar.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_multi_ushort.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_multi_ushortchar.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_pointer.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_pointer_stack.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_schar.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_sint.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_sshort.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_struct_va1.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_uchar.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_uchar_va.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_uint.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_uint_va.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_ulong_va.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_ulonglong.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_ushort.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/cls_ushort_va.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/err_bad_abi.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/err_bad_typedef.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/fastthis1_win32.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/fastthis2_win32.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/fastthis3_win32.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/float.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/float1.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/float2.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/float3.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/float4.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/float_va.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/huge_struct.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/many.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/many2.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/many2_win32.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/many_win32.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/negint.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/nested_struct.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/nested_struct1.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/nested_struct10.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/nested_struct11.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/nested_struct2.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/nested_struct3.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/nested_struct4.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/nested_struct5.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/nested_struct6.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/nested_struct7.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/nested_struct8.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/nested_struct9.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/problem1.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/promotion.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/pyobjc-tc.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/return_dbl.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/return_dbl1.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/return_dbl2.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/return_fl.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/return_fl1.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/return_fl2.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/return_fl3.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/return_ldl.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/return_ll.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/return_ll1.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/return_sc.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/return_sl.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/return_uc.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/return_ul.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/stret_large.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/stret_large2.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/stret_medium.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/stret_medium2.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/strlen.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/strlen2_win32.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/strlen_win32.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/struct1.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/struct1_win32.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/struct2.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/struct2_win32.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/struct3.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/struct4.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/struct5.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/struct6.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/struct7.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/struct8.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/struct9.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/testclosure.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/uninitialized.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/va_1.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/va_struct1.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/va_struct2.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/va_struct3.d 


# Each subdirectory must supply rules for building sources it contributes
nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/%.o: ../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libffi/testsuite/libffi.call/%.c
	@echo 'Building file: $<'
	@echo 'Invoking: Cross GCC Compiler'
	gcc -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


