################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
S_UPPER_SRCS += \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/excp_isr.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/excp_isr_4b.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/intr_isr.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/intr_isr_4b.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid00.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid01.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid02.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid03.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid04.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid05.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid06.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid07.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid08.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid09.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid10.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid11.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid12.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid13.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid14.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid15.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid16.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid17.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid18.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid19.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid20.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid21.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid22.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid23.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid24.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid25.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid26.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid27.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid28.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid29.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid30.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid31.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid32.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid33.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid34.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid35.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid36.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid37.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid38.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid39.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid40.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid41.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid42.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid43.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid44.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid45.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid46.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid47.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid48.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid49.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid50.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid51.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid52.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid53.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid54.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid55.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid56.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid57.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid58.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid59.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid60.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid61.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid62.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid63.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid64.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid65.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid66.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid67.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid68.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid69.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid70.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid71.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid72.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/nmih.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/reset.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/reset_4b.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid00.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid00_4b.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid01.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid01_4b.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid02.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid02_4b.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid03.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid03_4b.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid04.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid04_4b.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid05.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid05_4b.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid06.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid06_4b.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid07.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid07_4b.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid08.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid08_4b.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid09.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid09_4b.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid10.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid10_4b.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid11.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid11_4b.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid12.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid12_4b.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid13.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid13_4b.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid14.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid14_4b.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid15.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid15_4b.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid16.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid16_4b.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid17.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid17_4b.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid18.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid18_4b.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid19.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid19_4b.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid20.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid20_4b.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid21.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid21_4b.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid22.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid22_4b.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid23.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid23_4b.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid24.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid24_4b.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid25.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid25_4b.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid26.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid26_4b.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid27.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid27_4b.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid28.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid28_4b.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid29.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid29_4b.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid30.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid30_4b.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid31.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid31_4b.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid32.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid32_4b.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid33.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid33_4b.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid34.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid34_4b.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid35.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid35_4b.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid36.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid36_4b.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid37.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid37_4b.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid38.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid38_4b.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid39.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid39_4b.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid40.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid40_4b.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid41.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid41_4b.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid42.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid42_4b.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid43.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid43_4b.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid44.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid44_4b.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid45.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid45_4b.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid46.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid46_4b.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid47.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid47_4b.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid48.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid48_4b.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid49.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid49_4b.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid50.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid50_4b.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid51.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid51_4b.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid52.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid52_4b.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid53.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid53_4b.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid54.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid54_4b.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid55.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid55_4b.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid56.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid56_4b.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid57.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid57_4b.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid58.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid58_4b.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid59.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid59_4b.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid60.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid60_4b.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid61.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid61_4b.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid62.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid62_4b.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid63.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid63_4b.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid64.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid64_4b.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid65.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid65_4b.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid66.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid66_4b.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid67.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid67_4b.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid68.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid68_4b.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid69.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid69_4b.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid70.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid70_4b.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid71.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid71_4b.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid72.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid72_4b.S \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/wrh.S 

OBJS += \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/excp_isr.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/excp_isr_4b.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/intr_isr.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/intr_isr_4b.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid00.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid01.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid02.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid03.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid04.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid05.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid06.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid07.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid08.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid09.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid10.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid11.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid12.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid13.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid14.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid15.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid16.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid17.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid18.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid19.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid20.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid21.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid22.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid23.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid24.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid25.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid26.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid27.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid28.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid29.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid30.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid31.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid32.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid33.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid34.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid35.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid36.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid37.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid38.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid39.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid40.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid41.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid42.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid43.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid44.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid45.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid46.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid47.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid48.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid49.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid50.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid51.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid52.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid53.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid54.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid55.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid56.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid57.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid58.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid59.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid60.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid61.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid62.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid63.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid64.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid65.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid66.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid67.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid68.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid69.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid70.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid71.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/jmptbl_vid72.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/nmih.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/reset.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/reset_4b.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid00.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid00_4b.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid01.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid01_4b.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid02.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid02_4b.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid03.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid03_4b.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid04.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid04_4b.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid05.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid05_4b.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid06.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid06_4b.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid07.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid07_4b.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid08.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid08_4b.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid09.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid09_4b.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid10.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid10_4b.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid11.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid11_4b.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid12.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid12_4b.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid13.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid13_4b.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid14.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid14_4b.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid15.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid15_4b.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid16.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid16_4b.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid17.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid17_4b.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid18.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid18_4b.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid19.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid19_4b.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid20.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid20_4b.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid21.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid21_4b.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid22.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid22_4b.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid23.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid23_4b.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid24.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid24_4b.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid25.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid25_4b.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid26.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid26_4b.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid27.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid27_4b.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid28.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid28_4b.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid29.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid29_4b.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid30.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid30_4b.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid31.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid31_4b.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid32.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid32_4b.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid33.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid33_4b.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid34.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid34_4b.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid35.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid35_4b.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid36.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid36_4b.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid37.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid37_4b.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid38.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid38_4b.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid39.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid39_4b.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid40.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid40_4b.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid41.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid41_4b.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid42.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid42_4b.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid43.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid43_4b.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid44.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid44_4b.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid45.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid45_4b.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid46.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid46_4b.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid47.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid47_4b.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid48.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid48_4b.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid49.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid49_4b.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid50.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid50_4b.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid51.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid51_4b.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid52.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid52_4b.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid53.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid53_4b.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid54.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid54_4b.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid55.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid55_4b.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid56.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid56_4b.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid57.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid57_4b.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid58.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid58_4b.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid59.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid59_4b.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid60.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid60_4b.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid61.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid61_4b.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid62.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid62_4b.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid63.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid63_4b.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid64.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid64_4b.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid65.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid65_4b.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid66.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid66_4b.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid67.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid67_4b.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid68.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid68_4b.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid69.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid69_4b.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid70.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid70_4b.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid71.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid71_4b.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid72.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/vec_vid72_4b.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/wrh.o 


# Each subdirectory must supply rules for building sources it contributes
nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/%.o: ../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/nds32/isr-library/%.S
	@echo 'Building file: $<'
	@echo 'Invoking: Cross GCC Assembler'
	as  -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


