################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_addsub_dd.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_addsub_sd.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_addsub_td.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_dd_to_df.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_dd_to_di.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_dd_to_sd.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_dd_to_sf.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_dd_to_si.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_dd_to_td.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_dd_to_tf.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_dd_to_udi.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_dd_to_usi.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_dd_to_xf.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_df_to_dd.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_df_to_sd.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_df_to_td.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_di_to_dd.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_di_to_sd.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_di_to_td.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_div_dd.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_div_sd.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_div_td.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_eq_dd.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_eq_sd.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_eq_td.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_ge_dd.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_ge_sd.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_ge_td.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_gt_dd.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_gt_sd.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_gt_td.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_isinfd128.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_isinfd32.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_isinfd64.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_le_dd.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_le_sd.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_le_td.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_lt_dd.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_lt_sd.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_lt_td.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_mul_dd.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_mul_sd.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_mul_td.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_ne_dd.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_ne_sd.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_ne_td.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_sd_to_dd.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_sd_to_df.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_sd_to_di.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_sd_to_sf.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_sd_to_si.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_sd_to_td.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_sd_to_tf.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_sd_to_udi.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_sd_to_usi.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_sd_to_xf.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_sf_to_dd.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_sf_to_sd.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_sf_to_td.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_si_to_dd.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_si_to_sd.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_si_to_td.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_td_to_dd.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_td_to_df.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_td_to_di.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_td_to_sd.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_td_to_sf.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_td_to_si.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_td_to_tf.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_td_to_udi.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_td_to_usi.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_td_to_xf.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_tf_to_dd.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_tf_to_sd.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_tf_to_td.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_udi_to_dd.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_udi_to_sd.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_udi_to_td.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_unord_dd.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_unord_sd.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_unord_td.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_usi_to_dd.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_usi_to_sd.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_usi_to_td.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_xf_to_dd.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_xf_to_sd.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_xf_to_td.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid128.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid128_2_str_tables.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid128_add.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid128_compare.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid128_div.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid128_fma.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid128_logb.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid128_minmax.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid128_mul.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid128_next.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid128_noncomp.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid128_quantize.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid128_rem.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid128_round_integral.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid128_scalb.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid128_sqrt.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid128_string.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid128_to_int16.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid128_to_int32.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid128_to_int64.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid128_to_int8.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid128_to_uint16.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid128_to_uint32.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid128_to_uint64.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid128_to_uint8.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid32_to_bid128.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid32_to_bid64.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid64_add.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid64_compare.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid64_div.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid64_fma.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid64_logb.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid64_minmax.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid64_mul.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid64_next.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid64_noncomp.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid64_quantize.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid64_rem.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid64_round_integral.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid64_scalb.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid64_sqrt.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid64_string.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid64_to_bid128.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid64_to_int16.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid64_to_int32.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid64_to_int64.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid64_to_int8.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid64_to_uint16.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid64_to_uint32.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid64_to_uint64.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid64_to_uint8.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid_binarydecimal.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid_convert_data.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid_decimal_data.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid_decimal_globals.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid_dpd.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid_flag_operations.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid_from_int.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid_round.c 

OBJS += \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_addsub_dd.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_addsub_sd.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_addsub_td.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_dd_to_df.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_dd_to_di.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_dd_to_sd.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_dd_to_sf.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_dd_to_si.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_dd_to_td.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_dd_to_tf.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_dd_to_udi.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_dd_to_usi.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_dd_to_xf.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_df_to_dd.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_df_to_sd.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_df_to_td.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_di_to_dd.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_di_to_sd.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_di_to_td.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_div_dd.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_div_sd.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_div_td.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_eq_dd.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_eq_sd.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_eq_td.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_ge_dd.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_ge_sd.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_ge_td.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_gt_dd.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_gt_sd.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_gt_td.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_isinfd128.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_isinfd32.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_isinfd64.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_le_dd.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_le_sd.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_le_td.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_lt_dd.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_lt_sd.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_lt_td.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_mul_dd.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_mul_sd.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_mul_td.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_ne_dd.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_ne_sd.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_ne_td.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_sd_to_dd.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_sd_to_df.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_sd_to_di.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_sd_to_sf.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_sd_to_si.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_sd_to_td.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_sd_to_tf.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_sd_to_udi.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_sd_to_usi.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_sd_to_xf.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_sf_to_dd.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_sf_to_sd.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_sf_to_td.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_si_to_dd.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_si_to_sd.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_si_to_td.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_td_to_dd.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_td_to_df.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_td_to_di.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_td_to_sd.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_td_to_sf.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_td_to_si.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_td_to_tf.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_td_to_udi.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_td_to_usi.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_td_to_xf.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_tf_to_dd.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_tf_to_sd.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_tf_to_td.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_udi_to_dd.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_udi_to_sd.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_udi_to_td.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_unord_dd.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_unord_sd.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_unord_td.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_usi_to_dd.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_usi_to_sd.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_usi_to_td.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_xf_to_dd.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_xf_to_sd.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_xf_to_td.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid128.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid128_2_str_tables.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid128_add.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid128_compare.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid128_div.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid128_fma.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid128_logb.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid128_minmax.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid128_mul.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid128_next.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid128_noncomp.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid128_quantize.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid128_rem.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid128_round_integral.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid128_scalb.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid128_sqrt.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid128_string.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid128_to_int16.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid128_to_int32.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid128_to_int64.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid128_to_int8.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid128_to_uint16.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid128_to_uint32.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid128_to_uint64.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid128_to_uint8.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid32_to_bid128.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid32_to_bid64.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid64_add.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid64_compare.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid64_div.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid64_fma.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid64_logb.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid64_minmax.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid64_mul.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid64_next.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid64_noncomp.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid64_quantize.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid64_rem.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid64_round_integral.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid64_scalb.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid64_sqrt.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid64_string.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid64_to_bid128.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid64_to_int16.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid64_to_int32.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid64_to_int64.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid64_to_int8.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid64_to_uint16.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid64_to_uint32.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid64_to_uint64.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid64_to_uint8.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid_binarydecimal.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid_convert_data.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid_decimal_data.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid_decimal_globals.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid_dpd.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid_flag_operations.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid_from_int.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid_round.o 

C_DEPS += \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_addsub_dd.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_addsub_sd.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_addsub_td.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_dd_to_df.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_dd_to_di.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_dd_to_sd.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_dd_to_sf.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_dd_to_si.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_dd_to_td.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_dd_to_tf.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_dd_to_udi.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_dd_to_usi.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_dd_to_xf.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_df_to_dd.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_df_to_sd.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_df_to_td.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_di_to_dd.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_di_to_sd.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_di_to_td.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_div_dd.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_div_sd.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_div_td.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_eq_dd.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_eq_sd.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_eq_td.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_ge_dd.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_ge_sd.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_ge_td.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_gt_dd.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_gt_sd.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_gt_td.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_isinfd128.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_isinfd32.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_isinfd64.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_le_dd.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_le_sd.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_le_td.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_lt_dd.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_lt_sd.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_lt_td.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_mul_dd.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_mul_sd.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_mul_td.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_ne_dd.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_ne_sd.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_ne_td.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_sd_to_dd.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_sd_to_df.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_sd_to_di.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_sd_to_sf.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_sd_to_si.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_sd_to_td.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_sd_to_tf.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_sd_to_udi.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_sd_to_usi.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_sd_to_xf.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_sf_to_dd.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_sf_to_sd.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_sf_to_td.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_si_to_dd.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_si_to_sd.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_si_to_td.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_td_to_dd.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_td_to_df.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_td_to_di.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_td_to_sd.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_td_to_sf.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_td_to_si.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_td_to_tf.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_td_to_udi.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_td_to_usi.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_td_to_xf.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_tf_to_dd.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_tf_to_sd.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_tf_to_td.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_udi_to_dd.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_udi_to_sd.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_udi_to_td.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_unord_dd.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_unord_sd.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_unord_td.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_usi_to_dd.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_usi_to_sd.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_usi_to_td.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_xf_to_dd.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_xf_to_sd.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/_xf_to_td.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid128.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid128_2_str_tables.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid128_add.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid128_compare.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid128_div.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid128_fma.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid128_logb.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid128_minmax.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid128_mul.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid128_next.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid128_noncomp.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid128_quantize.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid128_rem.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid128_round_integral.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid128_scalb.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid128_sqrt.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid128_string.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid128_to_int16.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid128_to_int32.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid128_to_int64.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid128_to_int8.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid128_to_uint16.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid128_to_uint32.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid128_to_uint64.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid128_to_uint8.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid32_to_bid128.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid32_to_bid64.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid64_add.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid64_compare.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid64_div.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid64_fma.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid64_logb.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid64_minmax.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid64_mul.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid64_next.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid64_noncomp.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid64_quantize.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid64_rem.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid64_round_integral.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid64_scalb.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid64_sqrt.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid64_string.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid64_to_bid128.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid64_to_int16.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid64_to_int32.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid64_to_int64.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid64_to_int8.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid64_to_uint16.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid64_to_uint32.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid64_to_uint64.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid64_to_uint8.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid_binarydecimal.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid_convert_data.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid_decimal_data.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid_decimal_globals.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid_dpd.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid_flag_operations.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid_from_int.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/bid_round.d 


# Each subdirectory must supply rules for building sources it contributes
nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/%.o: ../nachos_initialCode/tools/gcc-4.9-4.9.2/src/libgcc/config/libbid/%.c
	@echo 'Building file: $<'
	@echo 'Invoking: Cross GCC Compiler'
	gcc -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


