################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
O_SRCS += \
../nachos_initialCode/code/build-origin/filesys-addrspace.o \
../nachos_initialCode/code/build-origin/filesys-bitmap.o \
../nachos_initialCode/code/build-origin/filesys-console.o \
../nachos_initialCode/code/build-origin/filesys-directory.o \
../nachos_initialCode/code/build-origin/filesys-disk.o \
../nachos_initialCode/code/build-origin/filesys-exception.o \
../nachos_initialCode/code/build-origin/filesys-filehdr.o \
../nachos_initialCode/code/build-origin/filesys-filesys.o \
../nachos_initialCode/code/build-origin/filesys-fstest.o \
../nachos_initialCode/code/build-origin/filesys-interrupt.o \
../nachos_initialCode/code/build-origin/filesys-list.o \
../nachos_initialCode/code/build-origin/filesys-machine.o \
../nachos_initialCode/code/build-origin/filesys-main.o \
../nachos_initialCode/code/build-origin/filesys-mipssim.o \
../nachos_initialCode/code/build-origin/filesys-openfile.o \
../nachos_initialCode/code/build-origin/filesys-progtest.o \
../nachos_initialCode/code/build-origin/filesys-scheduler.o \
../nachos_initialCode/code/build-origin/filesys-stats.o \
../nachos_initialCode/code/build-origin/filesys-switch.o \
../nachos_initialCode/code/build-origin/filesys-synch.o \
../nachos_initialCode/code/build-origin/filesys-synchdisk.o \
../nachos_initialCode/code/build-origin/filesys-synchlist.o \
../nachos_initialCode/code/build-origin/filesys-sysdep.o \
../nachos_initialCode/code/build-origin/filesys-system.o \
../nachos_initialCode/code/build-origin/filesys-thread.o \
../nachos_initialCode/code/build-origin/filesys-threadtest.o \
../nachos_initialCode/code/build-origin/filesys-timer.o \
../nachos_initialCode/code/build-origin/filesys-translate.o \
../nachos_initialCode/code/build-origin/filesys-utility.o \
../nachos_initialCode/code/build-origin/halt.o \
../nachos_initialCode/code/build-origin/matmult.o \
../nachos_initialCode/code/build-origin/network-addrspace.o \
../nachos_initialCode/code/build-origin/network-bitmap.o \
../nachos_initialCode/code/build-origin/network-console.o \
../nachos_initialCode/code/build-origin/network-directory.o \
../nachos_initialCode/code/build-origin/network-disk.o \
../nachos_initialCode/code/build-origin/network-exception.o \
../nachos_initialCode/code/build-origin/network-filehdr.o \
../nachos_initialCode/code/build-origin/network-filesys.o \
../nachos_initialCode/code/build-origin/network-fstest.o \
../nachos_initialCode/code/build-origin/network-interrupt.o \
../nachos_initialCode/code/build-origin/network-list.o \
../nachos_initialCode/code/build-origin/network-machine.o \
../nachos_initialCode/code/build-origin/network-main.o \
../nachos_initialCode/code/build-origin/network-mipssim.o \
../nachos_initialCode/code/build-origin/network-nettest.o \
../nachos_initialCode/code/build-origin/network-network.o \
../nachos_initialCode/code/build-origin/network-openfile.o \
../nachos_initialCode/code/build-origin/network-post.o \
../nachos_initialCode/code/build-origin/network-progtest.o \
../nachos_initialCode/code/build-origin/network-scheduler.o \
../nachos_initialCode/code/build-origin/network-stats.o \
../nachos_initialCode/code/build-origin/network-switch.o \
../nachos_initialCode/code/build-origin/network-synch.o \
../nachos_initialCode/code/build-origin/network-synchdisk.o \
../nachos_initialCode/code/build-origin/network-synchlist.o \
../nachos_initialCode/code/build-origin/network-sysdep.o \
../nachos_initialCode/code/build-origin/network-system.o \
../nachos_initialCode/code/build-origin/network-thread.o \
../nachos_initialCode/code/build-origin/network-threadtest.o \
../nachos_initialCode/code/build-origin/network-timer.o \
../nachos_initialCode/code/build-origin/network-translate.o \
../nachos_initialCode/code/build-origin/network-utility.o \
../nachos_initialCode/code/build-origin/shell.o \
../nachos_initialCode/code/build-origin/sort.o \
../nachos_initialCode/code/build-origin/start.o \
../nachos_initialCode/code/build-origin/threads-interrupt.o \
../nachos_initialCode/code/build-origin/threads-list.o \
../nachos_initialCode/code/build-origin/threads-main.o \
../nachos_initialCode/code/build-origin/threads-scheduler.o \
../nachos_initialCode/code/build-origin/threads-stats.o \
../nachos_initialCode/code/build-origin/threads-switch.o \
../nachos_initialCode/code/build-origin/threads-synch.o \
../nachos_initialCode/code/build-origin/threads-synchlist.o \
../nachos_initialCode/code/build-origin/threads-sysdep.o \
../nachos_initialCode/code/build-origin/threads-system.o \
../nachos_initialCode/code/build-origin/threads-thread.o \
../nachos_initialCode/code/build-origin/threads-threadtest.o \
../nachos_initialCode/code/build-origin/threads-timer.o \
../nachos_initialCode/code/build-origin/threads-utility.o \
../nachos_initialCode/code/build-origin/userprog-addrspace.o \
../nachos_initialCode/code/build-origin/userprog-bitmap.o \
../nachos_initialCode/code/build-origin/userprog-console.o \
../nachos_initialCode/code/build-origin/userprog-exception.o \
../nachos_initialCode/code/build-origin/userprog-interrupt.o \
../nachos_initialCode/code/build-origin/userprog-list.o \
../nachos_initialCode/code/build-origin/userprog-machine.o \
../nachos_initialCode/code/build-origin/userprog-main.o \
../nachos_initialCode/code/build-origin/userprog-mipssim.o \
../nachos_initialCode/code/build-origin/userprog-progtest.o \
../nachos_initialCode/code/build-origin/userprog-scheduler.o \
../nachos_initialCode/code/build-origin/userprog-stats.o \
../nachos_initialCode/code/build-origin/userprog-switch.o \
../nachos_initialCode/code/build-origin/userprog-synch.o \
../nachos_initialCode/code/build-origin/userprog-synchlist.o \
../nachos_initialCode/code/build-origin/userprog-sysdep.o \
../nachos_initialCode/code/build-origin/userprog-system.o \
../nachos_initialCode/code/build-origin/userprog-thread.o \
../nachos_initialCode/code/build-origin/userprog-threadtest.o \
../nachos_initialCode/code/build-origin/userprog-timer.o \
../nachos_initialCode/code/build-origin/userprog-translate.o \
../nachos_initialCode/code/build-origin/userprog-utility.o \
../nachos_initialCode/code/build-origin/vm-addrspace.o \
../nachos_initialCode/code/build-origin/vm-bitmap.o \
../nachos_initialCode/code/build-origin/vm-console.o \
../nachos_initialCode/code/build-origin/vm-exception.o \
../nachos_initialCode/code/build-origin/vm-interrupt.o \
../nachos_initialCode/code/build-origin/vm-list.o \
../nachos_initialCode/code/build-origin/vm-machine.o \
../nachos_initialCode/code/build-origin/vm-main.o \
../nachos_initialCode/code/build-origin/vm-mipssim.o \
../nachos_initialCode/code/build-origin/vm-progtest.o \
../nachos_initialCode/code/build-origin/vm-scheduler.o \
../nachos_initialCode/code/build-origin/vm-stats.o \
../nachos_initialCode/code/build-origin/vm-switch.o \
../nachos_initialCode/code/build-origin/vm-synch.o \
../nachos_initialCode/code/build-origin/vm-synchlist.o \
../nachos_initialCode/code/build-origin/vm-sysdep.o \
../nachos_initialCode/code/build-origin/vm-system.o \
../nachos_initialCode/code/build-origin/vm-thread.o \
../nachos_initialCode/code/build-origin/vm-threadtest.o \
../nachos_initialCode/code/build-origin/vm-timer.o \
../nachos_initialCode/code/build-origin/vm-translate.o \
../nachos_initialCode/code/build-origin/vm-utility.o 


# Each subdirectory must supply rules for building sources it contributes

