################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../nachos_initialCode/tools/binutils-2.25/opcodes/aarch64-asm-2.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/aarch64-asm.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/aarch64-dis-2.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/aarch64-dis.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/aarch64-gen.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/aarch64-opc-2.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/aarch64-opc.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/alpha-dis.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/alpha-opc.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/arc-dis.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/arc-ext.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/arc-opc.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/arm-dis.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/avr-dis.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/bfin-dis.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/cgen-asm.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/cgen-bitset.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/cgen-dis.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/cgen-opc.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/cr16-dis.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/cr16-opc.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/cris-dis.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/cris-opc.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/crx-dis.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/crx-opc.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/d10v-dis.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/d10v-opc.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/d30v-dis.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/d30v-opc.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/dis-buf.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/dis-init.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/disassemble.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/dlx-dis.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/epiphany-asm.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/epiphany-desc.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/epiphany-dis.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/epiphany-ibld.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/epiphany-opc.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/fr30-asm.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/fr30-desc.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/fr30-dis.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/fr30-ibld.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/fr30-opc.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/frv-asm.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/frv-desc.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/frv-dis.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/frv-ibld.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/frv-opc.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/h8300-dis.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/h8500-dis.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/hppa-dis.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/i370-dis.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/i370-opc.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/i386-dis.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/i386-gen.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/i386-opc.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/i860-dis.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/i960-dis.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/ia64-asmtab.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/ia64-dis.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/ia64-gen.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/ia64-opc-a.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/ia64-opc-b.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/ia64-opc-d.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/ia64-opc-f.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/ia64-opc-i.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/ia64-opc-m.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/ia64-opc-x.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/ia64-opc.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/ip2k-asm.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/ip2k-desc.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/ip2k-dis.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/ip2k-ibld.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/ip2k-opc.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/iq2000-asm.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/iq2000-desc.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/iq2000-dis.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/iq2000-ibld.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/iq2000-opc.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/lm32-asm.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/lm32-desc.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/lm32-dis.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/lm32-ibld.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/lm32-opc.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/lm32-opinst.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/m10200-dis.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/m10200-opc.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/m10300-dis.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/m10300-opc.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/m32c-asm.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/m32c-desc.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/m32c-dis.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/m32c-ibld.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/m32c-opc.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/m32r-asm.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/m32r-desc.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/m32r-dis.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/m32r-ibld.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/m32r-opc.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/m32r-opinst.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/m68hc11-dis.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/m68hc11-opc.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/m68k-dis.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/m68k-opc.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/m88k-dis.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/mcore-dis.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/mep-asm.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/mep-desc.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/mep-dis.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/mep-ibld.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/mep-opc.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/metag-dis.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/microblaze-dis.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/micromips-opc.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/mips-dis.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/mips-opc.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/mips16-opc.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/mmix-dis.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/mmix-opc.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/moxie-dis.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/moxie-opc.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/msp430-decode.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/msp430-dis.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/mt-asm.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/mt-desc.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/mt-dis.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/mt-ibld.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/mt-opc.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/nds32-asm.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/nds32-dis.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/nios2-dis.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/nios2-opc.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/ns32k-dis.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/opc2c.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/or1k-asm.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/or1k-desc.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/or1k-dis.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/or1k-ibld.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/or1k-opc.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/or1k-opinst.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/pdp11-dis.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/pdp11-opc.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/pj-dis.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/pj-opc.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/ppc-dis.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/ppc-opc.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/rl78-decode.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/rl78-dis.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/rx-decode.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/rx-dis.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/s390-dis.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/s390-mkopc.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/s390-opc.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/score-dis.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/score7-dis.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/sh-dis.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/sh64-dis.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/sh64-opc.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/sparc-dis.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/sparc-opc.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/spu-dis.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/spu-opc.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/tic30-dis.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/tic4x-dis.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/tic54x-dis.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/tic54x-opc.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/tic6x-dis.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/tic80-dis.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/tic80-opc.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/tilegx-dis.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/tilegx-opc.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/tilepro-dis.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/tilepro-opc.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/v850-dis.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/v850-opc.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/vax-dis.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/w65-dis.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/xc16x-asm.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/xc16x-desc.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/xc16x-dis.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/xc16x-ibld.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/xc16x-opc.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/xgate-dis.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/xgate-opc.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/xstormy16-asm.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/xstormy16-desc.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/xstormy16-dis.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/xstormy16-ibld.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/xstormy16-opc.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/xtensa-dis.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/z80-dis.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/z8k-dis.c \
../nachos_initialCode/tools/binutils-2.25/opcodes/z8kgen.c 

OBJS += \
./nachos_initialCode/tools/binutils-2.25/opcodes/aarch64-asm-2.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/aarch64-asm.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/aarch64-dis-2.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/aarch64-dis.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/aarch64-gen.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/aarch64-opc-2.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/aarch64-opc.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/alpha-dis.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/alpha-opc.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/arc-dis.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/arc-ext.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/arc-opc.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/arm-dis.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/avr-dis.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/bfin-dis.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/cgen-asm.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/cgen-bitset.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/cgen-dis.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/cgen-opc.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/cr16-dis.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/cr16-opc.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/cris-dis.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/cris-opc.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/crx-dis.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/crx-opc.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/d10v-dis.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/d10v-opc.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/d30v-dis.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/d30v-opc.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/dis-buf.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/dis-init.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/disassemble.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/dlx-dis.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/epiphany-asm.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/epiphany-desc.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/epiphany-dis.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/epiphany-ibld.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/epiphany-opc.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/fr30-asm.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/fr30-desc.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/fr30-dis.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/fr30-ibld.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/fr30-opc.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/frv-asm.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/frv-desc.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/frv-dis.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/frv-ibld.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/frv-opc.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/h8300-dis.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/h8500-dis.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/hppa-dis.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/i370-dis.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/i370-opc.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/i386-dis.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/i386-gen.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/i386-opc.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/i860-dis.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/i960-dis.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/ia64-asmtab.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/ia64-dis.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/ia64-gen.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/ia64-opc-a.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/ia64-opc-b.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/ia64-opc-d.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/ia64-opc-f.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/ia64-opc-i.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/ia64-opc-m.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/ia64-opc-x.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/ia64-opc.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/ip2k-asm.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/ip2k-desc.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/ip2k-dis.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/ip2k-ibld.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/ip2k-opc.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/iq2000-asm.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/iq2000-desc.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/iq2000-dis.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/iq2000-ibld.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/iq2000-opc.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/lm32-asm.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/lm32-desc.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/lm32-dis.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/lm32-ibld.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/lm32-opc.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/lm32-opinst.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/m10200-dis.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/m10200-opc.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/m10300-dis.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/m10300-opc.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/m32c-asm.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/m32c-desc.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/m32c-dis.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/m32c-ibld.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/m32c-opc.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/m32r-asm.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/m32r-desc.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/m32r-dis.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/m32r-ibld.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/m32r-opc.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/m32r-opinst.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/m68hc11-dis.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/m68hc11-opc.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/m68k-dis.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/m68k-opc.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/m88k-dis.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/mcore-dis.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/mep-asm.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/mep-desc.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/mep-dis.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/mep-ibld.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/mep-opc.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/metag-dis.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/microblaze-dis.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/micromips-opc.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/mips-dis.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/mips-opc.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/mips16-opc.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/mmix-dis.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/mmix-opc.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/moxie-dis.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/moxie-opc.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/msp430-decode.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/msp430-dis.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/mt-asm.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/mt-desc.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/mt-dis.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/mt-ibld.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/mt-opc.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/nds32-asm.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/nds32-dis.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/nios2-dis.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/nios2-opc.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/ns32k-dis.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/opc2c.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/or1k-asm.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/or1k-desc.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/or1k-dis.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/or1k-ibld.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/or1k-opc.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/or1k-opinst.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/pdp11-dis.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/pdp11-opc.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/pj-dis.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/pj-opc.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/ppc-dis.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/ppc-opc.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/rl78-decode.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/rl78-dis.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/rx-decode.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/rx-dis.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/s390-dis.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/s390-mkopc.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/s390-opc.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/score-dis.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/score7-dis.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/sh-dis.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/sh64-dis.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/sh64-opc.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/sparc-dis.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/sparc-opc.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/spu-dis.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/spu-opc.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/tic30-dis.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/tic4x-dis.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/tic54x-dis.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/tic54x-opc.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/tic6x-dis.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/tic80-dis.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/tic80-opc.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/tilegx-dis.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/tilegx-opc.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/tilepro-dis.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/tilepro-opc.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/v850-dis.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/v850-opc.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/vax-dis.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/w65-dis.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/xc16x-asm.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/xc16x-desc.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/xc16x-dis.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/xc16x-ibld.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/xc16x-opc.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/xgate-dis.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/xgate-opc.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/xstormy16-asm.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/xstormy16-desc.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/xstormy16-dis.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/xstormy16-ibld.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/xstormy16-opc.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/xtensa-dis.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/z80-dis.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/z8k-dis.o \
./nachos_initialCode/tools/binutils-2.25/opcodes/z8kgen.o 

C_DEPS += \
./nachos_initialCode/tools/binutils-2.25/opcodes/aarch64-asm-2.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/aarch64-asm.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/aarch64-dis-2.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/aarch64-dis.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/aarch64-gen.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/aarch64-opc-2.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/aarch64-opc.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/alpha-dis.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/alpha-opc.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/arc-dis.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/arc-ext.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/arc-opc.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/arm-dis.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/avr-dis.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/bfin-dis.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/cgen-asm.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/cgen-bitset.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/cgen-dis.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/cgen-opc.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/cr16-dis.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/cr16-opc.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/cris-dis.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/cris-opc.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/crx-dis.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/crx-opc.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/d10v-dis.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/d10v-opc.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/d30v-dis.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/d30v-opc.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/dis-buf.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/dis-init.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/disassemble.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/dlx-dis.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/epiphany-asm.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/epiphany-desc.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/epiphany-dis.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/epiphany-ibld.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/epiphany-opc.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/fr30-asm.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/fr30-desc.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/fr30-dis.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/fr30-ibld.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/fr30-opc.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/frv-asm.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/frv-desc.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/frv-dis.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/frv-ibld.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/frv-opc.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/h8300-dis.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/h8500-dis.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/hppa-dis.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/i370-dis.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/i370-opc.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/i386-dis.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/i386-gen.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/i386-opc.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/i860-dis.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/i960-dis.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/ia64-asmtab.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/ia64-dis.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/ia64-gen.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/ia64-opc-a.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/ia64-opc-b.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/ia64-opc-d.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/ia64-opc-f.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/ia64-opc-i.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/ia64-opc-m.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/ia64-opc-x.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/ia64-opc.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/ip2k-asm.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/ip2k-desc.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/ip2k-dis.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/ip2k-ibld.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/ip2k-opc.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/iq2000-asm.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/iq2000-desc.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/iq2000-dis.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/iq2000-ibld.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/iq2000-opc.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/lm32-asm.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/lm32-desc.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/lm32-dis.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/lm32-ibld.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/lm32-opc.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/lm32-opinst.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/m10200-dis.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/m10200-opc.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/m10300-dis.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/m10300-opc.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/m32c-asm.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/m32c-desc.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/m32c-dis.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/m32c-ibld.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/m32c-opc.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/m32r-asm.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/m32r-desc.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/m32r-dis.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/m32r-ibld.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/m32r-opc.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/m32r-opinst.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/m68hc11-dis.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/m68hc11-opc.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/m68k-dis.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/m68k-opc.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/m88k-dis.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/mcore-dis.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/mep-asm.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/mep-desc.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/mep-dis.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/mep-ibld.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/mep-opc.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/metag-dis.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/microblaze-dis.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/micromips-opc.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/mips-dis.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/mips-opc.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/mips16-opc.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/mmix-dis.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/mmix-opc.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/moxie-dis.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/moxie-opc.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/msp430-decode.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/msp430-dis.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/mt-asm.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/mt-desc.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/mt-dis.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/mt-ibld.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/mt-opc.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/nds32-asm.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/nds32-dis.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/nios2-dis.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/nios2-opc.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/ns32k-dis.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/opc2c.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/or1k-asm.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/or1k-desc.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/or1k-dis.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/or1k-ibld.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/or1k-opc.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/or1k-opinst.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/pdp11-dis.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/pdp11-opc.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/pj-dis.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/pj-opc.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/ppc-dis.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/ppc-opc.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/rl78-decode.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/rl78-dis.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/rx-decode.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/rx-dis.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/s390-dis.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/s390-mkopc.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/s390-opc.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/score-dis.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/score7-dis.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/sh-dis.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/sh64-dis.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/sh64-opc.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/sparc-dis.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/sparc-opc.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/spu-dis.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/spu-opc.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/tic30-dis.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/tic4x-dis.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/tic54x-dis.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/tic54x-opc.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/tic6x-dis.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/tic80-dis.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/tic80-opc.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/tilegx-dis.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/tilegx-opc.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/tilepro-dis.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/tilepro-opc.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/v850-dis.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/v850-opc.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/vax-dis.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/w65-dis.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/xc16x-asm.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/xc16x-desc.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/xc16x-dis.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/xc16x-ibld.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/xc16x-opc.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/xgate-dis.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/xgate-opc.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/xstormy16-asm.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/xstormy16-desc.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/xstormy16-dis.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/xstormy16-ibld.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/xstormy16-opc.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/xtensa-dis.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/z80-dis.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/z8k-dis.d \
./nachos_initialCode/tools/binutils-2.25/opcodes/z8kgen.d 


# Each subdirectory must supply rules for building sources it contributes
nachos_initialCode/tools/binutils-2.25/opcodes/%.o: ../nachos_initialCode/tools/binutils-2.25/opcodes/%.c
	@echo 'Building file: $<'
	@echo 'Invoking: Cross GCC Compiler'
	gcc -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


