################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../nachos_initialCode/tools/binutils-2.25/bfd/aix386-core.c \
../nachos_initialCode/tools/binutils-2.25/bfd/aix5ppc-core.c \
../nachos_initialCode/tools/binutils-2.25/bfd/aout-adobe.c \
../nachos_initialCode/tools/binutils-2.25/bfd/aout-arm.c \
../nachos_initialCode/tools/binutils-2.25/bfd/aout-cris.c \
../nachos_initialCode/tools/binutils-2.25/bfd/aout-ns32k.c \
../nachos_initialCode/tools/binutils-2.25/bfd/aout-sparcle.c \
../nachos_initialCode/tools/binutils-2.25/bfd/aout-tic30.c \
../nachos_initialCode/tools/binutils-2.25/bfd/aout0.c \
../nachos_initialCode/tools/binutils-2.25/bfd/aout32.c \
../nachos_initialCode/tools/binutils-2.25/bfd/aout64.c \
../nachos_initialCode/tools/binutils-2.25/bfd/archive.c \
../nachos_initialCode/tools/binutils-2.25/bfd/archive64.c \
../nachos_initialCode/tools/binutils-2.25/bfd/archures.c \
../nachos_initialCode/tools/binutils-2.25/bfd/armnetbsd.c \
../nachos_initialCode/tools/binutils-2.25/bfd/bfd.c \
../nachos_initialCode/tools/binutils-2.25/bfd/bfdio.c \
../nachos_initialCode/tools/binutils-2.25/bfd/bfdwin.c \
../nachos_initialCode/tools/binutils-2.25/bfd/binary.c \
../nachos_initialCode/tools/binutils-2.25/bfd/bout.c \
../nachos_initialCode/tools/binutils-2.25/bfd/cache.c \
../nachos_initialCode/tools/binutils-2.25/bfd/cf-i386lynx.c \
../nachos_initialCode/tools/binutils-2.25/bfd/cf-sparclynx.c \
../nachos_initialCode/tools/binutils-2.25/bfd/cisco-core.c \
../nachos_initialCode/tools/binutils-2.25/bfd/coff-alpha.c \
../nachos_initialCode/tools/binutils-2.25/bfd/coff-apollo.c \
../nachos_initialCode/tools/binutils-2.25/bfd/coff-arm.c \
../nachos_initialCode/tools/binutils-2.25/bfd/coff-aux.c \
../nachos_initialCode/tools/binutils-2.25/bfd/coff-go32.c \
../nachos_initialCode/tools/binutils-2.25/bfd/coff-h8300.c \
../nachos_initialCode/tools/binutils-2.25/bfd/coff-h8500.c \
../nachos_initialCode/tools/binutils-2.25/bfd/coff-i386.c \
../nachos_initialCode/tools/binutils-2.25/bfd/coff-i860.c \
../nachos_initialCode/tools/binutils-2.25/bfd/coff-i960.c \
../nachos_initialCode/tools/binutils-2.25/bfd/coff-ia64.c \
../nachos_initialCode/tools/binutils-2.25/bfd/coff-m68k.c \
../nachos_initialCode/tools/binutils-2.25/bfd/coff-m88k.c \
../nachos_initialCode/tools/binutils-2.25/bfd/coff-mcore.c \
../nachos_initialCode/tools/binutils-2.25/bfd/coff-mips.c \
../nachos_initialCode/tools/binutils-2.25/bfd/coff-ppc.c \
../nachos_initialCode/tools/binutils-2.25/bfd/coff-rs6000.c \
../nachos_initialCode/tools/binutils-2.25/bfd/coff-sh.c \
../nachos_initialCode/tools/binutils-2.25/bfd/coff-sparc.c \
../nachos_initialCode/tools/binutils-2.25/bfd/coff-stgo32.c \
../nachos_initialCode/tools/binutils-2.25/bfd/coff-svm68k.c \
../nachos_initialCode/tools/binutils-2.25/bfd/coff-tic30.c \
../nachos_initialCode/tools/binutils-2.25/bfd/coff-tic4x.c \
../nachos_initialCode/tools/binutils-2.25/bfd/coff-tic54x.c \
../nachos_initialCode/tools/binutils-2.25/bfd/coff-tic80.c \
../nachos_initialCode/tools/binutils-2.25/bfd/coff-u68k.c \
../nachos_initialCode/tools/binutils-2.25/bfd/coff-w65.c \
../nachos_initialCode/tools/binutils-2.25/bfd/coff-we32k.c \
../nachos_initialCode/tools/binutils-2.25/bfd/coff-x86_64.c \
../nachos_initialCode/tools/binutils-2.25/bfd/coff-z80.c \
../nachos_initialCode/tools/binutils-2.25/bfd/coff-z8k.c \
../nachos_initialCode/tools/binutils-2.25/bfd/coff64-rs6000.c \
../nachos_initialCode/tools/binutils-2.25/bfd/coffgen.c \
../nachos_initialCode/tools/binutils-2.25/bfd/cofflink.c \
../nachos_initialCode/tools/binutils-2.25/bfd/compress.c \
../nachos_initialCode/tools/binutils-2.25/bfd/corefile.c \
../nachos_initialCode/tools/binutils-2.25/bfd/cpu-aarch64.c \
../nachos_initialCode/tools/binutils-2.25/bfd/cpu-alpha.c \
../nachos_initialCode/tools/binutils-2.25/bfd/cpu-arc.c \
../nachos_initialCode/tools/binutils-2.25/bfd/cpu-arm.c \
../nachos_initialCode/tools/binutils-2.25/bfd/cpu-avr.c \
../nachos_initialCode/tools/binutils-2.25/bfd/cpu-bfin.c \
../nachos_initialCode/tools/binutils-2.25/bfd/cpu-cr16.c \
../nachos_initialCode/tools/binutils-2.25/bfd/cpu-cr16c.c \
../nachos_initialCode/tools/binutils-2.25/bfd/cpu-cris.c \
../nachos_initialCode/tools/binutils-2.25/bfd/cpu-crx.c \
../nachos_initialCode/tools/binutils-2.25/bfd/cpu-d10v.c \
../nachos_initialCode/tools/binutils-2.25/bfd/cpu-d30v.c \
../nachos_initialCode/tools/binutils-2.25/bfd/cpu-dlx.c \
../nachos_initialCode/tools/binutils-2.25/bfd/cpu-epiphany.c \
../nachos_initialCode/tools/binutils-2.25/bfd/cpu-fr30.c \
../nachos_initialCode/tools/binutils-2.25/bfd/cpu-frv.c \
../nachos_initialCode/tools/binutils-2.25/bfd/cpu-h8300.c \
../nachos_initialCode/tools/binutils-2.25/bfd/cpu-h8500.c \
../nachos_initialCode/tools/binutils-2.25/bfd/cpu-hppa.c \
../nachos_initialCode/tools/binutils-2.25/bfd/cpu-i370.c \
../nachos_initialCode/tools/binutils-2.25/bfd/cpu-i386.c \
../nachos_initialCode/tools/binutils-2.25/bfd/cpu-i860.c \
../nachos_initialCode/tools/binutils-2.25/bfd/cpu-i960.c \
../nachos_initialCode/tools/binutils-2.25/bfd/cpu-ia64-opc.c \
../nachos_initialCode/tools/binutils-2.25/bfd/cpu-ia64.c \
../nachos_initialCode/tools/binutils-2.25/bfd/cpu-ip2k.c \
../nachos_initialCode/tools/binutils-2.25/bfd/cpu-iq2000.c \
../nachos_initialCode/tools/binutils-2.25/bfd/cpu-k1om.c \
../nachos_initialCode/tools/binutils-2.25/bfd/cpu-l1om.c \
../nachos_initialCode/tools/binutils-2.25/bfd/cpu-lm32.c \
../nachos_initialCode/tools/binutils-2.25/bfd/cpu-m10200.c \
../nachos_initialCode/tools/binutils-2.25/bfd/cpu-m10300.c \
../nachos_initialCode/tools/binutils-2.25/bfd/cpu-m32c.c \
../nachos_initialCode/tools/binutils-2.25/bfd/cpu-m32r.c \
../nachos_initialCode/tools/binutils-2.25/bfd/cpu-m68hc11.c \
../nachos_initialCode/tools/binutils-2.25/bfd/cpu-m68hc12.c \
../nachos_initialCode/tools/binutils-2.25/bfd/cpu-m68k.c \
../nachos_initialCode/tools/binutils-2.25/bfd/cpu-m88k.c \
../nachos_initialCode/tools/binutils-2.25/bfd/cpu-m9s12x.c \
../nachos_initialCode/tools/binutils-2.25/bfd/cpu-m9s12xg.c \
../nachos_initialCode/tools/binutils-2.25/bfd/cpu-mcore.c \
../nachos_initialCode/tools/binutils-2.25/bfd/cpu-mep.c \
../nachos_initialCode/tools/binutils-2.25/bfd/cpu-metag.c \
../nachos_initialCode/tools/binutils-2.25/bfd/cpu-microblaze.c \
../nachos_initialCode/tools/binutils-2.25/bfd/cpu-mips.c \
../nachos_initialCode/tools/binutils-2.25/bfd/cpu-mmix.c \
../nachos_initialCode/tools/binutils-2.25/bfd/cpu-moxie.c \
../nachos_initialCode/tools/binutils-2.25/bfd/cpu-msp430.c \
../nachos_initialCode/tools/binutils-2.25/bfd/cpu-mt.c \
../nachos_initialCode/tools/binutils-2.25/bfd/cpu-nds32.c \
../nachos_initialCode/tools/binutils-2.25/bfd/cpu-nios2.c \
../nachos_initialCode/tools/binutils-2.25/bfd/cpu-ns32k.c \
../nachos_initialCode/tools/binutils-2.25/bfd/cpu-or1k.c \
../nachos_initialCode/tools/binutils-2.25/bfd/cpu-pdp11.c \
../nachos_initialCode/tools/binutils-2.25/bfd/cpu-pj.c \
../nachos_initialCode/tools/binutils-2.25/bfd/cpu-plugin.c \
../nachos_initialCode/tools/binutils-2.25/bfd/cpu-powerpc.c \
../nachos_initialCode/tools/binutils-2.25/bfd/cpu-rl78.c \
../nachos_initialCode/tools/binutils-2.25/bfd/cpu-rs6000.c \
../nachos_initialCode/tools/binutils-2.25/bfd/cpu-rx.c \
../nachos_initialCode/tools/binutils-2.25/bfd/cpu-s390.c \
../nachos_initialCode/tools/binutils-2.25/bfd/cpu-score.c \
../nachos_initialCode/tools/binutils-2.25/bfd/cpu-sh.c \
../nachos_initialCode/tools/binutils-2.25/bfd/cpu-sparc.c \
../nachos_initialCode/tools/binutils-2.25/bfd/cpu-spu.c \
../nachos_initialCode/tools/binutils-2.25/bfd/cpu-tic30.c \
../nachos_initialCode/tools/binutils-2.25/bfd/cpu-tic4x.c \
../nachos_initialCode/tools/binutils-2.25/bfd/cpu-tic54x.c \
../nachos_initialCode/tools/binutils-2.25/bfd/cpu-tic6x.c \
../nachos_initialCode/tools/binutils-2.25/bfd/cpu-tic80.c \
../nachos_initialCode/tools/binutils-2.25/bfd/cpu-tilegx.c \
../nachos_initialCode/tools/binutils-2.25/bfd/cpu-tilepro.c \
../nachos_initialCode/tools/binutils-2.25/bfd/cpu-v850.c \
../nachos_initialCode/tools/binutils-2.25/bfd/cpu-v850_rh850.c \
../nachos_initialCode/tools/binutils-2.25/bfd/cpu-vax.c \
../nachos_initialCode/tools/binutils-2.25/bfd/cpu-w65.c \
../nachos_initialCode/tools/binutils-2.25/bfd/cpu-we32k.c \
../nachos_initialCode/tools/binutils-2.25/bfd/cpu-xc16x.c \
../nachos_initialCode/tools/binutils-2.25/bfd/cpu-xgate.c \
../nachos_initialCode/tools/binutils-2.25/bfd/cpu-xstormy16.c \
../nachos_initialCode/tools/binutils-2.25/bfd/cpu-xtensa.c \
../nachos_initialCode/tools/binutils-2.25/bfd/cpu-z80.c \
../nachos_initialCode/tools/binutils-2.25/bfd/cpu-z8k.c \
../nachos_initialCode/tools/binutils-2.25/bfd/demo64.c \
../nachos_initialCode/tools/binutils-2.25/bfd/dwarf1.c \
../nachos_initialCode/tools/binutils-2.25/bfd/dwarf2.c \
../nachos_initialCode/tools/binutils-2.25/bfd/ecoff.c \
../nachos_initialCode/tools/binutils-2.25/bfd/ecofflink.c \
../nachos_initialCode/tools/binutils-2.25/bfd/elf-attrs.c \
../nachos_initialCode/tools/binutils-2.25/bfd/elf-eh-frame.c \
../nachos_initialCode/tools/binutils-2.25/bfd/elf-ifunc.c \
../nachos_initialCode/tools/binutils-2.25/bfd/elf-m10200.c \
../nachos_initialCode/tools/binutils-2.25/bfd/elf-m10300.c \
../nachos_initialCode/tools/binutils-2.25/bfd/elf-nacl.c \
../nachos_initialCode/tools/binutils-2.25/bfd/elf-s390-common.c \
../nachos_initialCode/tools/binutils-2.25/bfd/elf-strtab.c \
../nachos_initialCode/tools/binutils-2.25/bfd/elf-vxworks.c \
../nachos_initialCode/tools/binutils-2.25/bfd/elf.c \
../nachos_initialCode/tools/binutils-2.25/bfd/elf32-am33lin.c \
../nachos_initialCode/tools/binutils-2.25/bfd/elf32-arc.c \
../nachos_initialCode/tools/binutils-2.25/bfd/elf32-arm.c \
../nachos_initialCode/tools/binutils-2.25/bfd/elf32-avr.c \
../nachos_initialCode/tools/binutils-2.25/bfd/elf32-bfin.c \
../nachos_initialCode/tools/binutils-2.25/bfd/elf32-cr16.c \
../nachos_initialCode/tools/binutils-2.25/bfd/elf32-cr16c.c \
../nachos_initialCode/tools/binutils-2.25/bfd/elf32-cris.c \
../nachos_initialCode/tools/binutils-2.25/bfd/elf32-crx.c \
../nachos_initialCode/tools/binutils-2.25/bfd/elf32-d10v.c \
../nachos_initialCode/tools/binutils-2.25/bfd/elf32-d30v.c \
../nachos_initialCode/tools/binutils-2.25/bfd/elf32-dlx.c \
../nachos_initialCode/tools/binutils-2.25/bfd/elf32-epiphany.c \
../nachos_initialCode/tools/binutils-2.25/bfd/elf32-fr30.c \
../nachos_initialCode/tools/binutils-2.25/bfd/elf32-frv.c \
../nachos_initialCode/tools/binutils-2.25/bfd/elf32-gen.c \
../nachos_initialCode/tools/binutils-2.25/bfd/elf32-h8300.c \
../nachos_initialCode/tools/binutils-2.25/bfd/elf32-hppa.c \
../nachos_initialCode/tools/binutils-2.25/bfd/elf32-i370.c \
../nachos_initialCode/tools/binutils-2.25/bfd/elf32-i386.c \
../nachos_initialCode/tools/binutils-2.25/bfd/elf32-i860.c \
../nachos_initialCode/tools/binutils-2.25/bfd/elf32-i960.c \
../nachos_initialCode/tools/binutils-2.25/bfd/elf32-ip2k.c \
../nachos_initialCode/tools/binutils-2.25/bfd/elf32-iq2000.c \
../nachos_initialCode/tools/binutils-2.25/bfd/elf32-lm32.c \
../nachos_initialCode/tools/binutils-2.25/bfd/elf32-m32c.c \
../nachos_initialCode/tools/binutils-2.25/bfd/elf32-m32r.c \
../nachos_initialCode/tools/binutils-2.25/bfd/elf32-m68hc11.c \
../nachos_initialCode/tools/binutils-2.25/bfd/elf32-m68hc12.c \
../nachos_initialCode/tools/binutils-2.25/bfd/elf32-m68hc1x.c \
../nachos_initialCode/tools/binutils-2.25/bfd/elf32-m68k.c \
../nachos_initialCode/tools/binutils-2.25/bfd/elf32-m88k.c \
../nachos_initialCode/tools/binutils-2.25/bfd/elf32-mcore.c \
../nachos_initialCode/tools/binutils-2.25/bfd/elf32-mep.c \
../nachos_initialCode/tools/binutils-2.25/bfd/elf32-metag.c \
../nachos_initialCode/tools/binutils-2.25/bfd/elf32-microblaze.c \
../nachos_initialCode/tools/binutils-2.25/bfd/elf32-mips.c \
../nachos_initialCode/tools/binutils-2.25/bfd/elf32-moxie.c \
../nachos_initialCode/tools/binutils-2.25/bfd/elf32-msp430.c \
../nachos_initialCode/tools/binutils-2.25/bfd/elf32-mt.c \
../nachos_initialCode/tools/binutils-2.25/bfd/elf32-nds32.c \
../nachos_initialCode/tools/binutils-2.25/bfd/elf32-nios2.c \
../nachos_initialCode/tools/binutils-2.25/bfd/elf32-or1k.c \
../nachos_initialCode/tools/binutils-2.25/bfd/elf32-pj.c \
../nachos_initialCode/tools/binutils-2.25/bfd/elf32-ppc.c \
../nachos_initialCode/tools/binutils-2.25/bfd/elf32-rl78.c \
../nachos_initialCode/tools/binutils-2.25/bfd/elf32-rx.c \
../nachos_initialCode/tools/binutils-2.25/bfd/elf32-s390.c \
../nachos_initialCode/tools/binutils-2.25/bfd/elf32-score.c \
../nachos_initialCode/tools/binutils-2.25/bfd/elf32-score7.c \
../nachos_initialCode/tools/binutils-2.25/bfd/elf32-sh-symbian.c \
../nachos_initialCode/tools/binutils-2.25/bfd/elf32-sh.c \
../nachos_initialCode/tools/binutils-2.25/bfd/elf32-sh64-com.c \
../nachos_initialCode/tools/binutils-2.25/bfd/elf32-sh64.c \
../nachos_initialCode/tools/binutils-2.25/bfd/elf32-sparc.c \
../nachos_initialCode/tools/binutils-2.25/bfd/elf32-spu.c \
../nachos_initialCode/tools/binutils-2.25/bfd/elf32-tic6x.c \
../nachos_initialCode/tools/binutils-2.25/bfd/elf32-tilegx.c \
../nachos_initialCode/tools/binutils-2.25/bfd/elf32-tilepro.c \
../nachos_initialCode/tools/binutils-2.25/bfd/elf32-v850.c \
../nachos_initialCode/tools/binutils-2.25/bfd/elf32-vax.c \
../nachos_initialCode/tools/binutils-2.25/bfd/elf32-xc16x.c \
../nachos_initialCode/tools/binutils-2.25/bfd/elf32-xgate.c \
../nachos_initialCode/tools/binutils-2.25/bfd/elf32-xstormy16.c \
../nachos_initialCode/tools/binutils-2.25/bfd/elf32-xtensa.c \
../nachos_initialCode/tools/binutils-2.25/bfd/elf32.c \
../nachos_initialCode/tools/binutils-2.25/bfd/elf64-alpha.c \
../nachos_initialCode/tools/binutils-2.25/bfd/elf64-gen.c \
../nachos_initialCode/tools/binutils-2.25/bfd/elf64-hppa.c \
../nachos_initialCode/tools/binutils-2.25/bfd/elf64-ia64-vms.c \
../nachos_initialCode/tools/binutils-2.25/bfd/elf64-mips.c \
../nachos_initialCode/tools/binutils-2.25/bfd/elf64-mmix.c \
../nachos_initialCode/tools/binutils-2.25/bfd/elf64-ppc.c \
../nachos_initialCode/tools/binutils-2.25/bfd/elf64-s390.c \
../nachos_initialCode/tools/binutils-2.25/bfd/elf64-sh64.c \
../nachos_initialCode/tools/binutils-2.25/bfd/elf64-sparc.c \
../nachos_initialCode/tools/binutils-2.25/bfd/elf64-tilegx.c \
../nachos_initialCode/tools/binutils-2.25/bfd/elf64-x86-64.c \
../nachos_initialCode/tools/binutils-2.25/bfd/elf64.c \
../nachos_initialCode/tools/binutils-2.25/bfd/elflink.c \
../nachos_initialCode/tools/binutils-2.25/bfd/elfn32-mips.c \
../nachos_initialCode/tools/binutils-2.25/bfd/elfnn-aarch64.c \
../nachos_initialCode/tools/binutils-2.25/bfd/elfnn-ia64.c \
../nachos_initialCode/tools/binutils-2.25/bfd/elfxx-aarch64.c \
../nachos_initialCode/tools/binutils-2.25/bfd/elfxx-ia64.c \
../nachos_initialCode/tools/binutils-2.25/bfd/elfxx-mips.c \
../nachos_initialCode/tools/binutils-2.25/bfd/elfxx-sparc.c \
../nachos_initialCode/tools/binutils-2.25/bfd/elfxx-tilegx.c \
../nachos_initialCode/tools/binutils-2.25/bfd/epoc-pe-arm.c \
../nachos_initialCode/tools/binutils-2.25/bfd/epoc-pei-arm.c \
../nachos_initialCode/tools/binutils-2.25/bfd/format.c \
../nachos_initialCode/tools/binutils-2.25/bfd/gen-aout.c \
../nachos_initialCode/tools/binutils-2.25/bfd/hash.c \
../nachos_initialCode/tools/binutils-2.25/bfd/host-aout.c \
../nachos_initialCode/tools/binutils-2.25/bfd/hp300bsd.c \
../nachos_initialCode/tools/binutils-2.25/bfd/hp300hpux.c \
../nachos_initialCode/tools/binutils-2.25/bfd/hppabsd-core.c \
../nachos_initialCode/tools/binutils-2.25/bfd/hpux-core.c \
../nachos_initialCode/tools/binutils-2.25/bfd/i386aout.c \
../nachos_initialCode/tools/binutils-2.25/bfd/i386bsd.c \
../nachos_initialCode/tools/binutils-2.25/bfd/i386dynix.c \
../nachos_initialCode/tools/binutils-2.25/bfd/i386freebsd.c \
../nachos_initialCode/tools/binutils-2.25/bfd/i386linux.c \
../nachos_initialCode/tools/binutils-2.25/bfd/i386lynx.c \
../nachos_initialCode/tools/binutils-2.25/bfd/i386mach3.c \
../nachos_initialCode/tools/binutils-2.25/bfd/i386msdos.c \
../nachos_initialCode/tools/binutils-2.25/bfd/i386netbsd.c \
../nachos_initialCode/tools/binutils-2.25/bfd/i386os9k.c \
../nachos_initialCode/tools/binutils-2.25/bfd/ieee.c \
../nachos_initialCode/tools/binutils-2.25/bfd/ihex.c \
../nachos_initialCode/tools/binutils-2.25/bfd/init.c \
../nachos_initialCode/tools/binutils-2.25/bfd/irix-core.c \
../nachos_initialCode/tools/binutils-2.25/bfd/libbfd.c \
../nachos_initialCode/tools/binutils-2.25/bfd/linker.c \
../nachos_initialCode/tools/binutils-2.25/bfd/lynx-core.c \
../nachos_initialCode/tools/binutils-2.25/bfd/m68k4knetbsd.c \
../nachos_initialCode/tools/binutils-2.25/bfd/m68klinux.c \
../nachos_initialCode/tools/binutils-2.25/bfd/m68knetbsd.c \
../nachos_initialCode/tools/binutils-2.25/bfd/m88kmach3.c \
../nachos_initialCode/tools/binutils-2.25/bfd/m88kopenbsd.c \
../nachos_initialCode/tools/binutils-2.25/bfd/mach-o-i386.c \
../nachos_initialCode/tools/binutils-2.25/bfd/mach-o-target.c \
../nachos_initialCode/tools/binutils-2.25/bfd/mach-o-x86-64.c \
../nachos_initialCode/tools/binutils-2.25/bfd/mach-o.c \
../nachos_initialCode/tools/binutils-2.25/bfd/merge.c \
../nachos_initialCode/tools/binutils-2.25/bfd/mipsbsd.c \
../nachos_initialCode/tools/binutils-2.25/bfd/mmo.c \
../nachos_initialCode/tools/binutils-2.25/bfd/netbsd-core.c \
../nachos_initialCode/tools/binutils-2.25/bfd/newsos3.c \
../nachos_initialCode/tools/binutils-2.25/bfd/nlm.c \
../nachos_initialCode/tools/binutils-2.25/bfd/nlm32-alpha.c \
../nachos_initialCode/tools/binutils-2.25/bfd/nlm32-i386.c \
../nachos_initialCode/tools/binutils-2.25/bfd/nlm32-ppc.c \
../nachos_initialCode/tools/binutils-2.25/bfd/nlm32-sparc.c \
../nachos_initialCode/tools/binutils-2.25/bfd/nlm32.c \
../nachos_initialCode/tools/binutils-2.25/bfd/nlm64.c \
../nachos_initialCode/tools/binutils-2.25/bfd/ns32knetbsd.c \
../nachos_initialCode/tools/binutils-2.25/bfd/oasys.c \
../nachos_initialCode/tools/binutils-2.25/bfd/opncls.c \
../nachos_initialCode/tools/binutils-2.25/bfd/osf-core.c \
../nachos_initialCode/tools/binutils-2.25/bfd/pc532-mach.c \
../nachos_initialCode/tools/binutils-2.25/bfd/pdp11.c \
../nachos_initialCode/tools/binutils-2.25/bfd/pe-arm-wince.c \
../nachos_initialCode/tools/binutils-2.25/bfd/pe-arm.c \
../nachos_initialCode/tools/binutils-2.25/bfd/pe-i386.c \
../nachos_initialCode/tools/binutils-2.25/bfd/pe-mcore.c \
../nachos_initialCode/tools/binutils-2.25/bfd/pe-mips.c \
../nachos_initialCode/tools/binutils-2.25/bfd/pe-ppc.c \
../nachos_initialCode/tools/binutils-2.25/bfd/pe-sh.c \
../nachos_initialCode/tools/binutils-2.25/bfd/pe-x86_64.c \
../nachos_initialCode/tools/binutils-2.25/bfd/peXXigen.c \
../nachos_initialCode/tools/binutils-2.25/bfd/pef.c \
../nachos_initialCode/tools/binutils-2.25/bfd/pei-arm-wince.c \
../nachos_initialCode/tools/binutils-2.25/bfd/pei-arm.c \
../nachos_initialCode/tools/binutils-2.25/bfd/pei-i386.c \
../nachos_initialCode/tools/binutils-2.25/bfd/pei-ia64.c \
../nachos_initialCode/tools/binutils-2.25/bfd/pei-mcore.c \
../nachos_initialCode/tools/binutils-2.25/bfd/pei-mips.c \
../nachos_initialCode/tools/binutils-2.25/bfd/pei-ppc.c \
../nachos_initialCode/tools/binutils-2.25/bfd/pei-sh.c \
../nachos_initialCode/tools/binutils-2.25/bfd/pei-x86_64.c \
../nachos_initialCode/tools/binutils-2.25/bfd/plugin.c \
../nachos_initialCode/tools/binutils-2.25/bfd/ppcboot.c \
../nachos_initialCode/tools/binutils-2.25/bfd/ptrace-core.c \
../nachos_initialCode/tools/binutils-2.25/bfd/reloc.c \
../nachos_initialCode/tools/binutils-2.25/bfd/reloc16.c \
../nachos_initialCode/tools/binutils-2.25/bfd/riscix.c \
../nachos_initialCode/tools/binutils-2.25/bfd/rs6000-core.c \
../nachos_initialCode/tools/binutils-2.25/bfd/sco5-core.c \
../nachos_initialCode/tools/binutils-2.25/bfd/section.c \
../nachos_initialCode/tools/binutils-2.25/bfd/simple.c \
../nachos_initialCode/tools/binutils-2.25/bfd/som.c \
../nachos_initialCode/tools/binutils-2.25/bfd/sparclinux.c \
../nachos_initialCode/tools/binutils-2.25/bfd/sparclynx.c \
../nachos_initialCode/tools/binutils-2.25/bfd/sparcnetbsd.c \
../nachos_initialCode/tools/binutils-2.25/bfd/srec.c \
../nachos_initialCode/tools/binutils-2.25/bfd/stab-syms.c \
../nachos_initialCode/tools/binutils-2.25/bfd/stabs.c \
../nachos_initialCode/tools/binutils-2.25/bfd/sunos.c \
../nachos_initialCode/tools/binutils-2.25/bfd/syms.c \
../nachos_initialCode/tools/binutils-2.25/bfd/targets.c \
../nachos_initialCode/tools/binutils-2.25/bfd/tekhex.c \
../nachos_initialCode/tools/binutils-2.25/bfd/trad-core.c \
../nachos_initialCode/tools/binutils-2.25/bfd/vax1knetbsd.c \
../nachos_initialCode/tools/binutils-2.25/bfd/vaxbsd.c \
../nachos_initialCode/tools/binutils-2.25/bfd/vaxnetbsd.c \
../nachos_initialCode/tools/binutils-2.25/bfd/verilog.c \
../nachos_initialCode/tools/binutils-2.25/bfd/versados.c \
../nachos_initialCode/tools/binutils-2.25/bfd/vms-alpha.c \
../nachos_initialCode/tools/binutils-2.25/bfd/vms-lib.c \
../nachos_initialCode/tools/binutils-2.25/bfd/vms-misc.c \
../nachos_initialCode/tools/binutils-2.25/bfd/xcofflink.c \
../nachos_initialCode/tools/binutils-2.25/bfd/xsym.c \
../nachos_initialCode/tools/binutils-2.25/bfd/xtensa-isa.c \
../nachos_initialCode/tools/binutils-2.25/bfd/xtensa-modules.c 

OBJS += \
./nachos_initialCode/tools/binutils-2.25/bfd/aix386-core.o \
./nachos_initialCode/tools/binutils-2.25/bfd/aix5ppc-core.o \
./nachos_initialCode/tools/binutils-2.25/bfd/aout-adobe.o \
./nachos_initialCode/tools/binutils-2.25/bfd/aout-arm.o \
./nachos_initialCode/tools/binutils-2.25/bfd/aout-cris.o \
./nachos_initialCode/tools/binutils-2.25/bfd/aout-ns32k.o \
./nachos_initialCode/tools/binutils-2.25/bfd/aout-sparcle.o \
./nachos_initialCode/tools/binutils-2.25/bfd/aout-tic30.o \
./nachos_initialCode/tools/binutils-2.25/bfd/aout0.o \
./nachos_initialCode/tools/binutils-2.25/bfd/aout32.o \
./nachos_initialCode/tools/binutils-2.25/bfd/aout64.o \
./nachos_initialCode/tools/binutils-2.25/bfd/archive.o \
./nachos_initialCode/tools/binutils-2.25/bfd/archive64.o \
./nachos_initialCode/tools/binutils-2.25/bfd/archures.o \
./nachos_initialCode/tools/binutils-2.25/bfd/armnetbsd.o \
./nachos_initialCode/tools/binutils-2.25/bfd/bfd.o \
./nachos_initialCode/tools/binutils-2.25/bfd/bfdio.o \
./nachos_initialCode/tools/binutils-2.25/bfd/bfdwin.o \
./nachos_initialCode/tools/binutils-2.25/bfd/binary.o \
./nachos_initialCode/tools/binutils-2.25/bfd/bout.o \
./nachos_initialCode/tools/binutils-2.25/bfd/cache.o \
./nachos_initialCode/tools/binutils-2.25/bfd/cf-i386lynx.o \
./nachos_initialCode/tools/binutils-2.25/bfd/cf-sparclynx.o \
./nachos_initialCode/tools/binutils-2.25/bfd/cisco-core.o \
./nachos_initialCode/tools/binutils-2.25/bfd/coff-alpha.o \
./nachos_initialCode/tools/binutils-2.25/bfd/coff-apollo.o \
./nachos_initialCode/tools/binutils-2.25/bfd/coff-arm.o \
./nachos_initialCode/tools/binutils-2.25/bfd/coff-aux.o \
./nachos_initialCode/tools/binutils-2.25/bfd/coff-go32.o \
./nachos_initialCode/tools/binutils-2.25/bfd/coff-h8300.o \
./nachos_initialCode/tools/binutils-2.25/bfd/coff-h8500.o \
./nachos_initialCode/tools/binutils-2.25/bfd/coff-i386.o \
./nachos_initialCode/tools/binutils-2.25/bfd/coff-i860.o \
./nachos_initialCode/tools/binutils-2.25/bfd/coff-i960.o \
./nachos_initialCode/tools/binutils-2.25/bfd/coff-ia64.o \
./nachos_initialCode/tools/binutils-2.25/bfd/coff-m68k.o \
./nachos_initialCode/tools/binutils-2.25/bfd/coff-m88k.o \
./nachos_initialCode/tools/binutils-2.25/bfd/coff-mcore.o \
./nachos_initialCode/tools/binutils-2.25/bfd/coff-mips.o \
./nachos_initialCode/tools/binutils-2.25/bfd/coff-ppc.o \
./nachos_initialCode/tools/binutils-2.25/bfd/coff-rs6000.o \
./nachos_initialCode/tools/binutils-2.25/bfd/coff-sh.o \
./nachos_initialCode/tools/binutils-2.25/bfd/coff-sparc.o \
./nachos_initialCode/tools/binutils-2.25/bfd/coff-stgo32.o \
./nachos_initialCode/tools/binutils-2.25/bfd/coff-svm68k.o \
./nachos_initialCode/tools/binutils-2.25/bfd/coff-tic30.o \
./nachos_initialCode/tools/binutils-2.25/bfd/coff-tic4x.o \
./nachos_initialCode/tools/binutils-2.25/bfd/coff-tic54x.o \
./nachos_initialCode/tools/binutils-2.25/bfd/coff-tic80.o \
./nachos_initialCode/tools/binutils-2.25/bfd/coff-u68k.o \
./nachos_initialCode/tools/binutils-2.25/bfd/coff-w65.o \
./nachos_initialCode/tools/binutils-2.25/bfd/coff-we32k.o \
./nachos_initialCode/tools/binutils-2.25/bfd/coff-x86_64.o \
./nachos_initialCode/tools/binutils-2.25/bfd/coff-z80.o \
./nachos_initialCode/tools/binutils-2.25/bfd/coff-z8k.o \
./nachos_initialCode/tools/binutils-2.25/bfd/coff64-rs6000.o \
./nachos_initialCode/tools/binutils-2.25/bfd/coffgen.o \
./nachos_initialCode/tools/binutils-2.25/bfd/cofflink.o \
./nachos_initialCode/tools/binutils-2.25/bfd/compress.o \
./nachos_initialCode/tools/binutils-2.25/bfd/corefile.o \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-aarch64.o \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-alpha.o \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-arc.o \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-arm.o \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-avr.o \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-bfin.o \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-cr16.o \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-cr16c.o \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-cris.o \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-crx.o \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-d10v.o \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-d30v.o \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-dlx.o \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-epiphany.o \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-fr30.o \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-frv.o \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-h8300.o \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-h8500.o \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-hppa.o \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-i370.o \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-i386.o \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-i860.o \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-i960.o \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-ia64-opc.o \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-ia64.o \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-ip2k.o \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-iq2000.o \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-k1om.o \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-l1om.o \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-lm32.o \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-m10200.o \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-m10300.o \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-m32c.o \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-m32r.o \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-m68hc11.o \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-m68hc12.o \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-m68k.o \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-m88k.o \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-m9s12x.o \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-m9s12xg.o \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-mcore.o \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-mep.o \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-metag.o \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-microblaze.o \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-mips.o \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-mmix.o \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-moxie.o \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-msp430.o \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-mt.o \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-nds32.o \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-nios2.o \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-ns32k.o \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-or1k.o \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-pdp11.o \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-pj.o \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-plugin.o \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-powerpc.o \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-rl78.o \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-rs6000.o \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-rx.o \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-s390.o \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-score.o \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-sh.o \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-sparc.o \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-spu.o \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-tic30.o \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-tic4x.o \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-tic54x.o \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-tic6x.o \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-tic80.o \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-tilegx.o \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-tilepro.o \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-v850.o \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-v850_rh850.o \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-vax.o \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-w65.o \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-we32k.o \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-xc16x.o \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-xgate.o \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-xstormy16.o \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-xtensa.o \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-z80.o \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-z8k.o \
./nachos_initialCode/tools/binutils-2.25/bfd/demo64.o \
./nachos_initialCode/tools/binutils-2.25/bfd/dwarf1.o \
./nachos_initialCode/tools/binutils-2.25/bfd/dwarf2.o \
./nachos_initialCode/tools/binutils-2.25/bfd/ecoff.o \
./nachos_initialCode/tools/binutils-2.25/bfd/ecofflink.o \
./nachos_initialCode/tools/binutils-2.25/bfd/elf-attrs.o \
./nachos_initialCode/tools/binutils-2.25/bfd/elf-eh-frame.o \
./nachos_initialCode/tools/binutils-2.25/bfd/elf-ifunc.o \
./nachos_initialCode/tools/binutils-2.25/bfd/elf-m10200.o \
./nachos_initialCode/tools/binutils-2.25/bfd/elf-m10300.o \
./nachos_initialCode/tools/binutils-2.25/bfd/elf-nacl.o \
./nachos_initialCode/tools/binutils-2.25/bfd/elf-s390-common.o \
./nachos_initialCode/tools/binutils-2.25/bfd/elf-strtab.o \
./nachos_initialCode/tools/binutils-2.25/bfd/elf-vxworks.o \
./nachos_initialCode/tools/binutils-2.25/bfd/elf.o \
./nachos_initialCode/tools/binutils-2.25/bfd/elf32-am33lin.o \
./nachos_initialCode/tools/binutils-2.25/bfd/elf32-arc.o \
./nachos_initialCode/tools/binutils-2.25/bfd/elf32-arm.o \
./nachos_initialCode/tools/binutils-2.25/bfd/elf32-avr.o \
./nachos_initialCode/tools/binutils-2.25/bfd/elf32-bfin.o \
./nachos_initialCode/tools/binutils-2.25/bfd/elf32-cr16.o \
./nachos_initialCode/tools/binutils-2.25/bfd/elf32-cr16c.o \
./nachos_initialCode/tools/binutils-2.25/bfd/elf32-cris.o \
./nachos_initialCode/tools/binutils-2.25/bfd/elf32-crx.o \
./nachos_initialCode/tools/binutils-2.25/bfd/elf32-d10v.o \
./nachos_initialCode/tools/binutils-2.25/bfd/elf32-d30v.o \
./nachos_initialCode/tools/binutils-2.25/bfd/elf32-dlx.o \
./nachos_initialCode/tools/binutils-2.25/bfd/elf32-epiphany.o \
./nachos_initialCode/tools/binutils-2.25/bfd/elf32-fr30.o \
./nachos_initialCode/tools/binutils-2.25/bfd/elf32-frv.o \
./nachos_initialCode/tools/binutils-2.25/bfd/elf32-gen.o \
./nachos_initialCode/tools/binutils-2.25/bfd/elf32-h8300.o \
./nachos_initialCode/tools/binutils-2.25/bfd/elf32-hppa.o \
./nachos_initialCode/tools/binutils-2.25/bfd/elf32-i370.o \
./nachos_initialCode/tools/binutils-2.25/bfd/elf32-i386.o \
./nachos_initialCode/tools/binutils-2.25/bfd/elf32-i860.o \
./nachos_initialCode/tools/binutils-2.25/bfd/elf32-i960.o \
./nachos_initialCode/tools/binutils-2.25/bfd/elf32-ip2k.o \
./nachos_initialCode/tools/binutils-2.25/bfd/elf32-iq2000.o \
./nachos_initialCode/tools/binutils-2.25/bfd/elf32-lm32.o \
./nachos_initialCode/tools/binutils-2.25/bfd/elf32-m32c.o \
./nachos_initialCode/tools/binutils-2.25/bfd/elf32-m32r.o \
./nachos_initialCode/tools/binutils-2.25/bfd/elf32-m68hc11.o \
./nachos_initialCode/tools/binutils-2.25/bfd/elf32-m68hc12.o \
./nachos_initialCode/tools/binutils-2.25/bfd/elf32-m68hc1x.o \
./nachos_initialCode/tools/binutils-2.25/bfd/elf32-m68k.o \
./nachos_initialCode/tools/binutils-2.25/bfd/elf32-m88k.o \
./nachos_initialCode/tools/binutils-2.25/bfd/elf32-mcore.o \
./nachos_initialCode/tools/binutils-2.25/bfd/elf32-mep.o \
./nachos_initialCode/tools/binutils-2.25/bfd/elf32-metag.o \
./nachos_initialCode/tools/binutils-2.25/bfd/elf32-microblaze.o \
./nachos_initialCode/tools/binutils-2.25/bfd/elf32-mips.o \
./nachos_initialCode/tools/binutils-2.25/bfd/elf32-moxie.o \
./nachos_initialCode/tools/binutils-2.25/bfd/elf32-msp430.o \
./nachos_initialCode/tools/binutils-2.25/bfd/elf32-mt.o \
./nachos_initialCode/tools/binutils-2.25/bfd/elf32-nds32.o \
./nachos_initialCode/tools/binutils-2.25/bfd/elf32-nios2.o \
./nachos_initialCode/tools/binutils-2.25/bfd/elf32-or1k.o \
./nachos_initialCode/tools/binutils-2.25/bfd/elf32-pj.o \
./nachos_initialCode/tools/binutils-2.25/bfd/elf32-ppc.o \
./nachos_initialCode/tools/binutils-2.25/bfd/elf32-rl78.o \
./nachos_initialCode/tools/binutils-2.25/bfd/elf32-rx.o \
./nachos_initialCode/tools/binutils-2.25/bfd/elf32-s390.o \
./nachos_initialCode/tools/binutils-2.25/bfd/elf32-score.o \
./nachos_initialCode/tools/binutils-2.25/bfd/elf32-score7.o \
./nachos_initialCode/tools/binutils-2.25/bfd/elf32-sh-symbian.o \
./nachos_initialCode/tools/binutils-2.25/bfd/elf32-sh.o \
./nachos_initialCode/tools/binutils-2.25/bfd/elf32-sh64-com.o \
./nachos_initialCode/tools/binutils-2.25/bfd/elf32-sh64.o \
./nachos_initialCode/tools/binutils-2.25/bfd/elf32-sparc.o \
./nachos_initialCode/tools/binutils-2.25/bfd/elf32-spu.o \
./nachos_initialCode/tools/binutils-2.25/bfd/elf32-tic6x.o \
./nachos_initialCode/tools/binutils-2.25/bfd/elf32-tilegx.o \
./nachos_initialCode/tools/binutils-2.25/bfd/elf32-tilepro.o \
./nachos_initialCode/tools/binutils-2.25/bfd/elf32-v850.o \
./nachos_initialCode/tools/binutils-2.25/bfd/elf32-vax.o \
./nachos_initialCode/tools/binutils-2.25/bfd/elf32-xc16x.o \
./nachos_initialCode/tools/binutils-2.25/bfd/elf32-xgate.o \
./nachos_initialCode/tools/binutils-2.25/bfd/elf32-xstormy16.o \
./nachos_initialCode/tools/binutils-2.25/bfd/elf32-xtensa.o \
./nachos_initialCode/tools/binutils-2.25/bfd/elf32.o \
./nachos_initialCode/tools/binutils-2.25/bfd/elf64-alpha.o \
./nachos_initialCode/tools/binutils-2.25/bfd/elf64-gen.o \
./nachos_initialCode/tools/binutils-2.25/bfd/elf64-hppa.o \
./nachos_initialCode/tools/binutils-2.25/bfd/elf64-ia64-vms.o \
./nachos_initialCode/tools/binutils-2.25/bfd/elf64-mips.o \
./nachos_initialCode/tools/binutils-2.25/bfd/elf64-mmix.o \
./nachos_initialCode/tools/binutils-2.25/bfd/elf64-ppc.o \
./nachos_initialCode/tools/binutils-2.25/bfd/elf64-s390.o \
./nachos_initialCode/tools/binutils-2.25/bfd/elf64-sh64.o \
./nachos_initialCode/tools/binutils-2.25/bfd/elf64-sparc.o \
./nachos_initialCode/tools/binutils-2.25/bfd/elf64-tilegx.o \
./nachos_initialCode/tools/binutils-2.25/bfd/elf64-x86-64.o \
./nachos_initialCode/tools/binutils-2.25/bfd/elf64.o \
./nachos_initialCode/tools/binutils-2.25/bfd/elflink.o \
./nachos_initialCode/tools/binutils-2.25/bfd/elfn32-mips.o \
./nachos_initialCode/tools/binutils-2.25/bfd/elfnn-aarch64.o \
./nachos_initialCode/tools/binutils-2.25/bfd/elfnn-ia64.o \
./nachos_initialCode/tools/binutils-2.25/bfd/elfxx-aarch64.o \
./nachos_initialCode/tools/binutils-2.25/bfd/elfxx-ia64.o \
./nachos_initialCode/tools/binutils-2.25/bfd/elfxx-mips.o \
./nachos_initialCode/tools/binutils-2.25/bfd/elfxx-sparc.o \
./nachos_initialCode/tools/binutils-2.25/bfd/elfxx-tilegx.o \
./nachos_initialCode/tools/binutils-2.25/bfd/epoc-pe-arm.o \
./nachos_initialCode/tools/binutils-2.25/bfd/epoc-pei-arm.o \
./nachos_initialCode/tools/binutils-2.25/bfd/format.o \
./nachos_initialCode/tools/binutils-2.25/bfd/gen-aout.o \
./nachos_initialCode/tools/binutils-2.25/bfd/hash.o \
./nachos_initialCode/tools/binutils-2.25/bfd/host-aout.o \
./nachos_initialCode/tools/binutils-2.25/bfd/hp300bsd.o \
./nachos_initialCode/tools/binutils-2.25/bfd/hp300hpux.o \
./nachos_initialCode/tools/binutils-2.25/bfd/hppabsd-core.o \
./nachos_initialCode/tools/binutils-2.25/bfd/hpux-core.o \
./nachos_initialCode/tools/binutils-2.25/bfd/i386aout.o \
./nachos_initialCode/tools/binutils-2.25/bfd/i386bsd.o \
./nachos_initialCode/tools/binutils-2.25/bfd/i386dynix.o \
./nachos_initialCode/tools/binutils-2.25/bfd/i386freebsd.o \
./nachos_initialCode/tools/binutils-2.25/bfd/i386linux.o \
./nachos_initialCode/tools/binutils-2.25/bfd/i386lynx.o \
./nachos_initialCode/tools/binutils-2.25/bfd/i386mach3.o \
./nachos_initialCode/tools/binutils-2.25/bfd/i386msdos.o \
./nachos_initialCode/tools/binutils-2.25/bfd/i386netbsd.o \
./nachos_initialCode/tools/binutils-2.25/bfd/i386os9k.o \
./nachos_initialCode/tools/binutils-2.25/bfd/ieee.o \
./nachos_initialCode/tools/binutils-2.25/bfd/ihex.o \
./nachos_initialCode/tools/binutils-2.25/bfd/init.o \
./nachos_initialCode/tools/binutils-2.25/bfd/irix-core.o \
./nachos_initialCode/tools/binutils-2.25/bfd/libbfd.o \
./nachos_initialCode/tools/binutils-2.25/bfd/linker.o \
./nachos_initialCode/tools/binutils-2.25/bfd/lynx-core.o \
./nachos_initialCode/tools/binutils-2.25/bfd/m68k4knetbsd.o \
./nachos_initialCode/tools/binutils-2.25/bfd/m68klinux.o \
./nachos_initialCode/tools/binutils-2.25/bfd/m68knetbsd.o \
./nachos_initialCode/tools/binutils-2.25/bfd/m88kmach3.o \
./nachos_initialCode/tools/binutils-2.25/bfd/m88kopenbsd.o \
./nachos_initialCode/tools/binutils-2.25/bfd/mach-o-i386.o \
./nachos_initialCode/tools/binutils-2.25/bfd/mach-o-target.o \
./nachos_initialCode/tools/binutils-2.25/bfd/mach-o-x86-64.o \
./nachos_initialCode/tools/binutils-2.25/bfd/mach-o.o \
./nachos_initialCode/tools/binutils-2.25/bfd/merge.o \
./nachos_initialCode/tools/binutils-2.25/bfd/mipsbsd.o \
./nachos_initialCode/tools/binutils-2.25/bfd/mmo.o \
./nachos_initialCode/tools/binutils-2.25/bfd/netbsd-core.o \
./nachos_initialCode/tools/binutils-2.25/bfd/newsos3.o \
./nachos_initialCode/tools/binutils-2.25/bfd/nlm.o \
./nachos_initialCode/tools/binutils-2.25/bfd/nlm32-alpha.o \
./nachos_initialCode/tools/binutils-2.25/bfd/nlm32-i386.o \
./nachos_initialCode/tools/binutils-2.25/bfd/nlm32-ppc.o \
./nachos_initialCode/tools/binutils-2.25/bfd/nlm32-sparc.o \
./nachos_initialCode/tools/binutils-2.25/bfd/nlm32.o \
./nachos_initialCode/tools/binutils-2.25/bfd/nlm64.o \
./nachos_initialCode/tools/binutils-2.25/bfd/ns32knetbsd.o \
./nachos_initialCode/tools/binutils-2.25/bfd/oasys.o \
./nachos_initialCode/tools/binutils-2.25/bfd/opncls.o \
./nachos_initialCode/tools/binutils-2.25/bfd/osf-core.o \
./nachos_initialCode/tools/binutils-2.25/bfd/pc532-mach.o \
./nachos_initialCode/tools/binutils-2.25/bfd/pdp11.o \
./nachos_initialCode/tools/binutils-2.25/bfd/pe-arm-wince.o \
./nachos_initialCode/tools/binutils-2.25/bfd/pe-arm.o \
./nachos_initialCode/tools/binutils-2.25/bfd/pe-i386.o \
./nachos_initialCode/tools/binutils-2.25/bfd/pe-mcore.o \
./nachos_initialCode/tools/binutils-2.25/bfd/pe-mips.o \
./nachos_initialCode/tools/binutils-2.25/bfd/pe-ppc.o \
./nachos_initialCode/tools/binutils-2.25/bfd/pe-sh.o \
./nachos_initialCode/tools/binutils-2.25/bfd/pe-x86_64.o \
./nachos_initialCode/tools/binutils-2.25/bfd/peXXigen.o \
./nachos_initialCode/tools/binutils-2.25/bfd/pef.o \
./nachos_initialCode/tools/binutils-2.25/bfd/pei-arm-wince.o \
./nachos_initialCode/tools/binutils-2.25/bfd/pei-arm.o \
./nachos_initialCode/tools/binutils-2.25/bfd/pei-i386.o \
./nachos_initialCode/tools/binutils-2.25/bfd/pei-ia64.o \
./nachos_initialCode/tools/binutils-2.25/bfd/pei-mcore.o \
./nachos_initialCode/tools/binutils-2.25/bfd/pei-mips.o \
./nachos_initialCode/tools/binutils-2.25/bfd/pei-ppc.o \
./nachos_initialCode/tools/binutils-2.25/bfd/pei-sh.o \
./nachos_initialCode/tools/binutils-2.25/bfd/pei-x86_64.o \
./nachos_initialCode/tools/binutils-2.25/bfd/plugin.o \
./nachos_initialCode/tools/binutils-2.25/bfd/ppcboot.o \
./nachos_initialCode/tools/binutils-2.25/bfd/ptrace-core.o \
./nachos_initialCode/tools/binutils-2.25/bfd/reloc.o \
./nachos_initialCode/tools/binutils-2.25/bfd/reloc16.o \
./nachos_initialCode/tools/binutils-2.25/bfd/riscix.o \
./nachos_initialCode/tools/binutils-2.25/bfd/rs6000-core.o \
./nachos_initialCode/tools/binutils-2.25/bfd/sco5-core.o \
./nachos_initialCode/tools/binutils-2.25/bfd/section.o \
./nachos_initialCode/tools/binutils-2.25/bfd/simple.o \
./nachos_initialCode/tools/binutils-2.25/bfd/som.o \
./nachos_initialCode/tools/binutils-2.25/bfd/sparclinux.o \
./nachos_initialCode/tools/binutils-2.25/bfd/sparclynx.o \
./nachos_initialCode/tools/binutils-2.25/bfd/sparcnetbsd.o \
./nachos_initialCode/tools/binutils-2.25/bfd/srec.o \
./nachos_initialCode/tools/binutils-2.25/bfd/stab-syms.o \
./nachos_initialCode/tools/binutils-2.25/bfd/stabs.o \
./nachos_initialCode/tools/binutils-2.25/bfd/sunos.o \
./nachos_initialCode/tools/binutils-2.25/bfd/syms.o \
./nachos_initialCode/tools/binutils-2.25/bfd/targets.o \
./nachos_initialCode/tools/binutils-2.25/bfd/tekhex.o \
./nachos_initialCode/tools/binutils-2.25/bfd/trad-core.o \
./nachos_initialCode/tools/binutils-2.25/bfd/vax1knetbsd.o \
./nachos_initialCode/tools/binutils-2.25/bfd/vaxbsd.o \
./nachos_initialCode/tools/binutils-2.25/bfd/vaxnetbsd.o \
./nachos_initialCode/tools/binutils-2.25/bfd/verilog.o \
./nachos_initialCode/tools/binutils-2.25/bfd/versados.o \
./nachos_initialCode/tools/binutils-2.25/bfd/vms-alpha.o \
./nachos_initialCode/tools/binutils-2.25/bfd/vms-lib.o \
./nachos_initialCode/tools/binutils-2.25/bfd/vms-misc.o \
./nachos_initialCode/tools/binutils-2.25/bfd/xcofflink.o \
./nachos_initialCode/tools/binutils-2.25/bfd/xsym.o \
./nachos_initialCode/tools/binutils-2.25/bfd/xtensa-isa.o \
./nachos_initialCode/tools/binutils-2.25/bfd/xtensa-modules.o 

C_DEPS += \
./nachos_initialCode/tools/binutils-2.25/bfd/aix386-core.d \
./nachos_initialCode/tools/binutils-2.25/bfd/aix5ppc-core.d \
./nachos_initialCode/tools/binutils-2.25/bfd/aout-adobe.d \
./nachos_initialCode/tools/binutils-2.25/bfd/aout-arm.d \
./nachos_initialCode/tools/binutils-2.25/bfd/aout-cris.d \
./nachos_initialCode/tools/binutils-2.25/bfd/aout-ns32k.d \
./nachos_initialCode/tools/binutils-2.25/bfd/aout-sparcle.d \
./nachos_initialCode/tools/binutils-2.25/bfd/aout-tic30.d \
./nachos_initialCode/tools/binutils-2.25/bfd/aout0.d \
./nachos_initialCode/tools/binutils-2.25/bfd/aout32.d \
./nachos_initialCode/tools/binutils-2.25/bfd/aout64.d \
./nachos_initialCode/tools/binutils-2.25/bfd/archive.d \
./nachos_initialCode/tools/binutils-2.25/bfd/archive64.d \
./nachos_initialCode/tools/binutils-2.25/bfd/archures.d \
./nachos_initialCode/tools/binutils-2.25/bfd/armnetbsd.d \
./nachos_initialCode/tools/binutils-2.25/bfd/bfd.d \
./nachos_initialCode/tools/binutils-2.25/bfd/bfdio.d \
./nachos_initialCode/tools/binutils-2.25/bfd/bfdwin.d \
./nachos_initialCode/tools/binutils-2.25/bfd/binary.d \
./nachos_initialCode/tools/binutils-2.25/bfd/bout.d \
./nachos_initialCode/tools/binutils-2.25/bfd/cache.d \
./nachos_initialCode/tools/binutils-2.25/bfd/cf-i386lynx.d \
./nachos_initialCode/tools/binutils-2.25/bfd/cf-sparclynx.d \
./nachos_initialCode/tools/binutils-2.25/bfd/cisco-core.d \
./nachos_initialCode/tools/binutils-2.25/bfd/coff-alpha.d \
./nachos_initialCode/tools/binutils-2.25/bfd/coff-apollo.d \
./nachos_initialCode/tools/binutils-2.25/bfd/coff-arm.d \
./nachos_initialCode/tools/binutils-2.25/bfd/coff-aux.d \
./nachos_initialCode/tools/binutils-2.25/bfd/coff-go32.d \
./nachos_initialCode/tools/binutils-2.25/bfd/coff-h8300.d \
./nachos_initialCode/tools/binutils-2.25/bfd/coff-h8500.d \
./nachos_initialCode/tools/binutils-2.25/bfd/coff-i386.d \
./nachos_initialCode/tools/binutils-2.25/bfd/coff-i860.d \
./nachos_initialCode/tools/binutils-2.25/bfd/coff-i960.d \
./nachos_initialCode/tools/binutils-2.25/bfd/coff-ia64.d \
./nachos_initialCode/tools/binutils-2.25/bfd/coff-m68k.d \
./nachos_initialCode/tools/binutils-2.25/bfd/coff-m88k.d \
./nachos_initialCode/tools/binutils-2.25/bfd/coff-mcore.d \
./nachos_initialCode/tools/binutils-2.25/bfd/coff-mips.d \
./nachos_initialCode/tools/binutils-2.25/bfd/coff-ppc.d \
./nachos_initialCode/tools/binutils-2.25/bfd/coff-rs6000.d \
./nachos_initialCode/tools/binutils-2.25/bfd/coff-sh.d \
./nachos_initialCode/tools/binutils-2.25/bfd/coff-sparc.d \
./nachos_initialCode/tools/binutils-2.25/bfd/coff-stgo32.d \
./nachos_initialCode/tools/binutils-2.25/bfd/coff-svm68k.d \
./nachos_initialCode/tools/binutils-2.25/bfd/coff-tic30.d \
./nachos_initialCode/tools/binutils-2.25/bfd/coff-tic4x.d \
./nachos_initialCode/tools/binutils-2.25/bfd/coff-tic54x.d \
./nachos_initialCode/tools/binutils-2.25/bfd/coff-tic80.d \
./nachos_initialCode/tools/binutils-2.25/bfd/coff-u68k.d \
./nachos_initialCode/tools/binutils-2.25/bfd/coff-w65.d \
./nachos_initialCode/tools/binutils-2.25/bfd/coff-we32k.d \
./nachos_initialCode/tools/binutils-2.25/bfd/coff-x86_64.d \
./nachos_initialCode/tools/binutils-2.25/bfd/coff-z80.d \
./nachos_initialCode/tools/binutils-2.25/bfd/coff-z8k.d \
./nachos_initialCode/tools/binutils-2.25/bfd/coff64-rs6000.d \
./nachos_initialCode/tools/binutils-2.25/bfd/coffgen.d \
./nachos_initialCode/tools/binutils-2.25/bfd/cofflink.d \
./nachos_initialCode/tools/binutils-2.25/bfd/compress.d \
./nachos_initialCode/tools/binutils-2.25/bfd/corefile.d \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-aarch64.d \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-alpha.d \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-arc.d \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-arm.d \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-avr.d \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-bfin.d \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-cr16.d \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-cr16c.d \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-cris.d \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-crx.d \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-d10v.d \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-d30v.d \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-dlx.d \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-epiphany.d \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-fr30.d \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-frv.d \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-h8300.d \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-h8500.d \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-hppa.d \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-i370.d \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-i386.d \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-i860.d \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-i960.d \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-ia64-opc.d \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-ia64.d \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-ip2k.d \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-iq2000.d \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-k1om.d \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-l1om.d \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-lm32.d \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-m10200.d \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-m10300.d \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-m32c.d \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-m32r.d \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-m68hc11.d \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-m68hc12.d \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-m68k.d \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-m88k.d \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-m9s12x.d \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-m9s12xg.d \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-mcore.d \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-mep.d \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-metag.d \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-microblaze.d \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-mips.d \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-mmix.d \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-moxie.d \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-msp430.d \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-mt.d \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-nds32.d \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-nios2.d \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-ns32k.d \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-or1k.d \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-pdp11.d \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-pj.d \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-plugin.d \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-powerpc.d \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-rl78.d \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-rs6000.d \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-rx.d \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-s390.d \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-score.d \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-sh.d \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-sparc.d \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-spu.d \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-tic30.d \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-tic4x.d \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-tic54x.d \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-tic6x.d \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-tic80.d \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-tilegx.d \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-tilepro.d \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-v850.d \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-v850_rh850.d \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-vax.d \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-w65.d \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-we32k.d \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-xc16x.d \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-xgate.d \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-xstormy16.d \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-xtensa.d \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-z80.d \
./nachos_initialCode/tools/binutils-2.25/bfd/cpu-z8k.d \
./nachos_initialCode/tools/binutils-2.25/bfd/demo64.d \
./nachos_initialCode/tools/binutils-2.25/bfd/dwarf1.d \
./nachos_initialCode/tools/binutils-2.25/bfd/dwarf2.d \
./nachos_initialCode/tools/binutils-2.25/bfd/ecoff.d \
./nachos_initialCode/tools/binutils-2.25/bfd/ecofflink.d \
./nachos_initialCode/tools/binutils-2.25/bfd/elf-attrs.d \
./nachos_initialCode/tools/binutils-2.25/bfd/elf-eh-frame.d \
./nachos_initialCode/tools/binutils-2.25/bfd/elf-ifunc.d \
./nachos_initialCode/tools/binutils-2.25/bfd/elf-m10200.d \
./nachos_initialCode/tools/binutils-2.25/bfd/elf-m10300.d \
./nachos_initialCode/tools/binutils-2.25/bfd/elf-nacl.d \
./nachos_initialCode/tools/binutils-2.25/bfd/elf-s390-common.d \
./nachos_initialCode/tools/binutils-2.25/bfd/elf-strtab.d \
./nachos_initialCode/tools/binutils-2.25/bfd/elf-vxworks.d \
./nachos_initialCode/tools/binutils-2.25/bfd/elf.d \
./nachos_initialCode/tools/binutils-2.25/bfd/elf32-am33lin.d \
./nachos_initialCode/tools/binutils-2.25/bfd/elf32-arc.d \
./nachos_initialCode/tools/binutils-2.25/bfd/elf32-arm.d \
./nachos_initialCode/tools/binutils-2.25/bfd/elf32-avr.d \
./nachos_initialCode/tools/binutils-2.25/bfd/elf32-bfin.d \
./nachos_initialCode/tools/binutils-2.25/bfd/elf32-cr16.d \
./nachos_initialCode/tools/binutils-2.25/bfd/elf32-cr16c.d \
./nachos_initialCode/tools/binutils-2.25/bfd/elf32-cris.d \
./nachos_initialCode/tools/binutils-2.25/bfd/elf32-crx.d \
./nachos_initialCode/tools/binutils-2.25/bfd/elf32-d10v.d \
./nachos_initialCode/tools/binutils-2.25/bfd/elf32-d30v.d \
./nachos_initialCode/tools/binutils-2.25/bfd/elf32-dlx.d \
./nachos_initialCode/tools/binutils-2.25/bfd/elf32-epiphany.d \
./nachos_initialCode/tools/binutils-2.25/bfd/elf32-fr30.d \
./nachos_initialCode/tools/binutils-2.25/bfd/elf32-frv.d \
./nachos_initialCode/tools/binutils-2.25/bfd/elf32-gen.d \
./nachos_initialCode/tools/binutils-2.25/bfd/elf32-h8300.d \
./nachos_initialCode/tools/binutils-2.25/bfd/elf32-hppa.d \
./nachos_initialCode/tools/binutils-2.25/bfd/elf32-i370.d \
./nachos_initialCode/tools/binutils-2.25/bfd/elf32-i386.d \
./nachos_initialCode/tools/binutils-2.25/bfd/elf32-i860.d \
./nachos_initialCode/tools/binutils-2.25/bfd/elf32-i960.d \
./nachos_initialCode/tools/binutils-2.25/bfd/elf32-ip2k.d \
./nachos_initialCode/tools/binutils-2.25/bfd/elf32-iq2000.d \
./nachos_initialCode/tools/binutils-2.25/bfd/elf32-lm32.d \
./nachos_initialCode/tools/binutils-2.25/bfd/elf32-m32c.d \
./nachos_initialCode/tools/binutils-2.25/bfd/elf32-m32r.d \
./nachos_initialCode/tools/binutils-2.25/bfd/elf32-m68hc11.d \
./nachos_initialCode/tools/binutils-2.25/bfd/elf32-m68hc12.d \
./nachos_initialCode/tools/binutils-2.25/bfd/elf32-m68hc1x.d \
./nachos_initialCode/tools/binutils-2.25/bfd/elf32-m68k.d \
./nachos_initialCode/tools/binutils-2.25/bfd/elf32-m88k.d \
./nachos_initialCode/tools/binutils-2.25/bfd/elf32-mcore.d \
./nachos_initialCode/tools/binutils-2.25/bfd/elf32-mep.d \
./nachos_initialCode/tools/binutils-2.25/bfd/elf32-metag.d \
./nachos_initialCode/tools/binutils-2.25/bfd/elf32-microblaze.d \
./nachos_initialCode/tools/binutils-2.25/bfd/elf32-mips.d \
./nachos_initialCode/tools/binutils-2.25/bfd/elf32-moxie.d \
./nachos_initialCode/tools/binutils-2.25/bfd/elf32-msp430.d \
./nachos_initialCode/tools/binutils-2.25/bfd/elf32-mt.d \
./nachos_initialCode/tools/binutils-2.25/bfd/elf32-nds32.d \
./nachos_initialCode/tools/binutils-2.25/bfd/elf32-nios2.d \
./nachos_initialCode/tools/binutils-2.25/bfd/elf32-or1k.d \
./nachos_initialCode/tools/binutils-2.25/bfd/elf32-pj.d \
./nachos_initialCode/tools/binutils-2.25/bfd/elf32-ppc.d \
./nachos_initialCode/tools/binutils-2.25/bfd/elf32-rl78.d \
./nachos_initialCode/tools/binutils-2.25/bfd/elf32-rx.d \
./nachos_initialCode/tools/binutils-2.25/bfd/elf32-s390.d \
./nachos_initialCode/tools/binutils-2.25/bfd/elf32-score.d \
./nachos_initialCode/tools/binutils-2.25/bfd/elf32-score7.d \
./nachos_initialCode/tools/binutils-2.25/bfd/elf32-sh-symbian.d \
./nachos_initialCode/tools/binutils-2.25/bfd/elf32-sh.d \
./nachos_initialCode/tools/binutils-2.25/bfd/elf32-sh64-com.d \
./nachos_initialCode/tools/binutils-2.25/bfd/elf32-sh64.d \
./nachos_initialCode/tools/binutils-2.25/bfd/elf32-sparc.d \
./nachos_initialCode/tools/binutils-2.25/bfd/elf32-spu.d \
./nachos_initialCode/tools/binutils-2.25/bfd/elf32-tic6x.d \
./nachos_initialCode/tools/binutils-2.25/bfd/elf32-tilegx.d \
./nachos_initialCode/tools/binutils-2.25/bfd/elf32-tilepro.d \
./nachos_initialCode/tools/binutils-2.25/bfd/elf32-v850.d \
./nachos_initialCode/tools/binutils-2.25/bfd/elf32-vax.d \
./nachos_initialCode/tools/binutils-2.25/bfd/elf32-xc16x.d \
./nachos_initialCode/tools/binutils-2.25/bfd/elf32-xgate.d \
./nachos_initialCode/tools/binutils-2.25/bfd/elf32-xstormy16.d \
./nachos_initialCode/tools/binutils-2.25/bfd/elf32-xtensa.d \
./nachos_initialCode/tools/binutils-2.25/bfd/elf32.d \
./nachos_initialCode/tools/binutils-2.25/bfd/elf64-alpha.d \
./nachos_initialCode/tools/binutils-2.25/bfd/elf64-gen.d \
./nachos_initialCode/tools/binutils-2.25/bfd/elf64-hppa.d \
./nachos_initialCode/tools/binutils-2.25/bfd/elf64-ia64-vms.d \
./nachos_initialCode/tools/binutils-2.25/bfd/elf64-mips.d \
./nachos_initialCode/tools/binutils-2.25/bfd/elf64-mmix.d \
./nachos_initialCode/tools/binutils-2.25/bfd/elf64-ppc.d \
./nachos_initialCode/tools/binutils-2.25/bfd/elf64-s390.d \
./nachos_initialCode/tools/binutils-2.25/bfd/elf64-sh64.d \
./nachos_initialCode/tools/binutils-2.25/bfd/elf64-sparc.d \
./nachos_initialCode/tools/binutils-2.25/bfd/elf64-tilegx.d \
./nachos_initialCode/tools/binutils-2.25/bfd/elf64-x86-64.d \
./nachos_initialCode/tools/binutils-2.25/bfd/elf64.d \
./nachos_initialCode/tools/binutils-2.25/bfd/elflink.d \
./nachos_initialCode/tools/binutils-2.25/bfd/elfn32-mips.d \
./nachos_initialCode/tools/binutils-2.25/bfd/elfnn-aarch64.d \
./nachos_initialCode/tools/binutils-2.25/bfd/elfnn-ia64.d \
./nachos_initialCode/tools/binutils-2.25/bfd/elfxx-aarch64.d \
./nachos_initialCode/tools/binutils-2.25/bfd/elfxx-ia64.d \
./nachos_initialCode/tools/binutils-2.25/bfd/elfxx-mips.d \
./nachos_initialCode/tools/binutils-2.25/bfd/elfxx-sparc.d \
./nachos_initialCode/tools/binutils-2.25/bfd/elfxx-tilegx.d \
./nachos_initialCode/tools/binutils-2.25/bfd/epoc-pe-arm.d \
./nachos_initialCode/tools/binutils-2.25/bfd/epoc-pei-arm.d \
./nachos_initialCode/tools/binutils-2.25/bfd/format.d \
./nachos_initialCode/tools/binutils-2.25/bfd/gen-aout.d \
./nachos_initialCode/tools/binutils-2.25/bfd/hash.d \
./nachos_initialCode/tools/binutils-2.25/bfd/host-aout.d \
./nachos_initialCode/tools/binutils-2.25/bfd/hp300bsd.d \
./nachos_initialCode/tools/binutils-2.25/bfd/hp300hpux.d \
./nachos_initialCode/tools/binutils-2.25/bfd/hppabsd-core.d \
./nachos_initialCode/tools/binutils-2.25/bfd/hpux-core.d \
./nachos_initialCode/tools/binutils-2.25/bfd/i386aout.d \
./nachos_initialCode/tools/binutils-2.25/bfd/i386bsd.d \
./nachos_initialCode/tools/binutils-2.25/bfd/i386dynix.d \
./nachos_initialCode/tools/binutils-2.25/bfd/i386freebsd.d \
./nachos_initialCode/tools/binutils-2.25/bfd/i386linux.d \
./nachos_initialCode/tools/binutils-2.25/bfd/i386lynx.d \
./nachos_initialCode/tools/binutils-2.25/bfd/i386mach3.d \
./nachos_initialCode/tools/binutils-2.25/bfd/i386msdos.d \
./nachos_initialCode/tools/binutils-2.25/bfd/i386netbsd.d \
./nachos_initialCode/tools/binutils-2.25/bfd/i386os9k.d \
./nachos_initialCode/tools/binutils-2.25/bfd/ieee.d \
./nachos_initialCode/tools/binutils-2.25/bfd/ihex.d \
./nachos_initialCode/tools/binutils-2.25/bfd/init.d \
./nachos_initialCode/tools/binutils-2.25/bfd/irix-core.d \
./nachos_initialCode/tools/binutils-2.25/bfd/libbfd.d \
./nachos_initialCode/tools/binutils-2.25/bfd/linker.d \
./nachos_initialCode/tools/binutils-2.25/bfd/lynx-core.d \
./nachos_initialCode/tools/binutils-2.25/bfd/m68k4knetbsd.d \
./nachos_initialCode/tools/binutils-2.25/bfd/m68klinux.d \
./nachos_initialCode/tools/binutils-2.25/bfd/m68knetbsd.d \
./nachos_initialCode/tools/binutils-2.25/bfd/m88kmach3.d \
./nachos_initialCode/tools/binutils-2.25/bfd/m88kopenbsd.d \
./nachos_initialCode/tools/binutils-2.25/bfd/mach-o-i386.d \
./nachos_initialCode/tools/binutils-2.25/bfd/mach-o-target.d \
./nachos_initialCode/tools/binutils-2.25/bfd/mach-o-x86-64.d \
./nachos_initialCode/tools/binutils-2.25/bfd/mach-o.d \
./nachos_initialCode/tools/binutils-2.25/bfd/merge.d \
./nachos_initialCode/tools/binutils-2.25/bfd/mipsbsd.d \
./nachos_initialCode/tools/binutils-2.25/bfd/mmo.d \
./nachos_initialCode/tools/binutils-2.25/bfd/netbsd-core.d \
./nachos_initialCode/tools/binutils-2.25/bfd/newsos3.d \
./nachos_initialCode/tools/binutils-2.25/bfd/nlm.d \
./nachos_initialCode/tools/binutils-2.25/bfd/nlm32-alpha.d \
./nachos_initialCode/tools/binutils-2.25/bfd/nlm32-i386.d \
./nachos_initialCode/tools/binutils-2.25/bfd/nlm32-ppc.d \
./nachos_initialCode/tools/binutils-2.25/bfd/nlm32-sparc.d \
./nachos_initialCode/tools/binutils-2.25/bfd/nlm32.d \
./nachos_initialCode/tools/binutils-2.25/bfd/nlm64.d \
./nachos_initialCode/tools/binutils-2.25/bfd/ns32knetbsd.d \
./nachos_initialCode/tools/binutils-2.25/bfd/oasys.d \
./nachos_initialCode/tools/binutils-2.25/bfd/opncls.d \
./nachos_initialCode/tools/binutils-2.25/bfd/osf-core.d \
./nachos_initialCode/tools/binutils-2.25/bfd/pc532-mach.d \
./nachos_initialCode/tools/binutils-2.25/bfd/pdp11.d \
./nachos_initialCode/tools/binutils-2.25/bfd/pe-arm-wince.d \
./nachos_initialCode/tools/binutils-2.25/bfd/pe-arm.d \
./nachos_initialCode/tools/binutils-2.25/bfd/pe-i386.d \
./nachos_initialCode/tools/binutils-2.25/bfd/pe-mcore.d \
./nachos_initialCode/tools/binutils-2.25/bfd/pe-mips.d \
./nachos_initialCode/tools/binutils-2.25/bfd/pe-ppc.d \
./nachos_initialCode/tools/binutils-2.25/bfd/pe-sh.d \
./nachos_initialCode/tools/binutils-2.25/bfd/pe-x86_64.d \
./nachos_initialCode/tools/binutils-2.25/bfd/peXXigen.d \
./nachos_initialCode/tools/binutils-2.25/bfd/pef.d \
./nachos_initialCode/tools/binutils-2.25/bfd/pei-arm-wince.d \
./nachos_initialCode/tools/binutils-2.25/bfd/pei-arm.d \
./nachos_initialCode/tools/binutils-2.25/bfd/pei-i386.d \
./nachos_initialCode/tools/binutils-2.25/bfd/pei-ia64.d \
./nachos_initialCode/tools/binutils-2.25/bfd/pei-mcore.d \
./nachos_initialCode/tools/binutils-2.25/bfd/pei-mips.d \
./nachos_initialCode/tools/binutils-2.25/bfd/pei-ppc.d \
./nachos_initialCode/tools/binutils-2.25/bfd/pei-sh.d \
./nachos_initialCode/tools/binutils-2.25/bfd/pei-x86_64.d \
./nachos_initialCode/tools/binutils-2.25/bfd/plugin.d \
./nachos_initialCode/tools/binutils-2.25/bfd/ppcboot.d \
./nachos_initialCode/tools/binutils-2.25/bfd/ptrace-core.d \
./nachos_initialCode/tools/binutils-2.25/bfd/reloc.d \
./nachos_initialCode/tools/binutils-2.25/bfd/reloc16.d \
./nachos_initialCode/tools/binutils-2.25/bfd/riscix.d \
./nachos_initialCode/tools/binutils-2.25/bfd/rs6000-core.d \
./nachos_initialCode/tools/binutils-2.25/bfd/sco5-core.d \
./nachos_initialCode/tools/binutils-2.25/bfd/section.d \
./nachos_initialCode/tools/binutils-2.25/bfd/simple.d \
./nachos_initialCode/tools/binutils-2.25/bfd/som.d \
./nachos_initialCode/tools/binutils-2.25/bfd/sparclinux.d \
./nachos_initialCode/tools/binutils-2.25/bfd/sparclynx.d \
./nachos_initialCode/tools/binutils-2.25/bfd/sparcnetbsd.d \
./nachos_initialCode/tools/binutils-2.25/bfd/srec.d \
./nachos_initialCode/tools/binutils-2.25/bfd/stab-syms.d \
./nachos_initialCode/tools/binutils-2.25/bfd/stabs.d \
./nachos_initialCode/tools/binutils-2.25/bfd/sunos.d \
./nachos_initialCode/tools/binutils-2.25/bfd/syms.d \
./nachos_initialCode/tools/binutils-2.25/bfd/targets.d \
./nachos_initialCode/tools/binutils-2.25/bfd/tekhex.d \
./nachos_initialCode/tools/binutils-2.25/bfd/trad-core.d \
./nachos_initialCode/tools/binutils-2.25/bfd/vax1knetbsd.d \
./nachos_initialCode/tools/binutils-2.25/bfd/vaxbsd.d \
./nachos_initialCode/tools/binutils-2.25/bfd/vaxnetbsd.d \
./nachos_initialCode/tools/binutils-2.25/bfd/verilog.d \
./nachos_initialCode/tools/binutils-2.25/bfd/versados.d \
./nachos_initialCode/tools/binutils-2.25/bfd/vms-alpha.d \
./nachos_initialCode/tools/binutils-2.25/bfd/vms-lib.d \
./nachos_initialCode/tools/binutils-2.25/bfd/vms-misc.d \
./nachos_initialCode/tools/binutils-2.25/bfd/xcofflink.d \
./nachos_initialCode/tools/binutils-2.25/bfd/xsym.d \
./nachos_initialCode/tools/binutils-2.25/bfd/xtensa-isa.d \
./nachos_initialCode/tools/binutils-2.25/bfd/xtensa-modules.d 


# Each subdirectory must supply rules for building sources it contributes
nachos_initialCode/tools/binutils-2.25/bfd/%.o: ../nachos_initialCode/tools/binutils-2.25/bfd/%.c
	@echo 'Building file: $<'
	@echo 'Invoking: Cross GCC Compiler'
	gcc -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


