################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/Wcast-qual-1.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/Wconversion-real.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/Wfloat-conversion.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/Wint-to-pointer-cast-1.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/Wint-to-pointer-cast-2.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/Wint-to-pointer-cast-3.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/Wmemset-transposed-args1.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/Wmemset-transposed-args2.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/Wpointer-arith-1.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/Wsequence-point-1.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/Wsizeof-pointer-memaccess1.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/Wsizeof-pointer-memaccess2.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/Wunused-local-typedefs.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/Wunused-var-1.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/Wunused-var-10.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/Wunused-var-11.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/Wunused-var-12.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/Wunused-var-13.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/Wunused-var-14.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/Wunused-var-2.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/Wunused-var-3.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/Wunused-var-4.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/Wunused-var-5.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/Wunused-var-6.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/Wunused-var-7.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/Wunused-var-8.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/Wunused-var-9.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/Wvarargs-2.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/Wvarargs.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/abi-bf.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/array-lit.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/asmgoto-1.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/asmgoto-2.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/asmgoto-3.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/asmgoto-4.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/attr-used-2.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/attr-used.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/attributes-1.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/builtin-offsetof.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/convert-vec-1.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/cxxbitfields-3.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/cxxbitfields-6.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/fmax-errors.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/fold-bitand-4.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/fold-divmul-1.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/init-vec-1.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/int128-1.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/int128-2.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/int128-types-1.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/opaque-vector.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr20000.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr20318.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr28656.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr33193.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr33763.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr36282-1.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr36282-2.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr36282-3.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr36282-4.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr36513-2.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr36513.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr37743.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr41779.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr41935.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr42674.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr43690.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr43772.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr43942.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr44832.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr46562-2.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr46562.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr48418.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr51294.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr51712.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr51768.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr52177.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr52181.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr53633.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr54486.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr54988.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr55619.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr55771.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr56302.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr56493.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr56566.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr56607.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr57793.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr58346-1.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr58346-2.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr58346-3.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr59032.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr59037.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr59223.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr59280.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr60101.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr60689.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr61553.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr61741.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/raw-string-1.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/raw-string-10.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/raw-string-11.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/raw-string-12.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/raw-string-13.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/raw-string-14.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/raw-string-15.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/raw-string-16.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/raw-string-17.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/raw-string-18.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/raw-string-19.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/raw-string-2.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/raw-string-3.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/raw-string-4.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/raw-string-5.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/raw-string-6.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/raw-string-7.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/raw-string-8.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/raw-string-9.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/restrict-1.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/restrict-2.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/restrict-4.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/rotate-1.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/rotate-1a.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/rotate-2.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/rotate-2a.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/rotate-3.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/rotate-3a.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/rotate-4.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/rotate-4a.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/rotate-5.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/scal-to-vec1.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/scal-to-vec2.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/transparent-union-1.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/uninit-17.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/uninit-D-O0.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/uninit-D.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/uninit-E-O0.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/uninit-E.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/uninit-F-O0.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/uninit-F.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/uninit-G-O0.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/uninit-G.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/uninit-pr51010.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/vector-1.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/vector-2.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/vector-3.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/vector-4.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/vector-compare-1.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/vector-compare-2.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/vector-compare-3.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/vector-init-1.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/vector-init-2.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/vector-scalar-2.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/vector-scalar.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/vector-shift.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/vector-shift1.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/vector-shift3.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/vector-subscript-1.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/vector-subscript-2.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/vector-subscript-3.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/vla-1.c \
../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/warn-ommitted-condop.c 

OBJS += \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/Wcast-qual-1.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/Wconversion-real.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/Wfloat-conversion.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/Wint-to-pointer-cast-1.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/Wint-to-pointer-cast-2.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/Wint-to-pointer-cast-3.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/Wmemset-transposed-args1.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/Wmemset-transposed-args2.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/Wpointer-arith-1.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/Wsequence-point-1.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/Wsizeof-pointer-memaccess1.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/Wsizeof-pointer-memaccess2.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/Wunused-local-typedefs.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/Wunused-var-1.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/Wunused-var-10.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/Wunused-var-11.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/Wunused-var-12.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/Wunused-var-13.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/Wunused-var-14.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/Wunused-var-2.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/Wunused-var-3.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/Wunused-var-4.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/Wunused-var-5.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/Wunused-var-6.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/Wunused-var-7.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/Wunused-var-8.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/Wunused-var-9.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/Wvarargs-2.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/Wvarargs.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/abi-bf.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/array-lit.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/asmgoto-1.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/asmgoto-2.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/asmgoto-3.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/asmgoto-4.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/attr-used-2.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/attr-used.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/attributes-1.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/builtin-offsetof.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/convert-vec-1.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/cxxbitfields-3.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/cxxbitfields-6.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/fmax-errors.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/fold-bitand-4.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/fold-divmul-1.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/init-vec-1.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/int128-1.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/int128-2.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/int128-types-1.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/opaque-vector.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr20000.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr20318.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr28656.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr33193.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr33763.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr36282-1.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr36282-2.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr36282-3.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr36282-4.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr36513-2.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr36513.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr37743.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr41779.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr41935.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr42674.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr43690.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr43772.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr43942.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr44832.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr46562-2.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr46562.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr48418.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr51294.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr51712.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr51768.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr52177.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr52181.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr53633.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr54486.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr54988.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr55619.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr55771.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr56302.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr56493.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr56566.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr56607.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr57793.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr58346-1.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr58346-2.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr58346-3.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr59032.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr59037.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr59223.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr59280.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr60101.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr60689.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr61553.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr61741.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/raw-string-1.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/raw-string-10.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/raw-string-11.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/raw-string-12.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/raw-string-13.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/raw-string-14.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/raw-string-15.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/raw-string-16.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/raw-string-17.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/raw-string-18.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/raw-string-19.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/raw-string-2.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/raw-string-3.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/raw-string-4.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/raw-string-5.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/raw-string-6.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/raw-string-7.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/raw-string-8.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/raw-string-9.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/restrict-1.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/restrict-2.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/restrict-4.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/rotate-1.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/rotate-1a.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/rotate-2.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/rotate-2a.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/rotate-3.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/rotate-3a.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/rotate-4.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/rotate-4a.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/rotate-5.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/scal-to-vec1.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/scal-to-vec2.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/transparent-union-1.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/uninit-17.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/uninit-D-O0.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/uninit-D.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/uninit-E-O0.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/uninit-E.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/uninit-F-O0.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/uninit-F.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/uninit-G-O0.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/uninit-G.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/uninit-pr51010.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/vector-1.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/vector-2.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/vector-3.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/vector-4.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/vector-compare-1.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/vector-compare-2.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/vector-compare-3.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/vector-init-1.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/vector-init-2.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/vector-scalar-2.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/vector-scalar.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/vector-shift.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/vector-shift1.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/vector-shift3.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/vector-subscript-1.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/vector-subscript-2.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/vector-subscript-3.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/vla-1.o \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/warn-ommitted-condop.o 

C_DEPS += \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/Wcast-qual-1.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/Wconversion-real.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/Wfloat-conversion.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/Wint-to-pointer-cast-1.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/Wint-to-pointer-cast-2.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/Wint-to-pointer-cast-3.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/Wmemset-transposed-args1.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/Wmemset-transposed-args2.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/Wpointer-arith-1.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/Wsequence-point-1.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/Wsizeof-pointer-memaccess1.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/Wsizeof-pointer-memaccess2.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/Wunused-local-typedefs.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/Wunused-var-1.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/Wunused-var-10.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/Wunused-var-11.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/Wunused-var-12.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/Wunused-var-13.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/Wunused-var-14.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/Wunused-var-2.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/Wunused-var-3.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/Wunused-var-4.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/Wunused-var-5.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/Wunused-var-6.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/Wunused-var-7.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/Wunused-var-8.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/Wunused-var-9.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/Wvarargs-2.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/Wvarargs.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/abi-bf.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/array-lit.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/asmgoto-1.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/asmgoto-2.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/asmgoto-3.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/asmgoto-4.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/attr-used-2.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/attr-used.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/attributes-1.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/builtin-offsetof.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/convert-vec-1.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/cxxbitfields-3.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/cxxbitfields-6.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/fmax-errors.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/fold-bitand-4.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/fold-divmul-1.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/init-vec-1.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/int128-1.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/int128-2.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/int128-types-1.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/opaque-vector.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr20000.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr20318.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr28656.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr33193.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr33763.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr36282-1.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr36282-2.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr36282-3.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr36282-4.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr36513-2.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr36513.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr37743.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr41779.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr41935.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr42674.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr43690.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr43772.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr43942.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr44832.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr46562-2.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr46562.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr48418.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr51294.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr51712.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr51768.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr52177.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr52181.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr53633.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr54486.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr54988.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr55619.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr55771.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr56302.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr56493.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr56566.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr56607.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr57793.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr58346-1.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr58346-2.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr58346-3.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr59032.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr59037.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr59223.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr59280.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr60101.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr60689.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr61553.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/pr61741.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/raw-string-1.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/raw-string-10.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/raw-string-11.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/raw-string-12.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/raw-string-13.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/raw-string-14.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/raw-string-15.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/raw-string-16.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/raw-string-17.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/raw-string-18.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/raw-string-19.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/raw-string-2.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/raw-string-3.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/raw-string-4.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/raw-string-5.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/raw-string-6.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/raw-string-7.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/raw-string-8.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/raw-string-9.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/restrict-1.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/restrict-2.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/restrict-4.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/rotate-1.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/rotate-1a.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/rotate-2.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/rotate-2a.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/rotate-3.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/rotate-3a.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/rotate-4.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/rotate-4a.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/rotate-5.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/scal-to-vec1.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/scal-to-vec2.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/transparent-union-1.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/uninit-17.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/uninit-D-O0.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/uninit-D.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/uninit-E-O0.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/uninit-E.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/uninit-F-O0.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/uninit-F.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/uninit-G-O0.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/uninit-G.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/uninit-pr51010.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/vector-1.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/vector-2.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/vector-3.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/vector-4.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/vector-compare-1.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/vector-compare-2.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/vector-compare-3.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/vector-init-1.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/vector-init-2.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/vector-scalar-2.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/vector-scalar.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/vector-shift.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/vector-shift1.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/vector-shift3.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/vector-subscript-1.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/vector-subscript-2.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/vector-subscript-3.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/vla-1.d \
./nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/warn-ommitted-condop.d 


# Each subdirectory must supply rules for building sources it contributes
nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/%.o: ../nachos_initialCode/tools/gcc-4.9-4.9.2/src/gcc/testsuite/c-c++-common/%.c
	@echo 'Building file: $<'
	@echo 'Invoking: Cross GCC Compiler'
	gcc -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


