################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../nachos_initialCode/tools/binutils-2.25/libiberty/_doprnt.c \
../nachos_initialCode/tools/binutils-2.25/libiberty/alloca.c \
../nachos_initialCode/tools/binutils-2.25/libiberty/argv.c \
../nachos_initialCode/tools/binutils-2.25/libiberty/asprintf.c \
../nachos_initialCode/tools/binutils-2.25/libiberty/atexit.c \
../nachos_initialCode/tools/binutils-2.25/libiberty/basename.c \
../nachos_initialCode/tools/binutils-2.25/libiberty/bcmp.c \
../nachos_initialCode/tools/binutils-2.25/libiberty/bcopy.c \
../nachos_initialCode/tools/binutils-2.25/libiberty/bsearch.c \
../nachos_initialCode/tools/binutils-2.25/libiberty/bzero.c \
../nachos_initialCode/tools/binutils-2.25/libiberty/calloc.c \
../nachos_initialCode/tools/binutils-2.25/libiberty/choose-temp.c \
../nachos_initialCode/tools/binutils-2.25/libiberty/clock.c \
../nachos_initialCode/tools/binutils-2.25/libiberty/concat.c \
../nachos_initialCode/tools/binutils-2.25/libiberty/copysign.c \
../nachos_initialCode/tools/binutils-2.25/libiberty/cp-demangle.c \
../nachos_initialCode/tools/binutils-2.25/libiberty/cp-demint.c \
../nachos_initialCode/tools/binutils-2.25/libiberty/cplus-dem.c \
../nachos_initialCode/tools/binutils-2.25/libiberty/crc32.c \
../nachos_initialCode/tools/binutils-2.25/libiberty/d-demangle.c \
../nachos_initialCode/tools/binutils-2.25/libiberty/dwarfnames.c \
../nachos_initialCode/tools/binutils-2.25/libiberty/dyn-string.c \
../nachos_initialCode/tools/binutils-2.25/libiberty/fdmatch.c \
../nachos_initialCode/tools/binutils-2.25/libiberty/ffs.c \
../nachos_initialCode/tools/binutils-2.25/libiberty/fibheap.c \
../nachos_initialCode/tools/binutils-2.25/libiberty/filename_cmp.c \
../nachos_initialCode/tools/binutils-2.25/libiberty/floatformat.c \
../nachos_initialCode/tools/binutils-2.25/libiberty/fnmatch.c \
../nachos_initialCode/tools/binutils-2.25/libiberty/fopen_unlocked.c \
../nachos_initialCode/tools/binutils-2.25/libiberty/getcwd.c \
../nachos_initialCode/tools/binutils-2.25/libiberty/getopt.c \
../nachos_initialCode/tools/binutils-2.25/libiberty/getopt1.c \
../nachos_initialCode/tools/binutils-2.25/libiberty/getpagesize.c \
../nachos_initialCode/tools/binutils-2.25/libiberty/getpwd.c \
../nachos_initialCode/tools/binutils-2.25/libiberty/getruntime.c \
../nachos_initialCode/tools/binutils-2.25/libiberty/gettimeofday.c \
../nachos_initialCode/tools/binutils-2.25/libiberty/hashtab.c \
../nachos_initialCode/tools/binutils-2.25/libiberty/hex.c \
../nachos_initialCode/tools/binutils-2.25/libiberty/index.c \
../nachos_initialCode/tools/binutils-2.25/libiberty/insque.c \
../nachos_initialCode/tools/binutils-2.25/libiberty/lbasename.c \
../nachos_initialCode/tools/binutils-2.25/libiberty/lrealpath.c \
../nachos_initialCode/tools/binutils-2.25/libiberty/make-relative-prefix.c \
../nachos_initialCode/tools/binutils-2.25/libiberty/make-temp-file.c \
../nachos_initialCode/tools/binutils-2.25/libiberty/md5.c \
../nachos_initialCode/tools/binutils-2.25/libiberty/memchr.c \
../nachos_initialCode/tools/binutils-2.25/libiberty/memcmp.c \
../nachos_initialCode/tools/binutils-2.25/libiberty/memcpy.c \
../nachos_initialCode/tools/binutils-2.25/libiberty/memmem.c \
../nachos_initialCode/tools/binutils-2.25/libiberty/memmove.c \
../nachos_initialCode/tools/binutils-2.25/libiberty/mempcpy.c \
../nachos_initialCode/tools/binutils-2.25/libiberty/memset.c \
../nachos_initialCode/tools/binutils-2.25/libiberty/mkstemps.c \
../nachos_initialCode/tools/binutils-2.25/libiberty/msdos.c \
../nachos_initialCode/tools/binutils-2.25/libiberty/objalloc.c \
../nachos_initialCode/tools/binutils-2.25/libiberty/obstack.c \
../nachos_initialCode/tools/binutils-2.25/libiberty/partition.c \
../nachos_initialCode/tools/binutils-2.25/libiberty/pex-common.c \
../nachos_initialCode/tools/binutils-2.25/libiberty/pex-djgpp.c \
../nachos_initialCode/tools/binutils-2.25/libiberty/pex-msdos.c \
../nachos_initialCode/tools/binutils-2.25/libiberty/pex-one.c \
../nachos_initialCode/tools/binutils-2.25/libiberty/pex-unix.c \
../nachos_initialCode/tools/binutils-2.25/libiberty/pex-win32.c \
../nachos_initialCode/tools/binutils-2.25/libiberty/pexecute.c \
../nachos_initialCode/tools/binutils-2.25/libiberty/physmem.c \
../nachos_initialCode/tools/binutils-2.25/libiberty/putenv.c \
../nachos_initialCode/tools/binutils-2.25/libiberty/random.c \
../nachos_initialCode/tools/binutils-2.25/libiberty/regex.c \
../nachos_initialCode/tools/binutils-2.25/libiberty/rename.c \
../nachos_initialCode/tools/binutils-2.25/libiberty/rindex.c \
../nachos_initialCode/tools/binutils-2.25/libiberty/safe-ctype.c \
../nachos_initialCode/tools/binutils-2.25/libiberty/setenv.c \
../nachos_initialCode/tools/binutils-2.25/libiberty/setproctitle.c \
../nachos_initialCode/tools/binutils-2.25/libiberty/sha1.c \
../nachos_initialCode/tools/binutils-2.25/libiberty/sigsetmask.c \
../nachos_initialCode/tools/binutils-2.25/libiberty/simple-object-coff.c \
../nachos_initialCode/tools/binutils-2.25/libiberty/simple-object-elf.c \
../nachos_initialCode/tools/binutils-2.25/libiberty/simple-object-mach-o.c \
../nachos_initialCode/tools/binutils-2.25/libiberty/simple-object-xcoff.c \
../nachos_initialCode/tools/binutils-2.25/libiberty/simple-object.c \
../nachos_initialCode/tools/binutils-2.25/libiberty/snprintf.c \
../nachos_initialCode/tools/binutils-2.25/libiberty/sort.c \
../nachos_initialCode/tools/binutils-2.25/libiberty/spaces.c \
../nachos_initialCode/tools/binutils-2.25/libiberty/splay-tree.c \
../nachos_initialCode/tools/binutils-2.25/libiberty/stack-limit.c \
../nachos_initialCode/tools/binutils-2.25/libiberty/stpcpy.c \
../nachos_initialCode/tools/binutils-2.25/libiberty/stpncpy.c \
../nachos_initialCode/tools/binutils-2.25/libiberty/strcasecmp.c \
../nachos_initialCode/tools/binutils-2.25/libiberty/strchr.c \
../nachos_initialCode/tools/binutils-2.25/libiberty/strdup.c \
../nachos_initialCode/tools/binutils-2.25/libiberty/strerror.c \
../nachos_initialCode/tools/binutils-2.25/libiberty/strncasecmp.c \
../nachos_initialCode/tools/binutils-2.25/libiberty/strncmp.c \
../nachos_initialCode/tools/binutils-2.25/libiberty/strndup.c \
../nachos_initialCode/tools/binutils-2.25/libiberty/strnlen.c \
../nachos_initialCode/tools/binutils-2.25/libiberty/strrchr.c \
../nachos_initialCode/tools/binutils-2.25/libiberty/strsignal.c \
../nachos_initialCode/tools/binutils-2.25/libiberty/strstr.c \
../nachos_initialCode/tools/binutils-2.25/libiberty/strtod.c \
../nachos_initialCode/tools/binutils-2.25/libiberty/strtol.c \
../nachos_initialCode/tools/binutils-2.25/libiberty/strtoul.c \
../nachos_initialCode/tools/binutils-2.25/libiberty/strverscmp.c \
../nachos_initialCode/tools/binutils-2.25/libiberty/timeval-utils.c \
../nachos_initialCode/tools/binutils-2.25/libiberty/tmpnam.c \
../nachos_initialCode/tools/binutils-2.25/libiberty/unlink-if-ordinary.c \
../nachos_initialCode/tools/binutils-2.25/libiberty/vasprintf.c \
../nachos_initialCode/tools/binutils-2.25/libiberty/vfork.c \
../nachos_initialCode/tools/binutils-2.25/libiberty/vfprintf.c \
../nachos_initialCode/tools/binutils-2.25/libiberty/vprintf.c \
../nachos_initialCode/tools/binutils-2.25/libiberty/vsnprintf.c \
../nachos_initialCode/tools/binutils-2.25/libiberty/vsprintf.c \
../nachos_initialCode/tools/binutils-2.25/libiberty/waitpid.c \
../nachos_initialCode/tools/binutils-2.25/libiberty/xatexit.c \
../nachos_initialCode/tools/binutils-2.25/libiberty/xexit.c \
../nachos_initialCode/tools/binutils-2.25/libiberty/xmalloc.c \
../nachos_initialCode/tools/binutils-2.25/libiberty/xmemdup.c \
../nachos_initialCode/tools/binutils-2.25/libiberty/xstrdup.c \
../nachos_initialCode/tools/binutils-2.25/libiberty/xstrerror.c \
../nachos_initialCode/tools/binutils-2.25/libiberty/xstrndup.c 

OBJS += \
./nachos_initialCode/tools/binutils-2.25/libiberty/_doprnt.o \
./nachos_initialCode/tools/binutils-2.25/libiberty/alloca.o \
./nachos_initialCode/tools/binutils-2.25/libiberty/argv.o \
./nachos_initialCode/tools/binutils-2.25/libiberty/asprintf.o \
./nachos_initialCode/tools/binutils-2.25/libiberty/atexit.o \
./nachos_initialCode/tools/binutils-2.25/libiberty/basename.o \
./nachos_initialCode/tools/binutils-2.25/libiberty/bcmp.o \
./nachos_initialCode/tools/binutils-2.25/libiberty/bcopy.o \
./nachos_initialCode/tools/binutils-2.25/libiberty/bsearch.o \
./nachos_initialCode/tools/binutils-2.25/libiberty/bzero.o \
./nachos_initialCode/tools/binutils-2.25/libiberty/calloc.o \
./nachos_initialCode/tools/binutils-2.25/libiberty/choose-temp.o \
./nachos_initialCode/tools/binutils-2.25/libiberty/clock.o \
./nachos_initialCode/tools/binutils-2.25/libiberty/concat.o \
./nachos_initialCode/tools/binutils-2.25/libiberty/copysign.o \
./nachos_initialCode/tools/binutils-2.25/libiberty/cp-demangle.o \
./nachos_initialCode/tools/binutils-2.25/libiberty/cp-demint.o \
./nachos_initialCode/tools/binutils-2.25/libiberty/cplus-dem.o \
./nachos_initialCode/tools/binutils-2.25/libiberty/crc32.o \
./nachos_initialCode/tools/binutils-2.25/libiberty/d-demangle.o \
./nachos_initialCode/tools/binutils-2.25/libiberty/dwarfnames.o \
./nachos_initialCode/tools/binutils-2.25/libiberty/dyn-string.o \
./nachos_initialCode/tools/binutils-2.25/libiberty/fdmatch.o \
./nachos_initialCode/tools/binutils-2.25/libiberty/ffs.o \
./nachos_initialCode/tools/binutils-2.25/libiberty/fibheap.o \
./nachos_initialCode/tools/binutils-2.25/libiberty/filename_cmp.o \
./nachos_initialCode/tools/binutils-2.25/libiberty/floatformat.o \
./nachos_initialCode/tools/binutils-2.25/libiberty/fnmatch.o \
./nachos_initialCode/tools/binutils-2.25/libiberty/fopen_unlocked.o \
./nachos_initialCode/tools/binutils-2.25/libiberty/getcwd.o \
./nachos_initialCode/tools/binutils-2.25/libiberty/getopt.o \
./nachos_initialCode/tools/binutils-2.25/libiberty/getopt1.o \
./nachos_initialCode/tools/binutils-2.25/libiberty/getpagesize.o \
./nachos_initialCode/tools/binutils-2.25/libiberty/getpwd.o \
./nachos_initialCode/tools/binutils-2.25/libiberty/getruntime.o \
./nachos_initialCode/tools/binutils-2.25/libiberty/gettimeofday.o \
./nachos_initialCode/tools/binutils-2.25/libiberty/hashtab.o \
./nachos_initialCode/tools/binutils-2.25/libiberty/hex.o \
./nachos_initialCode/tools/binutils-2.25/libiberty/index.o \
./nachos_initialCode/tools/binutils-2.25/libiberty/insque.o \
./nachos_initialCode/tools/binutils-2.25/libiberty/lbasename.o \
./nachos_initialCode/tools/binutils-2.25/libiberty/lrealpath.o \
./nachos_initialCode/tools/binutils-2.25/libiberty/make-relative-prefix.o \
./nachos_initialCode/tools/binutils-2.25/libiberty/make-temp-file.o \
./nachos_initialCode/tools/binutils-2.25/libiberty/md5.o \
./nachos_initialCode/tools/binutils-2.25/libiberty/memchr.o \
./nachos_initialCode/tools/binutils-2.25/libiberty/memcmp.o \
./nachos_initialCode/tools/binutils-2.25/libiberty/memcpy.o \
./nachos_initialCode/tools/binutils-2.25/libiberty/memmem.o \
./nachos_initialCode/tools/binutils-2.25/libiberty/memmove.o \
./nachos_initialCode/tools/binutils-2.25/libiberty/mempcpy.o \
./nachos_initialCode/tools/binutils-2.25/libiberty/memset.o \
./nachos_initialCode/tools/binutils-2.25/libiberty/mkstemps.o \
./nachos_initialCode/tools/binutils-2.25/libiberty/msdos.o \
./nachos_initialCode/tools/binutils-2.25/libiberty/objalloc.o \
./nachos_initialCode/tools/binutils-2.25/libiberty/obstack.o \
./nachos_initialCode/tools/binutils-2.25/libiberty/partition.o \
./nachos_initialCode/tools/binutils-2.25/libiberty/pex-common.o \
./nachos_initialCode/tools/binutils-2.25/libiberty/pex-djgpp.o \
./nachos_initialCode/tools/binutils-2.25/libiberty/pex-msdos.o \
./nachos_initialCode/tools/binutils-2.25/libiberty/pex-one.o \
./nachos_initialCode/tools/binutils-2.25/libiberty/pex-unix.o \
./nachos_initialCode/tools/binutils-2.25/libiberty/pex-win32.o \
./nachos_initialCode/tools/binutils-2.25/libiberty/pexecute.o \
./nachos_initialCode/tools/binutils-2.25/libiberty/physmem.o \
./nachos_initialCode/tools/binutils-2.25/libiberty/putenv.o \
./nachos_initialCode/tools/binutils-2.25/libiberty/random.o \
./nachos_initialCode/tools/binutils-2.25/libiberty/regex.o \
./nachos_initialCode/tools/binutils-2.25/libiberty/rename.o \
./nachos_initialCode/tools/binutils-2.25/libiberty/rindex.o \
./nachos_initialCode/tools/binutils-2.25/libiberty/safe-ctype.o \
./nachos_initialCode/tools/binutils-2.25/libiberty/setenv.o \
./nachos_initialCode/tools/binutils-2.25/libiberty/setproctitle.o \
./nachos_initialCode/tools/binutils-2.25/libiberty/sha1.o \
./nachos_initialCode/tools/binutils-2.25/libiberty/sigsetmask.o \
./nachos_initialCode/tools/binutils-2.25/libiberty/simple-object-coff.o \
./nachos_initialCode/tools/binutils-2.25/libiberty/simple-object-elf.o \
./nachos_initialCode/tools/binutils-2.25/libiberty/simple-object-mach-o.o \
./nachos_initialCode/tools/binutils-2.25/libiberty/simple-object-xcoff.o \
./nachos_initialCode/tools/binutils-2.25/libiberty/simple-object.o \
./nachos_initialCode/tools/binutils-2.25/libiberty/snprintf.o \
./nachos_initialCode/tools/binutils-2.25/libiberty/sort.o \
./nachos_initialCode/tools/binutils-2.25/libiberty/spaces.o \
./nachos_initialCode/tools/binutils-2.25/libiberty/splay-tree.o \
./nachos_initialCode/tools/binutils-2.25/libiberty/stack-limit.o \
./nachos_initialCode/tools/binutils-2.25/libiberty/stpcpy.o \
./nachos_initialCode/tools/binutils-2.25/libiberty/stpncpy.o \
./nachos_initialCode/tools/binutils-2.25/libiberty/strcasecmp.o \
./nachos_initialCode/tools/binutils-2.25/libiberty/strchr.o \
./nachos_initialCode/tools/binutils-2.25/libiberty/strdup.o \
./nachos_initialCode/tools/binutils-2.25/libiberty/strerror.o \
./nachos_initialCode/tools/binutils-2.25/libiberty/strncasecmp.o \
./nachos_initialCode/tools/binutils-2.25/libiberty/strncmp.o \
./nachos_initialCode/tools/binutils-2.25/libiberty/strndup.o \
./nachos_initialCode/tools/binutils-2.25/libiberty/strnlen.o \
./nachos_initialCode/tools/binutils-2.25/libiberty/strrchr.o \
./nachos_initialCode/tools/binutils-2.25/libiberty/strsignal.o \
./nachos_initialCode/tools/binutils-2.25/libiberty/strstr.o \
./nachos_initialCode/tools/binutils-2.25/libiberty/strtod.o \
./nachos_initialCode/tools/binutils-2.25/libiberty/strtol.o \
./nachos_initialCode/tools/binutils-2.25/libiberty/strtoul.o \
./nachos_initialCode/tools/binutils-2.25/libiberty/strverscmp.o \
./nachos_initialCode/tools/binutils-2.25/libiberty/timeval-utils.o \
./nachos_initialCode/tools/binutils-2.25/libiberty/tmpnam.o \
./nachos_initialCode/tools/binutils-2.25/libiberty/unlink-if-ordinary.o \
./nachos_initialCode/tools/binutils-2.25/libiberty/vasprintf.o \
./nachos_initialCode/tools/binutils-2.25/libiberty/vfork.o \
./nachos_initialCode/tools/binutils-2.25/libiberty/vfprintf.o \
./nachos_initialCode/tools/binutils-2.25/libiberty/vprintf.o \
./nachos_initialCode/tools/binutils-2.25/libiberty/vsnprintf.o \
./nachos_initialCode/tools/binutils-2.25/libiberty/vsprintf.o \
./nachos_initialCode/tools/binutils-2.25/libiberty/waitpid.o \
./nachos_initialCode/tools/binutils-2.25/libiberty/xatexit.o \
./nachos_initialCode/tools/binutils-2.25/libiberty/xexit.o \
./nachos_initialCode/tools/binutils-2.25/libiberty/xmalloc.o \
./nachos_initialCode/tools/binutils-2.25/libiberty/xmemdup.o \
./nachos_initialCode/tools/binutils-2.25/libiberty/xstrdup.o \
./nachos_initialCode/tools/binutils-2.25/libiberty/xstrerror.o \
./nachos_initialCode/tools/binutils-2.25/libiberty/xstrndup.o 

C_DEPS += \
./nachos_initialCode/tools/binutils-2.25/libiberty/_doprnt.d \
./nachos_initialCode/tools/binutils-2.25/libiberty/alloca.d \
./nachos_initialCode/tools/binutils-2.25/libiberty/argv.d \
./nachos_initialCode/tools/binutils-2.25/libiberty/asprintf.d \
./nachos_initialCode/tools/binutils-2.25/libiberty/atexit.d \
./nachos_initialCode/tools/binutils-2.25/libiberty/basename.d \
./nachos_initialCode/tools/binutils-2.25/libiberty/bcmp.d \
./nachos_initialCode/tools/binutils-2.25/libiberty/bcopy.d \
./nachos_initialCode/tools/binutils-2.25/libiberty/bsearch.d \
./nachos_initialCode/tools/binutils-2.25/libiberty/bzero.d \
./nachos_initialCode/tools/binutils-2.25/libiberty/calloc.d \
./nachos_initialCode/tools/binutils-2.25/libiberty/choose-temp.d \
./nachos_initialCode/tools/binutils-2.25/libiberty/clock.d \
./nachos_initialCode/tools/binutils-2.25/libiberty/concat.d \
./nachos_initialCode/tools/binutils-2.25/libiberty/copysign.d \
./nachos_initialCode/tools/binutils-2.25/libiberty/cp-demangle.d \
./nachos_initialCode/tools/binutils-2.25/libiberty/cp-demint.d \
./nachos_initialCode/tools/binutils-2.25/libiberty/cplus-dem.d \
./nachos_initialCode/tools/binutils-2.25/libiberty/crc32.d \
./nachos_initialCode/tools/binutils-2.25/libiberty/d-demangle.d \
./nachos_initialCode/tools/binutils-2.25/libiberty/dwarfnames.d \
./nachos_initialCode/tools/binutils-2.25/libiberty/dyn-string.d \
./nachos_initialCode/tools/binutils-2.25/libiberty/fdmatch.d \
./nachos_initialCode/tools/binutils-2.25/libiberty/ffs.d \
./nachos_initialCode/tools/binutils-2.25/libiberty/fibheap.d \
./nachos_initialCode/tools/binutils-2.25/libiberty/filename_cmp.d \
./nachos_initialCode/tools/binutils-2.25/libiberty/floatformat.d \
./nachos_initialCode/tools/binutils-2.25/libiberty/fnmatch.d \
./nachos_initialCode/tools/binutils-2.25/libiberty/fopen_unlocked.d \
./nachos_initialCode/tools/binutils-2.25/libiberty/getcwd.d \
./nachos_initialCode/tools/binutils-2.25/libiberty/getopt.d \
./nachos_initialCode/tools/binutils-2.25/libiberty/getopt1.d \
./nachos_initialCode/tools/binutils-2.25/libiberty/getpagesize.d \
./nachos_initialCode/tools/binutils-2.25/libiberty/getpwd.d \
./nachos_initialCode/tools/binutils-2.25/libiberty/getruntime.d \
./nachos_initialCode/tools/binutils-2.25/libiberty/gettimeofday.d \
./nachos_initialCode/tools/binutils-2.25/libiberty/hashtab.d \
./nachos_initialCode/tools/binutils-2.25/libiberty/hex.d \
./nachos_initialCode/tools/binutils-2.25/libiberty/index.d \
./nachos_initialCode/tools/binutils-2.25/libiberty/insque.d \
./nachos_initialCode/tools/binutils-2.25/libiberty/lbasename.d \
./nachos_initialCode/tools/binutils-2.25/libiberty/lrealpath.d \
./nachos_initialCode/tools/binutils-2.25/libiberty/make-relative-prefix.d \
./nachos_initialCode/tools/binutils-2.25/libiberty/make-temp-file.d \
./nachos_initialCode/tools/binutils-2.25/libiberty/md5.d \
./nachos_initialCode/tools/binutils-2.25/libiberty/memchr.d \
./nachos_initialCode/tools/binutils-2.25/libiberty/memcmp.d \
./nachos_initialCode/tools/binutils-2.25/libiberty/memcpy.d \
./nachos_initialCode/tools/binutils-2.25/libiberty/memmem.d \
./nachos_initialCode/tools/binutils-2.25/libiberty/memmove.d \
./nachos_initialCode/tools/binutils-2.25/libiberty/mempcpy.d \
./nachos_initialCode/tools/binutils-2.25/libiberty/memset.d \
./nachos_initialCode/tools/binutils-2.25/libiberty/mkstemps.d \
./nachos_initialCode/tools/binutils-2.25/libiberty/msdos.d \
./nachos_initialCode/tools/binutils-2.25/libiberty/objalloc.d \
./nachos_initialCode/tools/binutils-2.25/libiberty/obstack.d \
./nachos_initialCode/tools/binutils-2.25/libiberty/partition.d \
./nachos_initialCode/tools/binutils-2.25/libiberty/pex-common.d \
./nachos_initialCode/tools/binutils-2.25/libiberty/pex-djgpp.d \
./nachos_initialCode/tools/binutils-2.25/libiberty/pex-msdos.d \
./nachos_initialCode/tools/binutils-2.25/libiberty/pex-one.d \
./nachos_initialCode/tools/binutils-2.25/libiberty/pex-unix.d \
./nachos_initialCode/tools/binutils-2.25/libiberty/pex-win32.d \
./nachos_initialCode/tools/binutils-2.25/libiberty/pexecute.d \
./nachos_initialCode/tools/binutils-2.25/libiberty/physmem.d \
./nachos_initialCode/tools/binutils-2.25/libiberty/putenv.d \
./nachos_initialCode/tools/binutils-2.25/libiberty/random.d \
./nachos_initialCode/tools/binutils-2.25/libiberty/regex.d \
./nachos_initialCode/tools/binutils-2.25/libiberty/rename.d \
./nachos_initialCode/tools/binutils-2.25/libiberty/rindex.d \
./nachos_initialCode/tools/binutils-2.25/libiberty/safe-ctype.d \
./nachos_initialCode/tools/binutils-2.25/libiberty/setenv.d \
./nachos_initialCode/tools/binutils-2.25/libiberty/setproctitle.d \
./nachos_initialCode/tools/binutils-2.25/libiberty/sha1.d \
./nachos_initialCode/tools/binutils-2.25/libiberty/sigsetmask.d \
./nachos_initialCode/tools/binutils-2.25/libiberty/simple-object-coff.d \
./nachos_initialCode/tools/binutils-2.25/libiberty/simple-object-elf.d \
./nachos_initialCode/tools/binutils-2.25/libiberty/simple-object-mach-o.d \
./nachos_initialCode/tools/binutils-2.25/libiberty/simple-object-xcoff.d \
./nachos_initialCode/tools/binutils-2.25/libiberty/simple-object.d \
./nachos_initialCode/tools/binutils-2.25/libiberty/snprintf.d \
./nachos_initialCode/tools/binutils-2.25/libiberty/sort.d \
./nachos_initialCode/tools/binutils-2.25/libiberty/spaces.d \
./nachos_initialCode/tools/binutils-2.25/libiberty/splay-tree.d \
./nachos_initialCode/tools/binutils-2.25/libiberty/stack-limit.d \
./nachos_initialCode/tools/binutils-2.25/libiberty/stpcpy.d \
./nachos_initialCode/tools/binutils-2.25/libiberty/stpncpy.d \
./nachos_initialCode/tools/binutils-2.25/libiberty/strcasecmp.d \
./nachos_initialCode/tools/binutils-2.25/libiberty/strchr.d \
./nachos_initialCode/tools/binutils-2.25/libiberty/strdup.d \
./nachos_initialCode/tools/binutils-2.25/libiberty/strerror.d \
./nachos_initialCode/tools/binutils-2.25/libiberty/strncasecmp.d \
./nachos_initialCode/tools/binutils-2.25/libiberty/strncmp.d \
./nachos_initialCode/tools/binutils-2.25/libiberty/strndup.d \
./nachos_initialCode/tools/binutils-2.25/libiberty/strnlen.d \
./nachos_initialCode/tools/binutils-2.25/libiberty/strrchr.d \
./nachos_initialCode/tools/binutils-2.25/libiberty/strsignal.d \
./nachos_initialCode/tools/binutils-2.25/libiberty/strstr.d \
./nachos_initialCode/tools/binutils-2.25/libiberty/strtod.d \
./nachos_initialCode/tools/binutils-2.25/libiberty/strtol.d \
./nachos_initialCode/tools/binutils-2.25/libiberty/strtoul.d \
./nachos_initialCode/tools/binutils-2.25/libiberty/strverscmp.d \
./nachos_initialCode/tools/binutils-2.25/libiberty/timeval-utils.d \
./nachos_initialCode/tools/binutils-2.25/libiberty/tmpnam.d \
./nachos_initialCode/tools/binutils-2.25/libiberty/unlink-if-ordinary.d \
./nachos_initialCode/tools/binutils-2.25/libiberty/vasprintf.d \
./nachos_initialCode/tools/binutils-2.25/libiberty/vfork.d \
./nachos_initialCode/tools/binutils-2.25/libiberty/vfprintf.d \
./nachos_initialCode/tools/binutils-2.25/libiberty/vprintf.d \
./nachos_initialCode/tools/binutils-2.25/libiberty/vsnprintf.d \
./nachos_initialCode/tools/binutils-2.25/libiberty/vsprintf.d \
./nachos_initialCode/tools/binutils-2.25/libiberty/waitpid.d \
./nachos_initialCode/tools/binutils-2.25/libiberty/xatexit.d \
./nachos_initialCode/tools/binutils-2.25/libiberty/xexit.d \
./nachos_initialCode/tools/binutils-2.25/libiberty/xmalloc.d \
./nachos_initialCode/tools/binutils-2.25/libiberty/xmemdup.d \
./nachos_initialCode/tools/binutils-2.25/libiberty/xstrdup.d \
./nachos_initialCode/tools/binutils-2.25/libiberty/xstrerror.d \
./nachos_initialCode/tools/binutils-2.25/libiberty/xstrndup.d 


# Each subdirectory must supply rules for building sources it contributes
nachos_initialCode/tools/binutils-2.25/libiberty/%.o: ../nachos_initialCode/tools/binutils-2.25/libiberty/%.c
	@echo 'Building file: $<'
	@echo 'Invoking: Cross GCC Compiler'
	gcc -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


